// Bài học gốc theo cấu trúc Chương 5-16 của giáo trình do người học cung cấp.
// Nội dung, ví dụ và cách diễn giải được viết mới cho môi trường học trực tuyến.

const SOURCE_NOTE = 'Bài học được biên soạn mới theo cấu trúc chủ đề của giáo trình Quản trị Tài chính Doanh nghiệp do bạn cung cấp; không sao chép nguyên văn.'

const ACADEMIC_SOURCES = [
  {
    title: 'MIT OpenCourseWare 15.401 Finance Theory I',
    url: 'https://ocw.mit.edu/courses/15-401-finance-theory-i-fall-2008/',
    note: 'Khung chủ đề về báo cáo tài chính, giá trị thời gian, chứng khoán và quyết định đầu tư.',
  },
  {
    title: 'MIT OpenCourseWare 15.402 Finance Theory II',
    url: 'https://ocw.mit.edu/courses/15-402-finance-theory-ii-spring-2003/',
    note: 'Khung chủ đề về tài trợ, định giá, chi phí vốn và phân tích quyết định doanh nghiệp.',
  },
  {
    title: 'NYU Stern Corporate Finance · Aswath Damodaran',
    url: 'https://pages.stern.nyu.edu/~adamodar/New_Home_Page/corpfin.html',
    note: 'Danh mục bài giảng, bài tập và bảng tính dùng để đối chiếu cấu trúc khái niệm.',
  },
]

const practiceField = (id, label, placeholder, help) => ({ id, label, placeholder, help, required: true })

const buildPractice = (topic, link) => ({
  title: `Workpaper · ${topic.title}`,
  minutes: 20,
  objective: `Biến chủ đề ${topic.title.toLowerCase()} thành một sản phẩm có thể kiểm tra và dùng trong công việc finance.`,
  scenario: `Bạn là finance intern hỗ trợ ${topic.chapter.toLowerCase()}. Quản lý cần một ghi chú ngắn có phép tính, kết luận, giả định và rủi ro; không chấp nhận một con số đứng riêng không có đơn vị hoặc mốc thời gian.`,
  steps: [
    `Hoàn thành yêu cầu: ${topic.exercise}`,
    'Ghi rõ dữ kiện, đơn vị, mốc thời gian và công thức/logic đã dùng.',
    'Chuyển kết quả thành kết luận, khuyến nghị và một bước kiểm chứng tiếp theo.',
  ],
  fields: [
    practiceField('workpaper', 'Bài làm chính và phép tính', `Thực hiện: ${topic.exercise}`, 'Có thể dùng bảng hoặc gạch đầu dòng; ghi đơn vị và dấu tiền.'),
    practiceField('interpretation', 'Diễn giải cho quản lý', 'Kết quả nói gì về quyết định? Dữ kiện nào đã chắc chắn và giả định nào còn mở?', 'Đừng chỉ chép công thức; giải thích tác động kinh doanh.'),
    practiceField('recommendation', 'Khuyến nghị và kiểm chứng', 'Tôi đề xuất ... vì ...; cần kiểm tra ... bởi ... trước ngày ...', 'Nêu hành động, owner hoặc dữ liệu cần lấy tiếp.'),
  ],
  rubric: [
    'Tính đúng và nhất quán về dấu, đơn vị, kỳ và giả định.',
    'Giải thích được ý nghĩa quản trị, không biến giả định thành dữ kiện.',
    'Có khuyến nghị, rủi ro và bước kiểm chứng cụ thể.',
  ],
  modelAnswer: `Một bài làm tốt thực hiện đúng yêu cầu “${topic.exercise}”, cho phép người khác truy vết cách tính, rồi kết luận trong bối cảnh doanh nghiệp. Khi thiếu dữ liệu, hãy ghi rõ giả định và đề xuất cách kiểm chứng.`,
  link: link || '/corporate-finance',
})

function buildLesson(topic) {
  const {
    id, order, title, chapter, level = 'Trung cấp', minutes = 26,
    summary, concept, points, formula, example, work, warning, exercise, terms, link = '/corporate-finance',
  } = topic

  return {
    id: `tcdn-${id}`,
    track: 'Tài chính doanh nghiệp',
    courseOrder: order,
    title: `TC DN ${String(order).padStart(2, '0')} · ${title}`,
    chapter,
    level,
    minutes,
    summary,
    sourceNote: SOURCE_NOTE,
    sources: ACADEMIC_SOURCES,
    sections: [
      {
        h: '1. Bạn cần hiểu điều gì?',
        p: [
          summary,
          `Trong công việc finance, chủ đề này giúp bạn ${work.toLowerCase()}. Trước khi tính, hãy xác định rõ đơn vị tiền, thời điểm và giả định; cùng một con số nhưng khác kỳ hoặc khác đơn vị có thể dẫn đến kết luận sai.`,
        ],
      },
      {
        h: '2. Khái niệm và cách đặt câu hỏi',
        p: [concept],
        list: points,
      },
      {
        h: '3. Công thức và ví dụ số',
        p: [
          `Công thức hoặc khung tính: ${formula}`,
          example,
        ],
        tip: 'Đừng ném công thức vào bảng tính trước khi xác nhận dấu tiền vào/ra, mốc thời gian và việc con số là Actual, Budget hay Forecast.',
      },
      {
        h: '4. Dùng khi đi làm và điểm dễ sai',
        p: [
          work,
          `Điểm cần cảnh giác: ${warning}`,
          `Bài luyện tay: ${exercise}`,
        ],
        list: [
          'Ghi dữ kiện đã xác nhận riêng với giả định cần kiểm chứng.',
          'Nêu tác động bằng tiền hoặc bằng chỉ số có đơn vị rõ ràng.',
          'Kết thúc bằng hành động, người phụ trách và thời điểm xem lại.',
        ],
      },
    ],
    keyPoints: [
      concept,
      `Khung tính: ${formula}`,
      `Ứng dụng: ${work}`,
      `Tránh: ${warning}`,
    ],
    relatedTerms: terms,
    tryIt: { text: exercise, link },
    learningActivity: {
      scenario: `Bạn là finance intern đang hỗ trợ ${chapter.toLowerCase()}. Quản lý cần một ghi chú ngắn, có phép tính và điều kiện cần kiểm chứng trước khi quyết định.`,
      calculation: formula,
      decision: work,
      warning,
    },
    practice: buildPractice(topic, link),
  }
}

const TOPICS = [
  {
    id: 'gia-tri-thoi-gian-cua-tien', order: 15, title: 'Giá trị thời gian của tiền',
    chapter: 'Chương 5 · Giá trị thời gian của tiền', level: 'Cơ bản', minutes: 30,
    summary: 'Hiểu vì sao một đồng hôm nay và một đồng trong tương lai không có cùng giá trị, từ đó tránh cộng thẳng các dòng tiền ở những thời điểm khác nhau.',
    concept: 'Tiền hôm nay có thể được đầu tư, dùng để trả nợ hoặc giảm rủi ro thanh khoản; vì vậy nó thường đáng giá hơn cùng số tiền nhận sau. Lãi suất, lạm phát, rủi ro và khả năng dùng tiền là các lý do phải quy đổi thời điểm.',
    points: ['Giá trị tương lai trả lời: khoản tiền hôm nay sẽ thành bao nhiêu?', 'Giá trị hiện tại trả lời: khoản tiền tương lai đáng giá bao nhiêu hôm nay?', 'Lãi suất phải cùng kỳ với số kỳ: lãi tháng đi với số tháng, lãi năm đi với số năm.'],
    formula: 'FV = PV × (1 + r)^n; PV = FV / (1 + r)^n.',
    example: 'Gửi 100 triệu đồng với lãi suất 10% một năm: cuối năm một là 110 triệu; cuối năm hai là 121 triệu nếu lãi được nhập gốc. Ngược lại, 121 triệu nhận sau hai năm tại mức 10% có giá trị hiện tại là 100 triệu.',
    work: 'so sánh các phương án thu chi có thời điểm khác nhau thay vì nhìn số danh nghĩa',
    warning: 'dùng lãi suất năm cho dòng tiền tháng hoặc quên rằng rủi ro của hai dòng tiền có thể khác nhau',
    exercise: 'Tính giá trị hiện tại của 150 triệu đồng nhận sau 3 năm tại 9%/năm, rồi viết một câu giải thích ý nghĩa.',
    terms: ['Giá trị hiện tại (PV)', 'Giá trị tương lai (FV)', 'Lãi đơn', 'Lãi kép', 'Tỷ lệ chiết khấu'], link: '/corporate-finance#npv-lab',
  },
  {
    id: 'lai-don-lai-kep-va-lai-suat-hieu-dung', order: 16, title: 'Lãi đơn, lãi kép và lãi suất hiệu dụng',
    chapter: 'Chương 5 · Giá trị thời gian của tiền', level: 'Cơ bản', minutes: 28,
    summary: 'Phân biệt cách tính lãi đơn và lãi kép, đồng thời biết cách so sánh hai khoản vay hoặc đầu tư có tần suất ghép lãi khác nhau.',
    concept: 'Lãi đơn chỉ tính lãi trên gốc ban đầu; lãi kép tính lãi trên cả gốc và lãi tích lũy. Khi lãi được ghép nhiều lần trong năm, lãi suất hiệu dụng thường cao hơn lãi suất danh nghĩa cùng con số công bố.',
    points: ['Lãi danh nghĩa cần đi kèm số lần ghép lãi.', 'Lãi suất hiệu dụng dùng để so sánh chi phí/lợi tức cùng năm.', 'Phí vay, phí bảo lãnh và điều kiện trả trước có thể làm chi phí thực cao hơn lãi ghi trên hợp đồng.'],
    formula: 'EAR = (1 + r_danh_nghia / m)^m − 1.',
    example: 'Khoản vay báo lãi danh nghĩa 12% ghép lãi hằng tháng có EAR = (1 + 12%/12)^12 − 1, xấp xỉ 12,68%. Con số này phù hợp hơn để so với một khoản vay 12,4% ghép lãi hằng năm.',
    work: 'so sánh chi phí thật của các phương án vay, gửi tiền hoặc chiết khấu thanh toán',
    warning: 'so lãi suất quảng cáo mà bỏ qua chu kỳ ghép lãi, phí và lịch trả gốc',
    exercise: 'So sánh EAR của 10% ghép quý với 10,2% ghép năm; ghi phương án nào có lợi hơn cho người gửi tiền.',
    terms: ['Lãi suất danh nghĩa', 'Lãi suất hiệu dụng', 'Ghép lãi', 'Chi phí vay thực'], link: '/corporate-finance',
  },
  {
    id: 'nien-kim-va-lich-tra-no', order: 17, title: 'Niên kim, khoản vay và lịch trả nợ',
    chapter: 'Chương 5 · Giá trị thời gian của tiền', level: 'Trung cấp', minutes: 32,
    summary: 'Tính và đọc được dòng tiền đều theo kỳ, phân biệt trả đầu kỳ/cuối kỳ, và lập lịch trả nợ cho một khoản vay đơn giản.',
    concept: 'Niên kim là chuỗi dòng tiền bằng nhau phát sinh theo khoảng thời gian đều. Trong doanh nghiệp, nó xuất hiện ở tiền thuê, khoản vay trả góp, hợp đồng bảo trì và dòng tiền dự án ổn định.',
    points: ['Niên kim thông thường trả cuối kỳ; niên kim đầu kỳ trả ngay đầu kỳ.', 'Mỗi kỳ trả nợ thường gồm lãi trên dư nợ đầu kỳ và một phần gốc.', 'Lịch trả nợ giúp treasury thấy áp lực tiền, không chỉ tổng lãi trên P&L.'],
    formula: 'PV niên kim = PMT × [1 − 1/(1+r)^n] / r.',
    example: 'Vay 1 tỷ đồng, trả cuối mỗi năm 4 lần với lãi 10%. Khoản trả đều được tính từ công thức niên kim; sau đó lập bảng từng năm để tách lãi, gốc và dư nợ còn lại.',
    work: 'lập lịch tiền cho khoản vay hoặc hợp đồng thuê trước khi cam kết',
    warning: 'nhầm kỳ trả đầu với kỳ trả cuối hoặc chỉ nhìn khoản trả đều mà quên biến động tiền theo mùa',
    exercise: 'Lập 3 dòng đầu của lịch trả góp cho khoản vay 300 triệu, 12%/năm, trả đều cuối năm trong 3 năm.',
    terms: ['Niên kim', 'Khoản trả đều', 'Dư nợ gốc', 'Lịch trả nợ', 'Tiền thuê'], link: '/corporate-finance#cash-budget-lab',
  },
  {
    id: 'trai-phieu-va-loi-suat-den-han', order: 18, title: 'Trái phiếu, coupon và lợi suất đến hạn',
    chapter: 'Chương 6 · Định giá trái phiếu và cổ phiếu', level: 'Trung cấp', minutes: 32,
    summary: 'Hiểu trái phiếu là hợp đồng nợ, đọc được mệnh giá, coupon, kỳ hạn và lý do giá trái phiếu thay đổi khi lãi suất thị trường đổi.',
    concept: 'Trái phiếu hứa trả coupon định kỳ và hoàn mệnh giá khi đáo hạn. Giá hôm nay là giá trị hiện tại của các dòng tiền đó, chiết khấu bằng lợi suất mà thị trường yêu cầu cho mức rủi ro và kỳ hạn tương ứng.',
    points: ['Coupon là tiền lãi ghi trong điều khoản; lợi suất thị trường là tỷ lệ chiết khấu đang yêu cầu.', 'Lãi suất thị trường tăng thường làm giá trái phiếu coupon cố định giảm.', 'Rủi ro tín dụng, thanh khoản và kỳ hạn ảnh hưởng lợi suất, không chỉ lãi suất cơ bản.'],
    formula: 'Giá trái phiếu = PV(coupon từng kỳ) + PV(mệnh giá đáo hạn).',
    example: 'Trái phiếu mệnh giá 1.000, coupon 8%/năm, còn 3 năm. Nếu lợi suất yêu cầu là 10%, giá sẽ thấp hơn mệnh giá vì coupon 8% kém hấp dẫn hơn mức 10% thị trường đòi hỏi.',
    work: 'đánh giá chi phí huy động nợ và rủi ro lãi suất của doanh nghiệp',
    warning: 'coi coupon là lợi suất thực của người mua hoặc quên khả năng tổ chức phát hành không trả được nợ',
    exercise: 'Viết ba lý do khiến trái phiếu coupon 8% có thể giao dịch dưới mệnh giá.',
    terms: ['Trái phiếu', 'Mệnh giá', 'Coupon', 'Lợi suất đến hạn', 'Rủi ro tín dụng'], link: '/corporate-finance',
  },
  {
    id: 'dinh-gia-co-phieu-bang-co-tuc-nang-cao', order: 19, title: 'Định giá cổ phiếu bằng dòng cổ tức',
    chapter: 'Chương 6 · Định giá trái phiếu và cổ phiếu', level: 'Trung cấp', minutes: 34,
    summary: 'Hiểu mô hình cổ tức là một cách quy đổi dòng tiền kỳ vọng về hiện tại, biết điều kiện áp dụng và vì sao nó không phù hợp với mọi doanh nghiệp.',
    concept: 'Giá trị vốn chủ sở hữu có thể được nhìn như giá trị hiện tại của dòng tiền về cho cổ đông. Mô hình tăng trưởng đều phù hợp hơn với doanh nghiệp đã trưởng thành, chính sách chi trả ổn định và tăng trưởng dài hạn thấp hơn chi phí vốn chủ.',
    points: ['Dòng cổ tức phải là dòng tiền bền vững, không chỉ mức trả một năm bất thường.', 'Tốc độ tăng trưởng dài hạn không nên cao hơn khả năng tăng trưởng kinh tế dài hạn mãi mãi.', 'Với công ty không trả cổ tức hoặc thay đổi mạnh, cần dùng cách tiếp cận khác như FCF hoặc bội số để kiểm tra chéo.'],
    formula: 'P0 = D1 / (ke − g), với ke > g.',
    example: 'Cổ tức kỳ vọng năm sau 2.000 đồng/cổ phiếu, chi phí vốn chủ 14%, tăng trưởng dài hạn 5%: giá trị mô hình là 2.000/(14%−5%) = khoảng 22.222 đồng.',
    work: 'kiểm tra tính hợp lý của giả định cổ tức và kỳ vọng của cổ đông',
    warning: 'dùng g gần bằng hoặc lớn hơn ke để tạo ra giá trị phi thực tế',
    exercise: 'Thay đổi g từ 4% lên 6% trong ví dụ và mô tả vì sao giá trị nhạy mạnh.',
    terms: ['Cổ tức', 'Chi phí vốn chủ', 'Tăng trưởng ổn định', 'Mô hình Gordon'], link: '/corporate-finance#npv-lab',
  },
  {
    id: 'gia-tri-thi-truong-va-gia-tri-so-sach', order: 20, title: 'Giá trị thị trường, giá trị sổ sách và giới hạn bội số',
    chapter: 'Chương 6 · Định giá trái phiếu và cổ phiếu', level: 'Trung cấp', minutes: 28,
    summary: 'Phân biệt giá trị sổ sách với giá trị thị trường và dùng P/E, P/B như công cụ đặt câu hỏi thay vì nhãn rẻ/đắt.',
    concept: 'Giá trị sổ sách phản ánh số còn lại theo quy tắc kế toán; giá trị thị trường phản ánh kỳ vọng về tiền, tăng trưởng và rủi ro trong tương lai. Khoảng cách giữa hai giá trị có thể hợp lý nếu tài sản vô hình, khả năng sinh lời hoặc rủi ro khác nhau.',
    points: ['P/B phù hợp hơn khi giá trị sổ sách tài sản có ý nghĩa và chất lượng tài sản được kiểm tra.', 'P/E cần đi cùng tăng trưởng, biên, đòn bẩy và chất lượng lợi nhuận.', 'So sánh chỉ hữu ích khi cùng ngành, cùng chu kỳ và cùng định nghĩa chỉ tiêu.'],
    formula: 'P/B = Giá trị vốn hóa / Vốn chủ sở hữu sổ sách; P/E = Giá thị trường / EPS.',
    example: 'Hai công ty có P/E 8 và 16. Công ty P/E 8 có thể rẻ, nhưng cũng có thể thị trường dự báo lợi nhuận giảm hoặc nợ cao. Chênh lệch không thể được giải thích chỉ bằng hai số 8 và 16.',
    work: 'lập bảng so sánh định giá có giả định rõ ràng trước khi kiến nghị',
    warning: 'kết luận “P/E thấp là rẻ” hoặc trộn chỉ tiêu sau thuế với giá trị doanh nghiệp trước nợ',
    exercise: 'Soạn bảng ba cột so P/E, ROE và nợ/vốn cho hai doanh nghiệp cùng ngành, rồi ghi dữ liệu còn thiếu.',
    terms: ['Giá trị sổ sách', 'Giá trị thị trường', 'P/E', 'P/B', 'EPS'], link: '/compare',
  },
  {
    id: 'quyet-dinh-dau-tu-von', order: 21, title: 'Quyết định đầu tư vốn và vòng đời dự án',
    chapter: 'Chương 7 · Kỹ thuật phân tích dự án đầu tư', level: 'Trung cấp', minutes: 30,
    summary: 'Biết biến một ý tưởng như mua máy, mở chi nhánh hoặc triển khai phần mềm thành business case có phạm vi, dòng tiền và tiêu chí ra quyết định.',
    concept: 'Ngân sách vốn là quy trình chọn các khoản đầu tư dài hạn. Một dự án cần được xác định mục tiêu, các phương án thay thế, dòng tiền tăng thêm, rủi ro, người sở hữu và cách đo kết quả sau triển khai.',
    points: ['Sàng lọc: dự án có phù hợp chiến lược, pháp lý và năng lực vận hành không?', 'Phân tích: dòng tiền tăng thêm, thời điểm, tỷ lệ chiết khấu và độ nhạy.', 'Phê duyệt và hậu kiểm: so Actual với business case để cải thiện các giả định sau này.'],
    formula: 'Quyết định tốt = lợi ích tăng thêm − toàn bộ chi phí liên quan, quy đổi về cùng thời điểm.',
    example: 'Máy mới giảm nhân công 300 triệu mỗi năm nhưng cần CAPEX 1 tỷ, bảo trì 40 triệu, tồn kho phụ tùng tăng 100 triệu và lắp đặt mất 2 tháng. Business case phải có toàn bộ các dòng này, không chỉ 300 triệu tiết kiệm.',
    work: 'chuẩn hóa đề xuất đầu tư để ban điều hành so sánh dự án theo cùng chuẩn',
    warning: 'đưa doanh thu toàn công ty vào dự án hoặc bỏ qua chi phí triển khai, vốn lưu động và giá trị thay thế',
    exercise: 'Lập danh sách tiền ra ban đầu, tiền vào, chi phí định kỳ và rủi ro cho dự án mua máy đóng gói.',
    terms: ['Ngân sách vốn', 'CAPEX', 'Business case', 'Dòng tiền tăng thêm', 'Hậu kiểm'], link: '/corporate-finance#npv-lab',
  },
  {
    id: 'payback-arr-va-gioi-han', order: 22, title: 'Payback, ARR và giới hạn của chỉ tiêu đơn giản',
    chapter: 'Chương 7 · Kỹ thuật phân tích dự án đầu tư', level: 'Trung cấp', minutes: 28,
    summary: 'Biết dùng thời gian hoàn vốn và tỷ suất sinh lời kế toán như chỉ tiêu phụ cho thanh khoản hoặc truyền thông, không dùng chúng thay thế NPV.',
    concept: 'Payback đo thời gian thu hồi vốn; ARR dựa trên lợi nhuận kế toán tương đối. Chúng dễ giải thích nhưng đều có điểm mù: payback có thể bỏ qua tiền sau mốc hoàn vốn và giá trị thời gian; ARR không phản ánh dòng tiền đúng thời điểm.',
    points: ['Payback hữu ích khi thanh khoản, rủi ro công nghệ hoặc tuổi thọ ngắn là vấn đề lớn.', 'Payback chiết khấu tốt hơn payback thường nhưng vẫn không nói toàn bộ giá trị dự án.', 'ARR phải nêu rõ mẫu số và lợi nhuận kế toán được dùng.'],
    formula: 'Payback đơn giản = vốn đầu tư ban đầu / dòng tiền năm bình quân (chỉ khi dòng tiền đều).',
    example: 'Dự án A hoàn vốn 2 năm rồi tạo ít tiền; dự án B hoàn vốn 3 năm nhưng tạo dòng tiền lớn năm 4-8. Nếu chỉ chọn A theo payback, doanh nghiệp có thể bỏ qua giá trị lớn của B.',
    work: 'thảo luận thanh khoản dự án cùng NPV thay vì dùng một chỉ tiêu để quyết định tất cả',
    warning: 'gọi dự án “tốt” chỉ vì hoàn vốn nhanh hoặc bỏ qua dòng tiền sau thời gian hoàn vốn',
    exercise: 'Cho hai dự án có thời gian hoàn vốn 2 và 3 năm, viết hai câu hỏi cần trả lời trước khi chọn dự án 2 năm.',
    terms: ['Payback', 'Payback chiết khấu', 'ARR', 'Thanh khoản dự án'], link: '/corporate-finance#npv-lab',
  },
  {
    id: 'npv-irr-pi-va-xung-dot', order: 23, title: 'NPV, IRR, PI và khi các chỉ tiêu mâu thuẫn',
    chapter: 'Chương 7 · Kỹ thuật phân tích dự án đầu tư', level: 'Nâng cao', minutes: 36,
    summary: 'Tính được NPV, hiểu trực giác IRR và biết ưu tiên NPV khi các chỉ tiêu tạo ra lựa chọn khác nhau giữa các dự án loại trừ nhau.',
    concept: 'NPV đo giá trị tiền hiện tại tăng thêm sau khi trừ vốn đầu tư và chi phí vốn. IRR là tỷ lệ chiết khấu làm NPV bằng 0. PI cho biết giá trị hiện tại dòng tiền trên một đơn vị vốn đầu tư, hữu ích khi vốn bị giới hạn.',
    points: ['Nếu NPV > 0 tại tỷ lệ chiết khấu phù hợp, dự án tạo giá trị theo giả định.', 'IRR có thể gây hiểu nhầm khi dòng tiền đổi dấu nhiều lần hoặc dự án có quy mô/thời điểm khác nhau.', 'Với dự án loại trừ nhau, NPV thường phù hợp hơn để tối đa hóa tổng giá trị.'],
    formula: 'NPV = Σ[CFt/(1+r)^t] − CF0; IRR là r khiến NPV = 0.',
    example: 'Dự án chi 1.000 triệu hôm nay, nhận 450 triệu trong 3 năm. Tại 12%, phải chiết khấu từng năm rồi trừ 1.000; không được cộng 1.350 rồi gọi phần chênh là giá trị tạo ra.',
    work: 'đánh giá dự án và giải thích lựa chọn bằng dòng tiền, chi phí vốn và độ nhạy',
    warning: 'dùng IRR duy nhất hoặc để Excel chọn một nghiệm khi dòng tiền có nhiều lần đổi dấu',
    exercise: 'Dùng lab NPV, tăng WACC 2 điểm phần trăm và giảm dòng tiền 15%; ghi điều kiện nào làm dự án đổi kết luận.',
    terms: ['NPV', 'IRR', 'PI', 'Chi phí vốn', 'Dự án loại trừ nhau'], link: '/corporate-finance#npv-lab',
  },
  {
    id: 'dong-tien-tang-them-va-chi-phi-co-hoi', order: 24, title: 'Dòng tiền tăng thêm, chi phí chìm và chi phí cơ hội',
    chapter: 'Chương 8 · Xác định dòng tiền trong các quyết định đầu tư', level: 'Nâng cao', minutes: 34,
    summary: 'Xác định đúng những dòng tiền thay đổi vì dự án, tách chi phí chìm khỏi chi phí cơ hội và tránh đếm hai lần chi phí tài trợ.',
    concept: 'Phân tích dự án theo nguyên tắc độc lập: chỉ đưa vào những dòng tiền chênh lệch giữa làm và không làm dự án. Chi phí đã phát sinh không thay đổi quyết định là chi phí chìm; nguồn lực đang có nhưng dùng cho dự án sẽ mất cơ hội dùng vào việc khác nên vẫn có chi phí cơ hội.',
    points: ['Chi phí khảo sát đã trả tuần trước thường là chi phí chìm.', 'Mặt bằng doanh nghiệp đang bỏ trống nhưng có thể cho thuê phải tính tiền thuê bị bỏ lỡ.', 'Lãi vay thường không nằm trong FCF dự án khi dùng WACC, để tránh trừ chi phí vốn hai lần.'],
    formula: 'Dòng tiền dự án = dòng tiền có dự án − dòng tiền không có dự án.',
    example: 'Doanh nghiệp đã chi 50 triệu nghiên cứu máy mới. Khoản này không đổi dù mua hay không mua nên không đưa vào NPV. Nhưng nếu dùng kho có thể cho thuê 15 triệu/năm, 15 triệu là chi phí cơ hội liên quan.',
    work: 'làm sạch business case để chỉ còn lợi ích và chi phí thực sự thay đổi do quyết định',
    warning: 'đưa chi phí chìm vào để “bảo vệ” quyết định cũ hoặc bỏ qua chi phí cơ hội vì không có hóa đơn tiền mặt',
    exercise: 'Phân loại: phí tư vấn đã trả, tiền thuê kho bị bỏ lỡ, lãi vay, tiền mua máy, doanh thu tăng thêm thành liên quan/không liên quan.',
    terms: ['Dòng tiền chênh lệch', 'Chi phí chìm', 'Chi phí cơ hội', 'Nguyên tắc độc lập', 'FCF'], link: '/corporate-finance#npv-lab',
  },
  {
    id: 'du-bao-dong-tien-du-an-tu-ebit', order: 25, title: 'Dự báo dòng tiền dự án từ EBIT',
    chapter: 'Chương 8 · Xác định dòng tiền trong các quyết định đầu tư', level: 'Nâng cao', minutes: 36,
    summary: 'Chuyển dự báo doanh thu, chi phí và khấu hao thành dòng tiền hoạt động sau thuế của dự án theo cách có thể kiểm tra.',
    concept: 'EBIT là lợi nhuận trước lãi vay và thuế. Khi đánh giá FCF dự án, bắt đầu từ EBIT để tách quyết định đầu tư khỏi quyết định tài trợ; sau đó trừ thuế hoạt động và cộng lại khấu hao vì khấu hao giảm thuế nhưng không phải chi tiền trong kỳ.',
    points: ['Dự báo doanh thu từ driver như sản lượng, giá, công suất hoặc tỷ lệ chuyển đổi.', 'Giá vốn và chi phí vận hành phải phản ánh phần tăng thêm, không lấy nguyên cả P&L công ty.', 'Khấu hao ảnh hưởng thuế, dù không phải dòng tiền ra ngay.'],
    formula: 'OCF = EBIT × (1 − T) + Khấu hao, trong mô hình cơ bản.',
    example: 'EBIT tăng thêm 200 triệu, thuế 20%, khấu hao 90 triệu: OCF = 200×(1−20%) + 90 = 250 triệu. Con số 250 chưa trừ CAPEX hoặc vốn lưu động tăng thêm.',
    work: 'xây cầu nối từ giả định vận hành đến FCF dùng trong NPV',
    warning: 'trừ lãi vay khi đang sử dụng WACC hoặc quên cộng lại khấu hao sau khi tính thuế',
    exercise: 'Tính OCF khi doanh thu tăng thêm 800, chi phí tiền mặt 500, khấu hao 100, thuế 20%.',
    terms: ['EBIT', 'NOPAT', 'Khấu hao', 'OCF', 'Lá chắn thuế'], link: '/corporate-finance#npv-lab',
  },
  {
    id: 'von-luu-dong-gia-tri-thanh-ly-va-do-nhay', order: 26, title: 'Vốn lưu động, giá trị thanh lý và độ nhạy dự án',
    chapter: 'Chương 8 · Xác định dòng tiền trong các quyết định đầu tư', level: 'Nâng cao', minutes: 34,
    summary: 'Hoàn thiện mô hình dự án bằng vốn lưu động, giá trị cuối kỳ, thuế khi thanh lý và sensitivity thay vì chỉ dùng dòng tiền đều.',
    concept: 'Nhiều dự án cần tồn kho, phải thu hoặc tiền vận hành trước khi tạo doanh thu. Đây là tiền bị khóa vào vốn lưu động và thường được thu hồi khi dự án kết thúc. Giá bán tài sản cuối dự án cũng có thể tạo tiền và tác động thuế tùy giá trị sổ sách.',
    points: ['Tăng vốn lưu động là dòng tiền ra; thu hồi vốn lưu động cuối dự án là dòng tiền vào.', 'Giá thanh lý khác giá trị sổ sách có thể tạo lãi/lỗ chịu thuế.', 'Sensitivity tập trung vào driver chi phối NPV như giá, sản lượng, CAPEX, WACC hoặc tiến độ.'],
    formula: 'FCF cuối kỳ = OCF + thu hồi vốn lưu động + giá trị thanh lý sau thuế.',
    example: 'Dự án cần thêm 120 triệu tồn kho lúc đầu và thu lại toàn bộ vào năm 4. Khoản 120 là dòng tiền ra năm 0, dòng tiền vào năm 4; bỏ qua nó sẽ làm NPV bị cao ảo.',
    work: 'hoàn thiện business case với các dòng tiền thường bị bỏ sót và nêu ngưỡng rủi ro',
    warning: 'coi vốn lưu động là chi phí vĩnh viễn hoặc bỏ qua thuế khi bán tài sản cuối kỳ',
    exercise: 'Thêm 80 triệu vốn lưu động vào dự án 3 năm, thu hồi cuối năm 3; mô tả tác động lên NPV theo trực giác.',
    terms: ['Vốn lưu động ròng', 'Giá trị thanh lý', 'Giá trị sổ sách', 'Sensitivity', 'Free cash flow'], link: '/corporate-finance#npv-lab',
  },
  {
    id: 'ty-suat-sinh-loi-thuc-danh-nghia', order: 27, title: 'Tỷ suất sinh lời danh nghĩa, thực tế và kỳ vọng',
    chapter: 'Chương 9 · Lợi tức và rủi ro trong hoạt động đầu tư', level: 'Trung cấp', minutes: 30,
    summary: 'Phân biệt lợi tức tiền tệ, tỷ suất sinh lời danh nghĩa và thực tế để không nhầm tăng giá danh nghĩa với sức mua tăng thật.',
    concept: 'Tỷ suất sinh lời biểu diễn kết quả tương đối trên vốn bỏ ra. Lợi tức thực điều chỉnh ảnh hưởng lạm phát, hữu ích khi đánh giá mục tiêu dài hạn hoặc chi phí vốn trong môi trường giá thay đổi.',
    points: ['Lợi tức tuyệt đối là chênh lệch tiền; tỷ suất sinh lời chia chênh lệch cho vốn đầu kỳ.', 'Lợi tức danh nghĩa chưa loại lạm phát.', 'Lợi tức kỳ vọng là trung bình có trọng số của các kịch bản, không phải lời hứa.'],
    formula: 'r_thực = (1 + r_danh_nghĩa)/(1 + lạm phát) − 1; chỉ khi dùng r_danh_nghĩa − lạm phát mới là xấp xỉ.',
    example: 'Đầu tư tăng 12% trong năm lạm phát 8% tạo lợi tức thực xấp xỉ (1,12/1,08)−1 = 3,7%, không phải 12%.',
    work: 'đánh giá kết quả đầu tư và mục tiêu lợi nhuận trong bối cảnh lạm phát và rủi ro',
    warning: 'so lợi tức danh nghĩa giữa các năm lạm phát khác nhau như thể chúng ngang nhau',
    exercise: 'Tính lợi tức thực xấp xỉ khi lợi tức danh nghĩa 9% và lạm phát 5%.',
    terms: ['Tỷ suất sinh lời', 'Lợi tức danh nghĩa', 'Lợi tức thực', 'Lạm phát', 'Kỳ vọng'], link: '/learn/quan-tri-rui-ro',
  },
  {
    id: 'rui-ro-phan-sai-va-do-lech-chuan', order: 28, title: 'Rủi ro, phương sai và độ lệch chuẩn',
    chapter: 'Chương 9 · Lợi tức và rủi ro trong hoạt động đầu tư', level: 'Trung cấp', minutes: 34,
    summary: 'Đo được mức phân tán của tỷ suất sinh lời và hiểu vì sao cùng lợi tức kỳ vọng nhưng mức rủi ro có thể rất khác nhau.',
    concept: 'Rủi ro không chỉ là khả năng lỗ; trong tài chính nó thường được đo bằng độ không chắc chắn quanh kết quả kỳ vọng. Phương sai và độ lệch chuẩn tóm tắt mức dao động của các kết quả có thể xảy ra hoặc dữ liệu lịch sử.',
    points: ['Độ lệch chuẩn lớn nghĩa là kết quả phân tán mạnh quanh kỳ vọng.', 'Dữ liệu quá khứ chỉ là bằng chứng, không bảo đảm phân phối tương lai lặp lại.', 'Rủi ro cần gắn với thời hạn, thanh khoản và khả năng chịu lỗ của người ra quyết định.'],
    formula: 'Phương sai kỳ vọng = Σ[p × (r − r_kỳ_vọng)^2]; độ lệch chuẩn = căn bậc hai phương sai.',
    example: 'Hai dự án đều kỳ vọng 12%. Dự án A dao động 10-14%; B có thể -20% hoặc 44%. Trung bình giống nhau nhưng B có độ lệch chuẩn lớn hơn, nên cần mức bù rủi ro cao hơn.',
    work: 'đưa rủi ro vào lựa chọn đầu tư và trao đổi rõ mức biến động có thể chấp nhận',
    warning: 'xem độ lệch chuẩn là toàn bộ rủi ro hoặc dùng một chuỗi lịch sử quá ngắn để kết luận chắc chắn',
    exercise: 'Lập hai kịch bản tốt/xấu cho một dự án, gán xác suất và giải thích dự án nào cần sensitivity sâu hơn.',
    terms: ['Rủi ro', 'Phương sai', 'Độ lệch chuẩn', 'Xác suất', 'Tỷ suất sinh lời kỳ vọng'], link: '/learn/quan-tri-rui-ro',
  },
  {
    id: 'danh-muc-beta-va-capm', order: 29, title: 'Danh mục, beta và trực giác CAPM',
    chapter: 'Chương 9 · Lợi tức và rủi ro trong hoạt động đầu tư', level: 'Nâng cao', minutes: 36,
    summary: 'Hiểu đa dạng hóa giảm rủi ro riêng lẻ, beta đo mức nhạy với thị trường và CAPM là một khung ước lượng chi phí vốn chủ có điều kiện.',
    concept: 'Rủi ro riêng của một khách hàng, nhà máy hay sản phẩm có thể giảm bằng đa dạng hóa; rủi ro hệ thống như lãi suất, suy thoái hoặc thị trường chung không biến mất chỉ bằng cách thêm nhiều khoản đầu tư. Beta mô tả mức nhạy tương đối với biến động thị trường.',
    points: ['Beta lớn hơn 1 thường dao động mạnh hơn thị trường; beta dưới 1 thường ít nhạy hơn, nhưng không mặc định an toàn.', 'CAPM liên kết lợi suất yêu cầu với lãi suất phi rủi ro, beta và phần bù rủi ro thị trường.', 'Trong corporate finance, beta và CAPM là đầu vào ước lượng, cần kiểm tra với ngành, địa lý và cấu trúc dự án.'],
    formula: 'ke = rf + beta × (rm − rf).',
    example: 'Nếu rf 4%, beta 1,2 và phần bù thị trường 7%, chi phí vốn chủ theo CAPM là 4% + 1,2×7% = 12,4%. Đây là giả định mô hình, không phải mức lợi nhuận chắc chắn.',
    work: 'ước lượng tỷ lệ yêu cầu của vốn chủ và giải thích mức rủi ro hệ thống của dự án',
    warning: 'dùng beta từ công ty khác ngành hoặc coi CAPM là sự thật tuyệt đối thay vì một phương pháp ước lượng',
    exercise: 'Tính ke khi rf 3,5%, beta 0,9 và phần bù thị trường 6%; nêu một hạn chế của kết quả.',
    terms: ['Danh mục', 'Beta', 'CAPM', 'Rủi ro hệ thống', 'Phần bù rủi ro thị trường'], link: '/corporate-finance',
  },
  {
    id: 'thi-truong-hieu-qua-va-thong-tin', order: 30, title: 'Thị trường hiệu quả và cách dùng thông tin',
    chapter: 'Chương 10 · Tính hiệu quả của thị trường tài chính', level: 'Trung cấp', minutes: 28,
    summary: 'Hiểu giả thuyết thị trường hiệu quả như một cảnh báo về chi phí và tốc độ phản ánh thông tin, không phải tuyên bố rằng giá luôn hoàn hảo.',
    concept: 'Thị trường hiệu quả nói rằng thông tin sẵn có được phản ánh nhanh vào giá đến mức khó kiếm lợi nhuận vượt trội một cách bền vững sau chi phí. Các mức yếu, trung bình và mạnh khác nhau theo tập thông tin được giả định phản ánh.',
    points: ['Dạng yếu liên quan dữ liệu giá/lợi tức quá khứ.', 'Dạng trung bình liên quan thông tin công khai.', 'Dạng mạnh là giả định cực đoan hơn về mọi thông tin, thường không phải mô tả thực tế hoàn hảo.'],
    formula: 'Không có công thức đơn; trọng tâm là so kết quả sau chi phí với benchmark phù hợp.',
    example: 'Một tin lợi nhuận tốt được công bố không có nghĩa giá sẽ tăng mãi; một phần kỳ vọng có thể đã nằm trong giá trước tin. Câu hỏi đúng là kết quả thực khác kỳ vọng thị trường bao nhiêu.',
    work: 'đặt kỳ vọng thận trọng khi dùng dữ liệu thị trường và chọn benchmark cho phân tích',
    warning: 'diễn giải “thị trường hiệu quả” thành “không cần phân tích” hoặc “giá luôn đúng trong mọi khoảnh khắc”',
    exercise: 'Viết hai câu phân biệt “thông tin tốt” với “thông tin tốt hơn kỳ vọng” trong phản ứng giá cổ phiếu.',
    terms: ['Thị trường hiệu quả', 'Benchmark', 'Thông tin công khai', 'Kỳ vọng thị trường'], link: '/learn/thi-truong-va-bang-gia',
  },
  {
    id: 'cong-bo-thong-tin-va-thoi-diem-huy-dong-von', order: 31, title: 'Công bố thông tin và thời điểm huy động vốn',
    chapter: 'Chương 10 · Tính hiệu quả của thị trường tài chính', level: 'Ứng dụng', minutes: 26,
    summary: 'Biết vì sao chất lượng thông tin, thời điểm phát hành và giao tiếp với nhà đầu tư ảnh hưởng chi phí vốn, nhưng không được dùng để thao túng kỳ vọng.',
    concept: 'Nhà đầu tư yêu cầu lợi suất cao hơn khi thông tin mờ, rủi ro khó đánh giá hoặc niềm tin thấp. Công bố nhất quán, dự báo có cơ sở và giải thích chênh lệch giúp giảm bất định; nhưng doanh nghiệp phải tuân thủ quy định và không dùng thông tin chọn lọc để đánh lừa thị trường.',
    points: ['Công bố cần nhất quán về kỳ, chỉ tiêu và giả định.', 'Thời điểm phát hành chịu tác động điều kiện thị trường, nhu cầu vốn và quy định.', 'Pressure price ngắn hạn không thay thế giá trị dài hạn của doanh nghiệp.'],
    formula: 'Chi phí vốn tăng khi rủi ro cảm nhận và bất định thông tin tăng.',
    example: 'Nếu doanh nghiệp cần phát hành cổ phần khi giá giảm mạnh nhưng chưa có báo cáo giải thích nguyên nhân, nhà đầu tư có thể yêu cầu chiết khấu lớn hơn. Finance cần so sánh chi phí trì hoãn với chi phí pha loãng/điều kiện thị trường.',
    work: 'chuẩn bị dữ liệu minh bạch cho quyết định huy động vốn và truyền thông với bên cấp vốn',
    warning: 'hứa hẹn forecast không có cơ sở hoặc coi “thời điểm thị trường” là lý do để bỏ qua nhu cầu tiền thực',
    exercise: 'Liệt kê ba thông tin một nhà cho vay cần trước khi duyệt hạn mức vốn lưu động.',
    terms: ['Công bố thông tin', 'Bất cân xứng thông tin', 'Huy động vốn', 'Chi phí vốn'], link: '/corporate-finance',
  },
  {
    id: 'von-chu-va-loi-nhuan-giu-lai', order: 32, title: 'Vốn chủ sở hữu và lợi nhuận giữ lại',
    chapter: 'Chương 11 · Nguồn vốn của doanh nghiệp', level: 'Trung cấp', minutes: 28,
    summary: 'Hiểu vốn góp và lợi nhuận giữ lại là nguồn tài trợ có chi phí cơ hội, không phải “tiền miễn phí”, đồng thời biết đánh đổi với chia cổ tức hoặc vay nợ.',
    concept: 'Vốn chủ gồm vốn góp của chủ sở hữu và lợi nhuận được giữ lại để tái đầu tư. Không có khoản lãi bắt buộc như nợ, nhưng cổ đông vẫn yêu cầu lợi tức tương xứng rủi ro và có thể bị pha loãng nếu phát hành thêm.',
    points: ['Lợi nhuận giữ lại chỉ nên dùng nếu tạo giá trị cao hơn lựa chọn trả lại tiền cho cổ đông.', 'Phát hành thêm làm tăng vốn nhưng có chi phí phát hành, pha loãng và tín hiệu thị trường.', 'Vốn chủ linh hoạt hơn nợ trong giai đoạn dòng tiền biến động.'],
    formula: 'Nguồn vốn nội bộ = lợi nhuận sau thuế − cổ tức tiền mặt − các khoản phân phối khác.',
    example: 'Doanh nghiệp lãi 500 triệu, giữ lại 350 triệu và trả cổ tức 150 triệu. 350 triệu không miễn phí: cần so NPV các dự án sử dụng 350 triệu với lợi ích cổ đông có thể nhận nếu được phân phối.',
    work: 'đánh giá sức chứa vốn nội bộ và cách giải thích quyết định giữ lại lợi nhuận',
    warning: 'gọi lợi nhuận giữ lại là vốn không chi phí hoặc giữ tiền khi không có dự án tạo giá trị',
    exercise: 'Viết hai tiêu chí để quyết định dùng lợi nhuận giữ lại cho dự án thay vì chia cổ tức.',
    terms: ['Vốn chủ sở hữu', 'Lợi nhuận giữ lại', 'Pha loãng', 'Cổ tức', 'Chi phí cơ hội'], link: '/corporate-finance',
  },
  {
    id: 'von-no-trai-phieu-va-thue-tai-san', order: 33, title: 'Vốn nợ, trái phiếu và thuê tài sản',
    chapter: 'Chương 11 · Nguồn vốn của doanh nghiệp', level: 'Trung cấp', minutes: 32,
    summary: 'So sánh vay ngân hàng, trái phiếu và thuê tài sản theo lịch tiền, tài sản đảm bảo, điều kiện hợp đồng và rủi ro tái cấp vốn.',
    concept: 'Nợ cho phép dùng tiền của bên cho vay để đầu tư hôm nay, đổi lại nghĩa vụ lãi/gốc, tài sản đảm bảo và điều khoản hợp đồng. Thuê có thể linh hoạt về tài sản nhưng cũng là chuỗi nghĩa vụ tiền cần so sánh với mua.',
    points: ['Vay ngân hàng thường có quan hệ, tài sản đảm bảo và covenant cụ thể.', 'Trái phiếu có thể đa dạng nguồn vốn nhưng chịu chi phí phát hành, kỳ hạn và thị trường.', 'Thuê vận hành/thuê tài chính cần so tổng PV nghĩa vụ, linh hoạt và rủi ro công nghệ.'],
    formula: 'Chi phí nợ không chỉ là lãi suất: tổng nghĩa vụ tiền = lãi + gốc + phí + chi phí vi phạm điều khoản.',
    example: 'Hai phương án mua xe giao hàng bằng vay hoặc thuê đều có khoản trả hàng tháng. So sánh phải bao gồm tiền trả, bảo trì, giá trị còn lại, giới hạn sử dụng, bảo hiểm và PV của từng lịch tiền.',
    work: 'so sánh phương án tài trợ tài sản dựa trên lịch tiền và điều kiện hợp đồng',
    warning: 'chỉ chọn lãi suất thấp nhất mà bỏ qua lịch đáo hạn, covenant, tài sản thế chấp và rủi ro lãi suất biến động',
    exercise: 'Lập bảng bốn tiêu chí so vay ngân hàng, thuê tài sản và dùng tiền mặt cho một máy móc.',
    terms: ['Vốn nợ', 'Covenant', 'Tài sản đảm bảo', 'Trái phiếu', 'Thuê tài sản'], link: '/corporate-finance#cash-budget-lab',
  },
  {
    id: 'chi-phi-no-va-chi-phi-von-chu', order: 34, title: 'Chi phí nợ và chi phí vốn chủ',
    chapter: 'Chương 12 · Chi phí vốn', level: 'Nâng cao', minutes: 32,
    summary: 'Ước lượng được trực giác chi phí của từng nguồn vốn và hiểu vì sao lãi suất vay quan sát được cần điều chỉnh theo thuế, phí và rủi ro.',
    concept: 'Chi phí nợ là lợi suất người cho vay yêu cầu, có thể quan sát từ hợp đồng hoặc thị trường và thường được điều chỉnh sau thuế trong WACC. Chi phí vốn chủ không có hóa đơn định kỳ nhưng là lợi suất cổ đông yêu cầu vì chịu rủi ro sau cùng.',
    points: ['Chi phí nợ trước thuế phải phản ánh lãi hiện hành, phí và khả năng tái cấp vốn.', 'Chi phí nợ sau thuế chỉ có ý nghĩa khi doanh nghiệp thực sự có khả năng hưởng lợi thuế.', 'Chi phí vốn chủ có thể ước lượng bằng CAPM, mô hình cổ tức hoặc kiểm tra chéo nhiều phương pháp.'],
    formula: 'rD_sau_thuế = rD × (1 − T); ke có thể dùng CAPM hoặc mô hình cổ tức.',
    example: 'Lãi vay 10%, thuế 20% tạo chi phí nợ sau thuế lý thuyết 8%. Nhưng nếu doanh nghiệp lỗ và chưa dùng được lá chắn thuế, 8% có thể quá lạc quan cho giai đoạn gần.',
    work: 'ước lượng đầu vào chi phí vốn có thể giải thích được cho business case',
    warning: 'dùng lãi suất lịch sử cũ, bỏ qua phí hoặc mặc định mọi đồng lãi vay đều tạo lá chắn thuế',
    exercise: 'Tính chi phí nợ sau thuế với rD 11% và thuế 20%; nêu một điều kiện khiến kết quả này không phù hợp.',
    terms: ['Chi phí nợ', 'Lá chắn thuế', 'Chi phí vốn chủ', 'CAPM', 'Lợi suất yêu cầu'], link: '/corporate-finance#npv-lab',
  },
  {
    id: 'wacc-va-trong-so-von', order: 35, title: 'WACC và cách chọn trọng số vốn',
    chapter: 'Chương 12 · Chi phí vốn', level: 'Nâng cao', minutes: 36,
    summary: 'Tính được WACC cơ bản, hiểu trọng số theo giá trị thị trường và biết khi nào WACC toàn công ty không nên dùng cho một dự án riêng.',
    concept: 'WACC là chi phí bình quân có trọng số của nợ và vốn chủ, thường dùng làm tỷ lệ chiết khấu cho dự án có rủi ro tương tự hoạt động cốt lõi. Nó là khung ước lượng chứ không phải nút bấm mặc định.',
    points: ['Trọng số nên phản ánh cấu trúc vốn mục tiêu hoặc giá trị thị trường phù hợp, không chỉ số sổ sách cũ.', 'Nợ và vốn chủ phải nhất quán về tiền tệ, kỳ và điều kiện thị trường.', 'Dự án mới có rủi ro rất khác cần tỷ lệ riêng hoặc điều chỉnh rõ ràng.'],
    formula: 'WACC = wD × rD × (1−T) + wE × rE.',
    example: 'Nợ 40%, rD 9%, thuế 20%, vốn chủ 60%, rE 16%: WACC = 40%×9%×80% + 60%×16% = 12,48%.',
    work: 'chọn tỷ lệ chiết khấu và giải thích giả định vốn cho dự án',
    warning: 'dùng một WACC cho mọi dự án, trộn giá trị sổ sách với chi phí vốn thị trường hoặc để trọng số không cộng 100%',
    exercise: 'Tự tính WACC với nợ 30%, rD 10%, thuế 20%, vốn chủ 70%, rE 15%.',
    terms: ['WACC', 'Trọng số vốn', 'Giá trị thị trường', 'Chi phí nợ', 'Chi phí vốn chủ'], link: '/corporate-finance#npv-lab',
  },
  {
    id: 'chi-phi-von-du-an-va-phi-phat-hanh', order: 36, title: 'Chi phí vốn riêng cho dự án và phí phát hành',
    chapter: 'Chương 12 · Chi phí vốn', level: 'Nâng cao', minutes: 32,
    summary: 'Điều chỉnh chi phí vốn theo rủi ro dự án và nhận diện lúc phí phát hành nên nằm trong dòng tiền ban đầu thay vì làm sai tỷ lệ chiết khấu.',
    concept: 'Một dự án năng lượng ổn định, một dự án thị trường mới và một dự án phần mềm rủi ro cao không nhất thiết nên chiết khấu bằng cùng WACC. Phí phát hành cũng là tiền thực; cách đưa vào mô hình phải nhất quán để không đếm hai lần.',
    points: ['Dùng công ty thuần tương đồng hoặc đánh giá định tính để tham chiếu rủi ro dự án.', 'Điều chỉnh tỷ lệ phải có lý do, phạm vi và sensitivity.', 'Phí phát hành vốn mới thường nên được phản ánh ở nhu cầu vốn/dòng tiền ban đầu nếu đó là chi phí gia tăng của quyết định.'],
    formula: 'NPV dự án dùng r phù hợp rủi ro dự án; vốn huy động gộp = vốn cần dùng / (1 − tỷ lệ phí) khi phí trừ vào tiền nhận.',
    example: 'Dự án cần ròng 1.000 triệu và phí phát hành 5%; nếu phí khấu trừ từ tiền thu, doanh nghiệp phải huy động 1.000/(1−5%) = khoảng 1.052,6 triệu.',
    work: 'bảo vệ lựa chọn tỷ lệ chiết khấu và mô hình hóa chi phí huy động minh bạch',
    warning: 'tăng WACC tùy tiện để “an toàn” hoặc trừ phí phát hành ở cả dòng tiền lẫn chi phí vốn',
    exercise: 'Viết ba yếu tố khiến một dự án mới cần tỷ lệ chiết khấu khác hoạt động hiện hữu.',
    terms: ['Pure play', 'Rủi ro dự án', 'Phí phát hành', 'Tỷ lệ chiết khấu', 'Sensitivity'], link: '/corporate-finance#npv-lab',
  },
  {
    id: 'don-bay-va-co-cau-von', order: 37, title: 'Đòn bẩy và cơ cấu vốn',
    chapter: 'Chương 13 · Cơ cấu vốn', level: 'Nâng cao', minutes: 34,
    summary: 'Hiểu cơ cấu vốn là lựa chọn giữa lợi ích thuế và kỷ luật của nợ với chi phí kiệt quệ tài chính và rủi ro mất linh hoạt.',
    concept: 'Cơ cấu vốn thể hiện tỷ trọng nợ và vốn chủ tài trợ tài sản. Nợ có thể rẻ hơn và tạo lá chắn thuế, nhưng tạo cam kết cố định. Khi dòng tiền xấu, cùng một đòn bẩy có thể chuyển từ công cụ tăng hiệu quả thành nguyên nhân khủng hoảng thanh khoản.',
    points: ['Đòn bẩy vận hành và đòn bẩy tài chính đều có thể khuếch đại biến động.', 'Cơ cấu tối ưu khác nhau theo độ ổn định CFO, tài sản thế chấp, tăng trưởng và khả năng tiếp cận vốn.', 'Tỷ lệ nợ mục tiêu cần được kiểm tra bằng kịch bản xấu, không chỉ mức trung bình.'],
    formula: 'Nợ/Vốn chủ = tổng nợ có lãi / vốn chủ; phải đọc cùng lịch đáo hạn và khả năng trả lãi.',
    example: 'Hai công ty cùng EBIT 200 triệu. Công ty A lãi vay 20 triệu, B lãi vay 120 triệu. Khi EBIT giảm 30%, lợi nhuận sau lãi của B co lại nhanh hơn nhiều dù doanh thu giảm giống nhau.',
    work: 'đánh giá sức chịu đựng nợ và đề xuất mức đòn bẩy phù hợp kịch bản vận hành',
    warning: 'chọn tỷ lệ nợ theo một con số ngành mà bỏ qua mùa vụ, đáo hạn và khả năng tái cấp vốn',
    exercise: 'Lập kịch bản EBIT giảm 20% cho doanh nghiệp có chi phí lãi 30% EBIT; ghi chỉ số cần theo dõi.',
    terms: ['Cơ cấu vốn', 'Đòn bẩy tài chính', 'Khả năng trả lãi', 'Tái cấp vốn', 'Lá chắn thuế'], link: '/corporate-finance',
  },
  {
    id: 'tradeoff-kiet-que-va-chi-phi-dai-dien', order: 38, title: 'Đánh đổi thuế, kiệt quệ tài chính và chi phí đại diện',
    chapter: 'Chương 13 · Cơ cấu vốn', level: 'Nâng cao', minutes: 32,
    summary: 'Nhìn cơ cấu vốn bằng trade-off thực tế: nợ tạo lợi ích nhưng có chi phí khủng hoảng, xung đột lợi ích và hạn chế đầu tư.',
    concept: 'Lý thuyết trade-off cho rằng doanh nghiệp cân bằng lợi ích của nợ với chi phí kiệt quệ tài chính, chi phí đại diện và mất linh hoạt. Chi phí kiệt quệ không chỉ là phí luật sư khi phá sản mà còn là mất khách, mất nhà cung cấp, nhân sự và dự án tốt.',
    points: ['Nợ cao có thể khiến cổ đông thích dự án rủi ro hơn vì phần lỗ có thể rơi vào chủ nợ.', 'Chủ nợ phản ứng bằng covenant, tài sản đảm bảo và giám sát, tạo chi phí đại diện.', 'Doanh nghiệp tăng trưởng có nhiều cơ hội đầu tư cần giữ linh hoạt để không bỏ lỡ dự án NPV dương.'],
    formula: 'Giá trị nợ tối ưu không có công thức cố định; đánh giá bằng lợi ích thuế so với chi phí kỳ vọng do distress và mất linh hoạt.',
    example: 'Một công ty có thương hiệu phụ thuộc niềm tin khách hàng có thể chịu tổn thất lớn khi tin đồn thiếu tiền xuất hiện, ngay cả trước khi chính thức vỡ nợ. Vì vậy nợ “có vẻ rẻ” có thể trở nên đắt hơn trong thực tế.',
    work: 'đưa chi phí định tính và rủi ro hệ thống vào đề xuất cơ cấu vốn',
    warning: 'chỉ tính lá chắn thuế mà bỏ qua giá trị cơ hội bị mất khi doanh nghiệp gần vi phạm covenant',
    exercise: 'Liệt kê ba chi phí kiệt quệ tài chính không xuất hiện ngay trên báo cáo kết quả kinh doanh.',
    terms: ['Trade-off', 'Kiệt quệ tài chính', 'Chi phí đại diện', 'Covenant', 'Tính linh hoạt tài chính'], link: '/corporate-finance',
  },
  {
    id: 'trat-tu-phan-hang-nguon-von', order: 39, title: 'Trật tự phân hạng nguồn vốn',
    chapter: 'Chương 13 · Cơ cấu vốn', level: 'Nâng cao', minutes: 28,
    summary: 'Hiểu vì sao doanh nghiệp thường ưu tiên vốn nội bộ, sau đó nợ, rồi mới phát hành vốn chủ khi thông tin bất cân xứng và chi phí phát hành quan trọng.',
    concept: 'Lý thuyết trật tự phân hạng mô tả xu hướng ưu tiên nguồn vốn: tiền/lợi nhuận giữ lại trước, nợ sau, vốn chủ cuối cùng. Không phải luật bắt buộc, nhưng giúp giải thích hành vi khi quản lý biết nhiều hơn thị trường về triển vọng doanh nghiệp.',
    points: ['Vốn nội bộ giảm phí phát hành và tín hiệu tiêu cực tiềm năng.', 'Nợ có thể là lựa chọn kế tiếp nhưng bị giới hạn bởi sức chịu nợ.', 'Phát hành vốn chủ có thể hợp lý khi rủi ro cao, cần vốn dài hạn hoặc tránh distress.'],
    formula: 'Thứ tự tham chiếu: vốn nội bộ → nợ → vốn chủ; phải kiểm tra sức chịu đựng và mục tiêu chiến lược.',
    example: 'Doanh nghiệp đang có dự án NPV dương nhưng CFO ngắn hạn yếu. Dùng tiền nội bộ có thể thiếu thanh khoản; vay thêm có thể vi phạm covenant; phát hành vốn chủ có thể hợp lý dù pha loãng. Không có một đáp án mặc định.',
    work: 'giải thích lựa chọn nguồn vốn bằng tính sẵn có, chi phí, tín hiệu và rủi ro',
    warning: 'áp dụng trật tự như quy tắc cứng hoặc coi phát hành vốn chủ luôn là tín hiệu xấu',
    exercise: 'Xếp thứ tự ba nguồn vốn cho một công ty tăng trưởng nhanh nhưng CFO biến động, kèm điều kiện làm thứ tự thay đổi.',
    terms: ['Trật tự phân hạng', 'Thông tin bất cân xứng', 'Vốn nội bộ', 'Pha loãng', 'Sức chứa nợ'], link: '/corporate-finance',
  },
  {
    id: 'chinh-sach-co-tuc-tien-mat', order: 40, title: 'Chính sách cổ tức tiền mặt',
    chapter: 'Chương 14 · Chính sách cổ tức', level: 'Trung cấp', minutes: 28,
    summary: 'Đánh giá cổ tức như quyết định phân bổ vốn: trả tiền cho cổ đông hôm nay hay giữ lại để đầu tư dự án tạo giá trị hơn.',
    concept: 'Cổ tức tiền mặt là phân phối một phần tiền/vốn cho cổ đông. Chính sách bền vững cần cân bằng lợi nhuận, dòng tiền, cơ hội đầu tư, cam kết với cổ đông, điều kiện nợ và khả năng duy trì qua chu kỳ.',
    points: ['Ngày công bố, ngày không hưởng quyền và ngày thanh toán có ý nghĩa khác nhau.', 'Cổ tức cần tiền mặt, không chỉ lợi nhuận kế toán.', 'Một mức trả ổn định thường là tín hiệu cam kết nên cắt giảm có thể ảnh hưởng kỳ vọng.'],
    formula: 'Tỷ lệ chi trả = cổ tức tiền mặt / lợi nhuận sau thuế; tỷ lệ giữ lại = 1 − tỷ lệ chi trả.',
    example: 'Công ty lãi 1.000 triệu nhưng CFO chỉ 300 triệu do phải thu tăng. Trả cổ tức 600 triệu có thể buộc công ty vay thêm; quyết định phải xem tiền, covenant và dự án chứ không chỉ tỷ lệ lợi nhuận.',
    work: 'đánh giá khả năng chi trả và thông điệp của chính sách phân phối',
    warning: 'lấy lợi nhuận kế toán làm tiền sẵn có hoặc hứa mức cổ tức không chịu được khi dòng tiền suy giảm',
    exercise: 'Nêu ba dòng cần kiểm tra trước khi đề xuất tăng cổ tức tiền mặt.',
    terms: ['Cổ tức tiền mặt', 'Tỷ lệ chi trả', 'Tỷ lệ giữ lại', 'Ngày không hưởng quyền', 'CFO'], link: '/corporate-finance',
  },
  {
    id: 'mua-lai-co-phieu-va-chia-tach', order: 41, title: 'Mua lại cổ phiếu, cổ tức cổ phiếu và chia tách',
    chapter: 'Chương 14 · Chính sách cổ tức', level: 'Trung cấp', minutes: 28,
    summary: 'Phân biệt các hình thức phân phối/điều chỉnh vốn chủ và biết cách đánh giá động cơ, tác động tiền mặt, số cổ phiếu và tín hiệu đi kèm.',
    concept: 'Mua lại cổ phiếu dùng tiền công ty để giảm số cổ phiếu lưu hành hoặc nắm giữ cổ phiếu quỹ. Cổ tức cổ phiếu và chia tách thường không tự tạo tiền mới; chúng thay đổi số đơn vị cổ phiếu và cách trình bày vốn chủ.',
    points: ['Mua lại có thể linh hoạt hơn cổ tức định kỳ nhưng vẫn tiêu tốn tiền mặt.', 'EPS có thể tăng vì mẫu số giảm, không nhất thiết vì hoạt động kinh doanh tốt hơn.', 'Chia tách làm giá mỗi cổ phiếu thay đổi theo tỷ lệ nhưng không tự làm giá trị kinh tế tăng.'],
    formula: 'EPS = lợi nhuận thuộc cổ đông phổ thông / số cổ phiếu bình quân; mua lại làm mẫu số có thể giảm.',
    example: 'Công ty có lãi 100 triệu và 10 triệu cổ phiếu, EPS 10 đồng. Nếu mua lại để còn 8 triệu cổ phiếu, EPS thành 12,5 đồng nếu lợi nhuận không đổi; nhưng cần xem tiền  dùng mua lại có thể tạo NPV tốt hơn ở nơi khác không.',
    work: 'phân tích quyết định phân phối vốn chủ bằng tiền, giá trị và động cơ thực',
    warning: 'coi EPS tăng sau mua lại là bằng chứng chắc chắn doanh nghiệp tạo giá trị hoặc quên chi phí cơ hội của tiền mặt',
    exercise: 'Giải thích vì sao chia tách 1 thành 2 không tự làm giá trị cổ đông tăng gấp đôi.',
    terms: ['Mua lại cổ phiếu', 'Cổ phiếu quỹ', 'EPS', 'Cổ tức cổ phiếu', 'Chia tách cổ phiếu'], link: '/corporate-finance',
  },
  {
    id: 'von-luu-dong-rong-va-thanh-khoan', order: 42, title: 'Vốn lưu động ròng và thanh khoản vận hành',
    chapter: 'Chương 15 · Quản trị tài chính ngắn hạn', level: 'Trung cấp', minutes: 30,
    summary: 'Hiểu vốn lưu động ròng là phần đệm thanh khoản vận hành và biết vì sao tăng trưởng có thể hút tiền dù P&L đang đẹp.',
    concept: 'Vốn lưu động ròng thường là tài sản ngắn hạn trừ nợ ngắn hạn. Nó không phải toàn bộ tiền sẵn có, nhưng cho thấy mức nguồn lực ngắn hạn còn lại sau nghĩa vụ ngắn hạn. Quản trị tốt phải cân bằng an toàn thanh khoản với chi phí giữ tài sản nhàn rỗi.',
    points: ['Tồn kho và phải thu tăng nhanh hơn doanh thu có thể hút tiền.', 'Nợ phải trả tài trợ một phần hoạt động nhưng không nên kéo dài vô hạn.', 'Chính sách thận trọng giữ nhiều tài sản ngắn hạn hơn, đổi lại hiệu quả có thể thấp hơn.'],
    formula: 'NWC = tài sản ngắn hạn − nợ ngắn hạn.',
    example: 'Tài sản ngắn hạn 700 triệu, nợ ngắn hạn 550 triệu cho NWC 150 triệu. Nếu doanh thu tăng khiến phải thu tăng 200 triệu nhưng không có nguồn tài trợ, tiền có thể căng dù lợi nhuận tăng.',
    work: 'đánh giá khả năng vận hành ngắn hạn và ảnh hưởng tiền của kế hoạch tăng trưởng',
    warning: 'coi NWC dương là luôn tốt mà không kiểm tra chất lượng phải thu, tồn kho và lịch nợ đến hạn',
    exercise: 'Tính NWC khi tiền 80, phải thu 220, tồn kho 300, nợ ngắn hạn 450; nêu một điều cần kiểm tra.',
    terms: ['Vốn lưu động ròng', 'Tài sản ngắn hạn', 'Nợ ngắn hạn', 'Thanh khoản'], link: '/corporate-finance#working-capital-lab',
  },
  {
    id: 'chu-ky-tien-mat-va-driver-thu-chi', order: 43, title: 'Chu kỳ kinh doanh và chu kỳ chuyển đổi tiền',
    chapter: 'Chương 15 · Quản trị tài chính ngắn hạn', level: 'Trung cấp', minutes: 32,
    summary: 'Tính và diễn giải CCC để tìm xem tiền đang nằm ở tồn kho, khoản phải thu hay điều khoản thanh toán nhà cung cấp.',
    concept: 'Chu kỳ kinh doanh theo dõi từ mua/nhập hàng đến bán; chu kỳ chuyển đổi tiền điều chỉnh thêm thời gian được tài trợ bởi nhà cung cấp. CCC ngắn hơn thường giải phóng tiền, nhưng luôn phải cân nhắc dịch vụ khách hàng và quan hệ chuỗi cung ứng.',
    points: ['DIO đo ngày tồn kho; DSO đo ngày thu khách; DPO đo ngày trả nhà cung cấp.', 'Một ngày thay đổi ở mỗi chỉ số có thể quy ra lượng tiền dựa trên doanh thu/giá vốn mỗi ngày.', 'So sánh với lịch sử và cùng mô hình kinh doanh quan trọng hơn một ngưỡng chung.'],
    formula: 'CCC = DIO + DSO − DPO.',
    example: 'DIO 50 ngày, DSO 40 ngày, DPO 30 ngày tạo CCC 60 ngày. Nếu DSO tăng lên 55, tiền bị giam thêm 15 ngày trước khi xét các biến khác.',
    work: 'xác định driver tiền để ưu tiên thu nợ, tồn kho hoặc điều khoản mua hàng',
    warning: 'ép DPO cao bằng mọi giá làm mất chiết khấu hoặc nhà cung cấp, hoặc giảm tồn kho làm mất doanh thu',
    exercise: 'Dùng lab CCC, thay DSO tăng 10 ngày và viết tác động/rủi ro/hành động trong ba dòng.',
    terms: ['Chu kỳ chuyển đổi tiền', 'DIO', 'DSO', 'DPO', 'Vốn lưu động'], link: '/corporate-finance#working-capital-lab',
  },
  {
    id: 'chinh-sach-tai-tro-ngan-han', order: 44, title: 'Chính sách tài trợ tài sản ngắn hạn',
    chapter: 'Chương 15 · Quản trị tài chính ngắn hạn', level: 'Trung cấp', minutes: 30,
    summary: 'So sánh chính sách thận trọng, khớp kỳ hạn và mạo hiểm khi tài trợ vốn lưu động, đồng thời hiểu rủi ro tái cấp vốn của nợ ngắn hạn.',
    concept: 'Tài sản ngắn hạn có phần thường xuyên và phần mùa vụ. Doanh nghiệp cần quyết định phần nào dùng vốn dài hạn, phần nào dùng nợ ngắn hạn. Nợ ngắn hạn thường rẻ hơn nhưng rủi ro lãi suất, gia hạn và thanh khoản cao hơn.',
    points: ['Chính sách thận trọng dùng nhiều vốn dài hạn, an toàn hơn nhưng có thể tốn chi phí.', 'Khớp kỳ hạn cố gắng ghép thời hạn nguồn vốn với tuổi thọ tài sản.', 'Mạo hiểm dùng nhiều nợ ngắn hạn, có thể giảm chi phí nhưng tạo rủi ro refinancing.'],
    formula: 'Nhu cầu vốn ngắn hạn = phần biến động của tài sản ngắn hạn − nguồn tài trợ tự phát và tiền sẵn có.',
    example: 'Một nhà bán lẻ tăng tồn kho 3 tháng trước Tết. Nếu vay 12 tháng cho phần tồn kho chỉ cần 3 tháng, chi phí có thể cao; nếu vay 1 tháng nhưng hàng bán chậm, rủi ro đáo hạn tăng.',
    work: 'thiết kế cấu trúc tài trợ phù hợp mùa vụ và mức chịu đựng thanh khoản',
    warning: 'chọn nợ ngắn hạn chỉ vì lãi thấp mà không có kịch bản gia hạn hoặc bán hàng chậm',
    exercise: 'Nêu một ví dụ tài sản ngắn hạn thường xuyên và một ví dụ tài sản mùa vụ của cửa hàng online.',
    terms: ['Khớp kỳ hạn', 'Nợ ngắn hạn', 'Tái cấp vốn', 'Tài sản thường xuyên', 'Tài sản mùa vụ'], link: '/corporate-finance#cash-budget-lab',
  },
  {
    id: 'lap-ngan-sach-tien-mat', order: 45, title: 'Lập ngân sách tiền mặt theo tuần và tháng',
    chapter: 'Chương 15 · Quản trị tài chính ngắn hạn', level: 'Ứng dụng', minutes: 36,
    summary: 'Xây được ngân sách tiền mặt từ lịch thu, lịch chi và số dư đầu kỳ để phát hiện thiếu tiền trước khi nó thành khủng hoảng.',
    concept: 'Cash budget không dự báo lợi nhuận; nó dự báo thời điểm tiền thực vào và ra. Nó bắt đầu từ số dư đầu kỳ, cộng các khoản thu dự kiến, trừ khoản chi, sau đó so tiền cuối kỳ với mức tối thiểu để quyết định vay, đầu tư tạm thời hoặc điều chỉnh hoạt động.',
    points: ['Lịch thu cần dựa trên điều khoản thanh toán, tuổi nợ và khả năng thu thực tế.', 'Lịch chi gồm nhà cung cấp, lương, thuế, lãi/gốc, CAPEX và các nghĩa vụ không nằm cùng kỳ P&L.', 'Rolling 13 tuần thường hữu ích hơn chỉ nhìn tháng cuối vì cảnh báo sớm.'],
    formula: 'Tiền cuối kỳ = tiền đầu kỳ + thu tiền − chi tiền ± vay/trả nợ/đầu tư ngắn hạn.',
    example: 'Tiền đầu tuần 100 triệu, thu 120, trả NCC 140, lương 40, chi khác 20: tiền cuối tuần là 20 triệu. Nếu mức tối thiểu là 50, treasury phải xử lý khoảng trống 30 trước khi đến hạn.',
    work: 'dự báo thanh khoản và chuẩn bị nguồn vốn hoặc hành động vận hành sớm',
    warning: 'lấy doanh thu làm khoản thu tiền hoặc quên các khoản gốc vay, thuế và CAPEX',
    exercise: 'Dùng lab ngân sách tiền mặt, tạo một tuần âm tiền rồi ghi hai cách xử lý và đánh đổi của mỗi cách.',
    terms: ['Cash budget', 'Lịch thu tiền', 'Lịch chi tiền', 'Số dư tối thiểu', 'Rolling forecast'], link: '/corporate-finance#cash-budget-lab',
  },
  {
    id: 'ke-hoach-tai-chinh-ngan-han-va-vay', order: 46, title: 'Kế hoạch tài chính ngắn hạn và khoản vay',
    chapter: 'Chương 15 · Quản trị tài chính ngắn hạn', level: 'Ứng dụng', minutes: 32,
    summary: 'Kết nối forecast doanh thu, vốn lưu động, cash budget và hạn mức vay để chuẩn bị tài trợ trước khi doanh nghiệp thiếu tiền.',
    concept: 'Kế hoạch tài chính ngắn hạn chuyển các giả định vận hành thành nhu cầu tiền và nợ theo kỳ. Nó không chỉ trả lời “cần vay bao nhiêu” mà còn trả lời “cần vay từ khi nào, trả khi nào và điều gì làm kế hoạch không còn đúng”.',
    points: ['Hạn mức tín dụng nên được thương lượng trước khi khoản thiếu tiền xuất hiện.', 'Lãi vay và phí cam kết làm thay đổi cash budget.', 'Kịch bản downside nên có giả định thu chậm, doanh số thấp và chi phí bất thường.'],
    formula: 'Nhu cầu vay kỳ t = max(0, số dư tối thiểu − tiền cuối kỳ trước tài trợ).',
    example: 'Cash budget cho thấy tuần 5 âm 80 triệu và tuần 6 thu về 150 triệu. Có thể dùng hạn mức ngắn hạn 80 triệu, nhưng cần tính lãi, phí và rủi ro khách trả chậm làm tuần 6 không đạt kế hoạch.',
    work: 'chuẩn bị đề xuất hạn mức và kịch bản trả nợ dựa trên forecast tiền',
    warning: 'vay đúng số thiếu hụt cơ sở mà không dự phòng rủi ro hoặc không xem covenant/hạn mức còn lại',
    exercise: 'Viết một yêu cầu cấp hạn mức gồm số tiền, thời hạn, nguồn trả nợ và hai rủi ro cần quản lý.',
    terms: ['Hạn mức tín dụng', 'Vay ngắn hạn', 'Covenant', 'Forecast tiền', 'Thanh khoản'], link: '/corporate-finance#cash-budget-lab',
  },
  {
    id: 'quan-ly-tien-va-tien-dang-chuyen', order: 47, title: 'Quản lý tiền, tiền đang chuyển và tiền nhàn rỗi',
    chapter: 'Chương 16 · Quản lý tiền, tồn kho và tín dụng thương mại', level: 'Ứng dụng', minutes: 30,
    summary: 'Thiết kế quy trình thu chi, tập trung tiền và đầu tư tiền nhàn rỗi để giảm số dư thụ động nhưng vẫn giữ an toàn thanh khoản.',
    concept: 'Quản lý tiền tốt tối ưu tốc độ thu, kiểm soát tốc độ chi trong khuôn khổ hợp đồng và luật pháp, đồng thời đầu tư tạm thời phần dư khi không làm ảnh hưởng nghĩa vụ sắp tới. Tiền đang chuyển (float) là chênh lệch thời gian giữa ghi nhận và tiền thực sẵn sàng.',
    points: ['Tập trung tiền giúp nhìn tổng thanh khoản thay vì tiền rải rác nhiều tài khoản.', 'Tự động đối soát thu và phê duyệt chi giảm lỗi, gian lận và tiền treo.', 'Tiền nhàn rỗi chỉ đầu tư khi lịch tiền đã bảo đảm mức đệm cần thiết.'],
    formula: 'Số dư tiền mục tiêu phụ thuộc biến động thu chi, chi phí giao dịch, lãi suất cơ hội và mức rủi ro chấp nhận.',
    example: 'Công ty có 300 triệu ở ba tài khoản nhưng phải trả 250 triệu từ một tài khoản ngày mai. Nếu không có cơ chế tập trung/chuyển tiền kịp, tổng tiền cao vẫn không giải quyết được rủi ro thanh toán.',
    work: 'cải thiện khả năng quan sát tiền, đối soát và sử dụng tiền tạm thời nhàn rỗi',
    warning: 'đầu tư hết tiền dư nhìn thấy mà bỏ qua lịch chi gần hoặc trì hoãn thanh toán trái điều khoản để làm đẹp số dư',
    exercise: 'Vẽ quy trình từ lúc khách thanh toán đến lúc tiền được đối soát và sẵn sàng dùng; đánh dấu một điểm dễ chậm.',
    terms: ['Treasury', 'Float', 'Tập trung tiền', 'Đối soát', 'Tiền nhàn rỗi'], link: '/corporate-finance#cash-budget-lab',
  },
  {
    id: 'quan-ly-ton-kho-va-eoq', order: 48, title: 'Quản lý tồn kho và trực giác EOQ',
    chapter: 'Chương 16 · Quản lý tiền, tồn kho và tín dụng thương mại', level: 'Ứng dụng', minutes: 32,
    summary: 'Cân bằng chi phí đặt hàng, chi phí giữ hàng và mức phục vụ khách hàng; dùng EOQ như điểm xuất phát chứ không phải đáp án cứng.',
    concept: 'Tồn kho giúp đáp ứng khách hàng và bảo vệ sản xuất trước biến động, nhưng giam tiền, chiếm kho và có nguy cơ lỗi thời. EOQ mô tả lượng đặt hàng cân bằng chi phí đặt hàng với chi phí giữ hàng trong giả định đơn giản.',
    points: ['Chi phí giữ hàng gồm vốn bị giam, kho bãi, bảo hiểm, hao hụt và lỗi thời.', 'Chi phí đặt hàng gồm xử lý đơn, vận chuyển, kiểm tra và gián đoạn sản xuất.', 'Điểm đặt hàng lại cần xét nhu cầu trong thời gian giao hàng và tồn kho an toàn.'],
    formula: 'EOQ = căn bậc hai của (2 × nhu cầu năm × chi phí đặt hàng / chi phí giữ một đơn vị/năm).',
    example: 'Nhu cầu và chi phí thực tế biến động theo mùa, nên EOQ tính được không nên dùng mù quáng. Nếu nhà cung cấp giao chậm hơn dự kiến, điểm đặt hàng lại và tồn kho an toàn mới là phần quyết định không đứt hàng.',
    work: 'đặt câu hỏi về tiền bị giam trong kho mà vẫn bảo vệ mức phục vụ khách hàng',
    warning: 'giảm tồn kho để cải thiện tỷ số ngắn hạn nhưng gây hết hàng, mất doanh thu hoặc chi phí giao gấp cao',
    exercise: 'Liệt kê bốn chi phí giữ tồn kho của một cửa hàng mỹ phẩm và một rủi ro khi đặt hàng quá ít.',
    terms: ['EOQ', 'Tồn kho an toàn', 'Điểm đặt hàng lại', 'Chi phí giữ hàng', 'Vòng quay tồn kho'], link: '/corporate-finance#working-capital-lab',
  },
  {
    id: 'tin-dung-thuong-mai-va-thu-no', order: 49, title: 'Tín dụng thương mại, bán chịu và thu nợ',
    chapter: 'Chương 16 · Quản lý tiền, tồn kho và tín dụng thương mại', level: 'Ứng dụng', minutes: 34,
    summary: 'Thiết kế chính sách bán chịu cân bằng tăng doanh thu với rủi ro tín dụng, chi phí vốn và quan hệ khách hàng.',
    concept: 'Bán chịu là một khoản đầu tư vào khoản phải thu. Chính sách tín dụng cần xác định ai được mua chịu, hạn mức, kỳ hạn, chiết khấu thanh toán sớm, cách theo dõi tuổi nợ và quy trình thu hồi khi quá hạn.',
    points: ['Điều khoản 2/10, net 30 nghĩa là giảm 2% nếu trả trong 10 ngày, còn không thì toàn bộ đến hạn 30 ngày.', 'Phân tích tín dụng xem năng lực, lịch sử thanh toán, tài sản đảm bảo và tập trung rủi ro khách hàng.', 'Thu nợ hiệu quả bắt đầu từ hóa đơn chính xác và đối soát sớm, không chờ đến khi nợ quá hạn lâu.'],
    formula: 'Khoản phải thu bình quân xấp xỉ doanh thu tín dụng/ngày × DSO; chi phí vốn của bán chịu tăng khi DSO tăng.',
    example: 'Doanh thu tín dụng 30 triệu/ngày, DSO tăng từ 35 lên 50 ngày làm phải thu bình quân tăng khoảng 450 triệu. Lợi ích thêm doanh thu phải so với chi phí vốn và rủi ro nợ xấu của 450 triệu này.',
    work: 'đề xuất điều khoản tín dụng, theo dõi tuổi nợ và phối hợp sales thu tiền đúng hạn',
    warning: 'mở rộng bán chịu chỉ để đạt doanh thu hoặc dùng chiết khấu sớm mà không tính chi phí thật của ưu đãi',
    exercise: 'Viết ba tiêu chí phê duyệt hạn mức tín dụng cho khách hàng mới và một hành động khi nợ quá hạn 45 ngày.',
    terms: ['Tín dụng thương mại', 'Khoản phải thu', 'DSO', 'Tuổi nợ', 'Chiết khấu thanh toán'], link: '/corporate-finance#working-capital-lab',
  },
]

export const CORPORATE_FINANCE_ADVANCED_LESSONS = TOPICS.map(buildLesson)

export const CORPORATE_FINANCE_ADVANCED_PRACTICES = Object.fromEntries(
  CORPORATE_FINANCE_ADVANCED_LESSONS.map((item) => [item.id, item.practice]),
)

export const CORPORATE_FINANCE_ADVANCED_SOURCES = ACADEMIC_SOURCES
