// Bài thực hành gốc cho từng lesson. Đây là đầu ra ngắn theo kiểu analyst,
// không phải câu hỏi chọn đáp án.
const field = (id, label, placeholder, help) => ({ id, label, placeholder, help, required: true })

export const LESSON_PRACTICES = {
  'co-phieu-la-gi': {
    title: 'Nhật ký sở hữu doanh nghiệp',
    minutes: 12,
    objective: 'Biến khái niệm "mua cổ phiếu" thành một lý do sở hữu có thể kiểm tra.',
    scenario: 'Bạn được giao theo dõi một doanh nghiệp quen thuộc trong 30 ngày. Trước khi nhìn giá, hãy giải thích doanh nghiệp đó thực sự bán gì và điều gì có thể làm lợi nhuận thay đổi.',
    steps: [
      'Chọn một doanh nghiệp có sản phẩm hoặc dịch vụ bạn hiểu.',
      'Viết bằng lời của bạn doanh nghiệp kiếm tiền từ khách hàng nào và bán thứ gì.',
      'Nêu một yếu tố có thể làm lợi nhuận tốt hơn và một yếu tố có thể làm lợi nhuận xấu đi.',
    ],
    fields: [
      field('business', 'Doanh nghiệp nào và kiếm tiền bằng cách nào?', 'Ví dụ: FPT bán dịch vụ CNTT cho doanh nghiệp; doanh thu đến từ ...', 'Không ghi giá cổ phiếu ở đây. Hãy mô tả khách hàng, sản phẩm và cách thu tiền.'),
      field('owner_view', 'Nếu là chủ sở hữu nhỏ, bạn kỳ vọng nhận được gì?', 'Ví dụ: phần lợi nhuận được tái đầu tư, cổ tức hoặc giá trị doanh nghiệp tăng ...', 'Tách kỳ vọng về doanh nghiệp khỏi biến động giá từng ngày.'),
      field('risk', 'Một rủi ro kinh doanh cần theo dõi', 'Ví dụ: khách hàng lớn giảm chi tiêu, cạnh tranh làm biên lợi nhuận giảm ...', 'Rủi ro phải là điều có thể làm dòng tiền hoặc lợi nhuận thay đổi.'),
    ],
    rubric: ['Nêu đúng sản phẩm/khách hàng thay vì chỉ nêu mã cổ phiếu.', 'Kỳ vọng gắn với lợi nhuận hoặc dòng tiền, không chỉ "giá sẽ tăng".', 'Rủi ro cụ thể và có thể quan sát.'],
    modelAnswer: 'Một bài làm tốt mô tả mô hình kinh doanh trước, sau đó mới nêu giả thuyết. Ví dụ: "Doanh thu phần mềm xuất khẩu phụ thuộc nhu cầu chuyển đổi số của khách hàng và số nhân sự billable; rủi ro là khách hàng hoãn dự án làm công suất giảm."',
    link: '/stock/FPT',
  },
  'thi-truong-va-bang-gia': {
    title: 'Bản tin thị trường 5 dòng',
    minutes: 10,
    objective: 'Tập quan sát bối cảnh trước khi kết luận một mã tăng hoặc giảm là cơ hội.',
    scenario: 'Bạn là intern phải gửi ghi chú buổi sáng cho quản lý. Không cần dự báo giá, chỉ cần mô tả điều đang xảy ra.',
    steps: ['Mở Tổng quan và chọn một chỉ số thị trường.', 'Chọn một mã tăng/giảm đáng chú ý.', 'Phân biệt dữ kiện đang thấy với suy đoán về nguyên nhân.'],
    fields: [
      field('facts', 'Ba dữ kiện quan sát được', 'Ví dụ: VN-Index giảm ..., mã X giảm ..., khối lượng ...', 'Dùng số hoặc hướng biến động; chưa giải thích nguyên nhân.'),
      field('context', 'Bối cảnh thận trọng', 'Ví dụ: một phiên giảm chưa đủ cho thấy xu hướng; cần xem ...', 'Nêu điều bạn chưa biết và cần kiểm tra thêm.'),
      field('next_action', 'Hành động tiếp theo của analyst', 'Ví dụ: mở biểu đồ 6 tháng, đọc tin doanh nghiệp, chưa giao dịch ...', 'Hành động phải là bước nghiên cứu, không phải khẩu lệnh mua/bán.'),
    ],
    rubric: ['Dữ kiện và suy đoán được tách riêng.', 'Không kết luận từ một con số trong một phiên.', 'Có bước kiểm tra kế tiếp rõ ràng.'],
    modelAnswer: 'Một bản tin tốt có cấu trúc: "Điều đã biết → điều chưa biết → việc sẽ làm". Nó không dùng màu xanh/đỏ để suy ra chất lượng doanh nghiệp.',
    link: '/',
  },
  'doc-hieu-bieu-do-nen': {
    title: 'Ghi chú một cây nến trong bối cảnh',
    minutes: 12,
    objective: 'Mô tả được dữ kiện giá thay vì gắn nhãn mua/bán cho một cây nến đơn lẻ.',
    scenario: 'Một đồng nghiệp gửi ảnh biểu đồ và nói "có nến búa, mua được". Bạn cần trả lời theo cách có kiểm chứng hơn.',
    steps: ['Mở biểu đồ 6 tháng của một mã thanh khoản.', 'Chọn một cây nến nổi bật và mô tả thân, bóng nến, vị trí trong xu hướng.', 'Nêu thêm hai dữ kiện cần có trước khi hành động.'],
    fields: [
      field('observation', 'Cây nến nói gì về phiên đó?', 'Ví dụ: thân giảm dài, bóng dưới ngắn, đóng cửa gần thấp nhất phiên ...', 'Chỉ mô tả quan sát, không suy diễn ngay.'),
      field('context', 'Bối cảnh xu hướng', 'Ví dụ: giá đang dưới MA200 / đang tích lũy sau nhịp tăng ...', 'Một cây nến có ý nghĩa khác nhau ở hỗ trợ, kháng cự hoặc giữa vùng đi ngang.'),
      field('confirmation', 'Hai điều kiện xác nhận cần chờ', 'Ví dụ: khối lượng, phiên kế tiếp, vùng hỗ trợ, kết quả kinh doanh ...', 'Ghi rõ điều kiện có thể kiểm tra trên dữ liệu.'),
    ],
    rubric: ['Dùng ngôn ngữ mô tả giá/khối lượng.', 'Đặt nến vào bối cảnh nhiều phiên.', 'Không biến một mẫu nến thành lời khuyên giao dịch.'],
    modelAnswer: 'Câu trả lời tốt không nói "nến này chắc tăng". Nó nói điều thị trường thể hiện trong phiên và dữ kiện nào sẽ làm giả thuyết mạnh hơn hoặc yếu đi.',
    link: '/stock/AAPL',
  },
  'khoi-luong-xu-huong': {
    title: 'Kiểm tra giả thuyết xu hướng',
    minutes: 12,
    objective: 'Liên kết giá, khối lượng và mức hỗ trợ/kháng cự thành một giả thuyết có điều kiện.',
    scenario: 'Giá một mã vừa vượt đỉnh 3 tháng. Quản lý hỏi: đây là bứt phá đáng tin hay chỉ là nhiễu?',
    steps: ['Chọn một mã và xem biểu đồ 6 tháng.', 'Đánh dấu vùng giá bị kiểm tra nhiều lần.', 'So sánh khối lượng phiên biến động với các phiên gần đó.'],
    fields: [
      field('levels', 'Vùng hỗ trợ/kháng cự bạn thấy', 'Ví dụ: vùng 150-155 đã bị từ chối ba lần ...', 'Dùng vùng giá thay vì một số tuyệt đối quá chính xác.'),
      field('volume', 'Khối lượng củng cố hay làm yếu giả thuyết?', 'Ví dụ: phiên vượt vùng có khối lượng cao hơn trung bình / không có xác nhận ...', 'Giải thích vì sao khối lượng liên quan đến độ tin cậy.'),
      field('invalidation', 'Điều gì khiến bạn bỏ giả thuyết?', 'Ví dụ: giá đóng cửa quay lại dưới vùng ... trong khi khối lượng tăng ...', 'Viết điều kiện sai trước khi theo dõi tiếp.'),
    ],
    rubric: ['Có vùng giá, không chỉ nói "cao" hoặc "thấp".', 'So sánh khối lượng với bối cảnh.', 'Có điều kiện bác bỏ rõ ràng.'],
    modelAnswer: 'Bứt phá chỉ là giả thuyết. Một bài làm tốt nêu vùng cần giữ, tín hiệu khối lượng và mức nào khiến bạn dừng theo dõi ý tưởng đó.',
    link: '/stock/MSFT',
  },
  'duong-trung-binh-ma': {
    title: 'Bản đồ xu hướng bằng MA',
    minutes: 10,
    objective: 'Dùng MA để mô tả xu hướng và rủi ro, không dùng giao cắt như nút bấm tự động.',
    scenario: 'Bạn nhận bảng có MA20, MA50 và MA200 của một mã. Hãy viết một ghi chú ngắn cho người không biết kỹ thuật.',
    steps: ['Bật MA20, MA50, MA200 trên một biểu đồ 1 năm.', 'Xác định vị trí giá so với MA200.', 'Nhìn quan hệ MA20 và MA50 rồi nêu giới hạn của kết luận.'],
    fields: [
      field('trend', 'Xu hướng đang thuận hay nghịch theo MA?', 'Ví dụ: giá và MA20 nằm trên MA50, nhưng vẫn cần kiểm tra ...', 'Không cần kết luận mua/bán.'),
      field('risk_level', 'Mức giá hoặc MA nào là mốc rủi ro?', 'Ví dụ: nếu giá đóng cửa dưới MA50 và không hồi lại ...', 'Mốc cần liên quan đến kế hoạch theo dõi.'),
      field('limitation', 'Một giới hạn của MA trong tình huống này', 'Ví dụ: MA phản ứng trễ, thị trường đi ngang tạo nhiều tín hiệu giả ...', 'Nêu vì sao cần kết hợp dữ kiện khác.'),
    ],
    rubric: ['Phân biệt xu hướng với dự báo.', 'Có mốc theo dõi cụ thể.', 'Nêu đúng giới hạn trễ của MA.'],
    modelAnswer: 'MA là công cụ làm mượt dữ liệu quá khứ. Bài làm tốt dùng nó để đặt câu hỏi về xu hướng, không coi nó là lời hứa về phiên tiếp theo.',
    link: '/stock/NVDA',
  },
  'rsi-dong-luong': {
    title: 'Ghi chú động lượng RSI',
    minutes: 10,
    objective: 'Giải thích RSI như chỉ báo động lượng và tránh nhầm quá mua/quá bán với tín hiệu đảo chiều chắc chắn.',
    scenario: 'RSI của một mã ở 74. Bạn cần viết câu trả lời thận trọng cho câu hỏi "có phải bán ngay không?".',
    steps: ['Mở biểu đồ, bật RSI và quan sát giá cùng RSI.', 'Ghi mức RSI, xu hướng giá và vùng hỗ trợ/kháng cự gần nhất.', 'Viết điều kiện bạn sẽ theo dõi tiếp.'],
    fields: [
      field('reading', 'Đọc RSI trong đúng ngữ cảnh', 'Ví dụ: RSI 74 cho thấy động lượng tăng mạnh; không tự nó chứng minh giá sẽ giảm ...', 'Dùng từ "cho thấy" thay vì "chắc chắn".'),
      field('cross_check', 'Hai dữ kiện cần đối chiếu', 'Ví dụ: cấu trúc giá, khối lượng, MA50, kết quả kinh doanh ...', 'Chọn dữ kiện có thể kiểm tra.'),
      field('plan', 'Kế hoạch quan sát thay vì phản ứng cảm xúc', 'Ví dụ: theo dõi phân kỳ hoặc giá phá hỗ trợ ...', 'Nêu việc sẽ làm nếu tín hiệu xấu đi.'),
    ],
    rubric: ['Không đồng nhất RSI cao với bán.', 'Có đối chiếu bằng giá hoặc khối lượng.', 'Viết kế hoạch thay vì dự đoán chắc chắn.'],
    modelAnswer: 'RSI cao nói về tốc độ biến động gần đây. Trong xu hướng mạnh RSI có thể ở vùng cao lâu; vì vậy phải xem giá, khối lượng và khung thời gian.',
    link: '/stock/TSLA',
  },
  'macd-hoi-tu-phan-ky': {
    title: 'Nhật ký tín hiệu MACD',
    minutes: 10,
    objective: 'Mô tả chuyển biến động lượng và biết khi nào tín hiệu MACD dễ nhiễu.',
    scenario: 'MACD vừa cắt lên đường tín hiệu, nhưng giá vẫn đi ngang. Bạn cần ghi nhận điều gì trước khi gọi đó là tín hiệu tăng?',
    steps: ['Bật MACD trên biểu đồ 6 tháng.', 'Ghi vị trí MACD so với đường tín hiệu và mốc 0.', 'So sánh với cấu trúc giá và khối lượng.'],
    fields: [
      field('signal', 'Tín hiệu MACD quan sát được', 'Ví dụ: MACD cắt lên, histogram thu hẹp vùng âm ...', 'Nêu đúng điều biểu đồ hiển thị.'),
      field('price_check', 'Giá đã xác nhận hay chưa?', 'Ví dụ: giá còn dưới kháng cự ..., vì vậy đây mới là dấu hiệu sớm ...', 'MACD không thay thế phân tích giá.'),
      field('noise', 'Khi nào bạn coi tín hiệu này là nhiễu?', 'Ví dụ: thị trường đi ngang hẹp, các lần cắt liên tiếp nhưng không có xu hướng ...', 'Nêu một bối cảnh tín hiệu có thể sai. '),
    ],
    rubric: ['Phân biệt MACD với giá.', 'Có kiểm tra vị trí mốc 0 hoặc cấu trúc giá.', 'Nhận diện được thị trường đi ngang.'],
    modelAnswer: 'MACD hữu ích để quan sát thay đổi động lượng. Trong vùng đi ngang, các giao cắt thường đến muộn hoặc đảo liên tục, nên cần kỷ luật chờ xác nhận.',
    link: '/stock/GOOGL',
  },
  'bollinger-bands': {
    title: 'Báo cáo biến động Bollinger',
    minutes: 10,
    objective: 'Nhìn Bollinger Bands như bối cảnh biến động và xây kịch bản thay vì dự báo hướng bằng một chạm band.',
    scenario: 'Dải Bollinger đang thu hẹp nhiều tuần. Hãy chuẩn bị kế hoạch quan sát cho phiên biến động sắp tới.',
    steps: ['Bật Bollinger Bands trên biểu đồ 6 tháng.', 'Mô tả độ rộng dải và vị trí giá.', 'Viết hai kịch bản tăng/giảm cùng điều kiện xác nhận.'],
    fields: [
      field('volatility', 'Biến động đang nén hay mở rộng?', 'Ví dụ: dải hẹp hơn các tháng trước, giá dao động quanh đường giữa ...', 'Mô tả hiện tượng, chưa kết luận hướng.'),
      field('up_case', 'Kịch bản tăng và điều kiện xác nhận', 'Ví dụ: giá đóng cửa vượt vùng ... cùng khối lượng tăng ...', 'Viết theo dạng nếu-thì.'),
      field('down_case', 'Kịch bản giảm và cách xử lý', 'Ví dụ: giá phá vùng ...; khi đó tôi không đuổi theo lệnh mua ...', 'Có hành động rõ ràng nếu giả thuyết ngược xảy ra.'),
    ],
    rubric: ['Không coi chạm band là lệnh bắt buộc.', 'Có cả hai kịch bản.', 'Điều kiện có thể kiểm tra bằng dữ liệu.'],
    modelAnswer: 'Dải hẹp báo hiệu biến động thấp, không nói hướng. Bài làm mạnh nhất luôn chuẩn bị trước điều kiện cho cả hai hướng.',
    link: '/stock/AMZN',
  },
  'bao-cao-tai-chinh-1-can-doi': {
    title: 'Bản đồ bảng cân đối',
    minutes: 18,
    objective: 'Đọc được nguồn lực, nghĩa vụ và vốn chủ bằng một kiểm tra logic đơn giản.',
    scenario: 'Bạn nhận bảng cân đối của một công ty bán lẻ. Quản lý muốn biết tiền đang bị giữ ở đâu và đòn bẩy có đáng lo không.',
    steps: ['Mở Financials của một mã hoặc dùng số liệu ví dụ trong bài.', 'Ghi tài sản lớn nhất, khoản nợ lớn nhất và vốn chủ.', 'Kiểm tra phương trình tài sản = nợ + vốn chủ.'],
    fields: [
      field('assets', 'Tài sản nào cần giải thích trước?', 'Ví dụ: tồn kho chiếm ...; nếu tăng nhanh hơn doanh thu thì cần hỏi ...', 'Đừng chỉ chép số, hãy nêu câu hỏi kinh doanh.'),
      field('funding', 'Công ty đang dùng nợ hay vốn chủ để tài trợ?', 'Ví dụ: nợ/vốn chủ ...; cần xem lịch trả nợ và lãi vay ...', 'Không kết luận an toàn/nguy hiểm chỉ bằng một tỷ lệ.'),
      field('logic_check', 'Viết kiểm tra phương trình kế toán', 'Ví dụ: tài sản ... = nợ ... + vốn chủ ...; chênh lệch ... do đơn vị làm tròn', 'Ghi đơn vị bạn đang dùng.'),
    ],
    rubric: ['Nêu câu hỏi về chất lượng tài sản.', 'Tách nợ khỏi vốn chủ.', 'Kiểm tra được phương trình kế toán.'],
    modelAnswer: 'Một analyst không dừng ở tổng tài sản. Họ hỏi: tồn kho có bán được không, phải thu có thu được không, nợ đáo hạn khi nào và vốn chủ có đang tăng từ lợi nhuận thật không.',
    link: '/manual/FPT',
  },
  'bao-cao-tai-chinh-2-ket-qua': {
    title: 'Cầu nối doanh thu đến lợi nhuận',
    minutes: 18,
    objective: 'Tách thay đổi lợi nhuận thành doanh thu, giá vốn và chi phí vận hành.',
    scenario: 'Lợi nhuận ròng giảm dù doanh thu tăng. Bạn cần chuẩn bị ba câu hỏi cho cuộc họp tháng.',
    steps: ['Chọn hai kỳ báo cáo liên tiếp.', 'Tính hoặc đọc thay đổi doanh thu, lợi nhuận gộp và lợi nhuận ròng.', 'Viết giả thuyết nguyên nhân cần kiểm chứng.'],
    fields: [
      field('bridge', 'Cầu nối ba dòng chính', 'Ví dụ: doanh thu tăng ..., biên gộp giảm ..., chi phí bán hàng tăng ...', 'Nêu chiều và mức thay đổi nếu có.'),
      field('drivers', 'Ba câu hỏi nguyên nhân', 'Ví dụ: giá bán, sản lượng, mix, chiết khấu, chi phí một lần ...', 'Câu hỏi phải dẫn tới dữ liệu cần lấy.'),
      field('action', 'Việc cần làm tiếp theo', 'Ví dụ: tách doanh thu theo sản phẩm, so margin theo quý, kiểm tra chi phí ...', 'Không ghi "theo dõi thêm" chung chung.'),
    ],
    rubric: ['Không nhầm doanh thu với lợi nhuận.', 'Có cầu nối từ doanh thu đến biên/lợi nhuận.', 'Câu hỏi nguyên nhân có thể kiểm tra.'],
    modelAnswer: 'Doanh thu tăng không đảm bảo lợi nhuận tăng. Hãy bắt đầu bằng giá, sản lượng, cơ cấu và chi phí; sau đó tìm dòng báo cáo hoặc dữ liệu vận hành để kiểm chứng.',
    link: '/corporate-finance#labs',
  },
  'bao-cao-tai-chinh-3-luu-chuyen-tien': {
    title: 'Kiểm tra chất lượng lợi nhuận',
    minutes: 18,
    objective: 'So sánh lợi nhuận với dòng tiền kinh doanh và nhận diện câu hỏi về vốn lưu động.',
    scenario: 'Công ty báo lãi cao nhưng tiền từ hoạt động kinh doanh thấp. Bạn được yêu cầu chuẩn bị ghi chú rủi ro 1 đoạn.',
    steps: ['Lấy lợi nhuận ròng và CFO/OCF cùng kỳ.', 'So sánh hướng thay đổi của phải thu, tồn kho hoặc phải trả nếu có.', 'Viết câu hỏi ưu tiên cho kỳ báo cáo tiếp theo.'],
    fields: [
      field('comparison', 'So sánh lợi nhuận và dòng tiền', 'Ví dụ: OCF thấp hơn lợi nhuận; tỷ lệ OCF/LN là ...', 'Ghi rõ cùng một kỳ và cùng đơn vị.'),
      field('working_capital', 'Giả thuyết về vốn lưu động', 'Ví dụ: phải thu/tồn kho tăng có thể làm tiền bị giữ lại ...', 'Đây là giả thuyết, cần kiểm tra thuyết minh.'),
      field('question', 'Câu hỏi cho ban điều hành', 'Ví dụ: khoản phải thu tăng đến từ khách hàng nào, thời hạn thu tiền bao lâu?', 'Viết câu hỏi cụ thể có người trả lời được.'),
    ],
    rubric: ['So sánh cùng kỳ.', 'Không coi OCF thấp một kỳ là gian lận.', 'Nêu đúng vai trò của vốn lưu động.'],
    modelAnswer: 'Dòng tiền không phải bản sao của lợi nhuận. Chênh lệch có thể do tăng trưởng bình thường, đầu tư tồn kho hoặc vấn đề thu tiền; analyst phải tìm nguyên nhân thay vì gắn nhãn vội.',
    link: '/corporate-finance#working-capital-lab',
  },
  'chi-so-dinh-gia': {
    title: 'Phiếu định giá có giả định',
    minutes: 20,
    objective: 'Dùng P/E, P/B, ROE như câu hỏi về kỳ vọng chứ không phải nhãn rẻ/đắt.',
    scenario: 'Hai công ty cùng ngành có P/E khác nhau nhiều. Bạn cần giải thích ba khả năng trước khi kết luận.',
    steps: ['Chọn hai công ty cùng ngành hoặc cùng mô hình kinh doanh.', 'Ghi P/E, ROE, tăng trưởng/lợi nhuận và nợ nếu có.', 'Viết ba lý do hợp lý khiến bội số khác nhau.'],
    fields: [
      field('comparison', 'Bảng so sánh tối thiểu', 'Ví dụ: A P/E ..., ROE ...; B P/E ..., ROE ...', 'So sánh đúng ngành, cùng đơn vị và thời điểm.'),
      field('hypotheses', 'Ba giả thuyết cho chênh lệch', 'Ví dụ: tăng trưởng, rủi ro nợ, biên lợi nhuận, chất lượng dòng tiền ...', 'Không chọn một đáp án duy nhất khi chưa kiểm chứng.'),
      field('evidence', 'Dữ liệu cần thêm để kết luận', 'Ví dụ: forecast EPS, lịch sử biên, đối thủ, lưu chuyển tiền ...', 'Liệt kê nguồn hoặc báo cáo cần xem.'),
    ],
    rubric: ['So sánh cùng nhóm hợp lý.', 'Nêu giả thuyết thay vì chỉ nói P/E thấp là rẻ.', 'Có bằng chứng cần thu thập tiếp.'],
    modelAnswer: 'Bội số phản ánh cả tăng trưởng, rủi ro và chất lượng lợi nhuận. P/E thấp có thể là cơ hội, hoặc là thị trường đang kỳ vọng lợi nhuận giảm; công việc là tìm bằng chứng phân biệt hai khả năng.',
    link: '/compare',
  },
  'quy-trinh-ra-quyet-dinh': {
    title: 'Memo quyết định một trang',
    minutes: 25,
    objective: 'Tổng hợp phân tích thành quyết định có luận điểm, điều kiện sai và kế hoạch theo dõi.',
    scenario: 'Bạn phải trình bày một ý tưởng cho quản lý. Bài làm được đánh giá ở sự rõ ràng của giả định, không ở việc đoán đúng giá ngày mai.',
    steps: ['Chọn một mã bạn đã đọc báo cáo hoặc dữ liệu cơ bản.', 'Viết luận điểm, bằng chứng, mức giá/điều kiện hấp dẫn và điều kiện sai.', 'Nêu tỷ trọng giả lập phù hợp với rủi ro.'],
    fields: [
      field('thesis', 'Luận điểm 3 câu', 'Ví dụ: doanh thu ..., biên ..., lý do thị trường có thể đang đánh giá chưa đúng ...', 'Mỗi câu phải có một dữ kiện hoặc giả định.'),
      field('invalidation', 'Tôi sẽ sai nếu...', 'Ví dụ: khách hàng lớn giảm chi tiêu, biên gộp xuống dưới ..., nợ không được tái cấp ...', 'Điều kiện sai cần quan sát được.'),
      field('plan', 'Kế hoạch rủi ro và theo dõi', 'Ví dụ: tỷ trọng giả lập ..., xem lại khi có báo cáo quý hoặc giá phá vùng ...', 'Không dùng tiền thật trong bài tập.'),
    ],
    rubric: ['Có luận điểm và bằng chứng.', 'Điều kiện sai cụ thể.', 'Kế hoạch rủi ro trước khi hành động.'],
    modelAnswer: 'Memo tốt nhất ngắn nhưng kiểm chứng được: điều gì đang đúng, dữ liệu nào chứng minh, điều gì bác bỏ và bạn sẽ làm gì khi điều đó xảy ra.',
    link: '/research',
  },
  'quan-tri-rui-ro': {
    title: 'Phiếu cỡ vị thế và danh mục',
    minutes: 20,
    objective: 'Tính rủi ro theo khoảng cách đến mức dừng, sau đó kiểm tra rủi ro tập trung.',
    scenario: 'Bạn có danh mục giả lập 100 triệu đồng và muốn mua một mã ở 50.000 đồng với mức dừng 46.000 đồng. Quy tắc rủi ro là 1% danh mục mỗi ý tưởng.',
    steps: ['Tính số tiền rủi ro cho phép.', 'Tính rủi ro trên một cổ phiếu và số lượng tối đa.', 'Kiểm tra mã này có làm danh mục tập trung cùng ngành hay không.'],
    fields: [
      field('calculation', 'Tính cỡ vị thế', 'Viết: 1% × 100 triệu = ...; rủi ro/cp = ...; số cp tối đa = ...', 'Chỉ cần trình bày phép tính, không cần mua thật.'),
      field('concentration', 'Kiểm tra tập trung', 'Ví dụ: danh mục đã có ... mã cùng ngành; thêm mã này làm rủi ro ...', 'Đa dạng hóa là theo nguồn rủi ro, không chỉ theo số mã.'),
      field('rule', 'Một quy tắc bạn cam kết giữ', 'Ví dụ: không tăng số lượng chỉ vì giá giảm; không mã nào vượt ...', 'Quy tắc phải đo được.'),
    ],
    rubric: ['Tách giá trị vị thế khỏi số tiền rủi ro.', 'Có kiểm tra tập trung.', 'Quy tắc rõ và đo được.'],
    modelAnswer: 'Với ví dụ, rủi ro cho phép là 1 triệu; rủi ro/cp là 4.000; số lượng tối đa là 250 cp. Đây là giới hạn rủi ro, không phải khuyến nghị mua.',
    link: '/trading',
  },
  'tam-ly-dau-tu': {
    title: 'Bản cam kết quyết định có kỷ luật',
    minutes: 15,
    objective: 'Thiết kế "phanh" cho các lỗi hành vi trước khi cảm xúc xuất hiện.',
    scenario: 'Bạn vừa có ba lệnh giả lập thắng liên tiếp và muốn tăng mạnh quy mô lệnh tiếp theo. Hãy viết quy tắc để bảo vệ quy trình.',
    steps: ['Chọn một lỗi hành vi bạn dễ gặp nhất.', 'Viết tín hiệu cảnh báo sớm.', 'Viết quy tắc hành động bắt buộc và cách kiểm tra sau 10 lệnh.'],
    fields: [
      field('bias', 'Lỗi hành vi và tín hiệu cảnh báo', 'Ví dụ: FOMO khi thấy mã tăng mạnh và tôi đọc tin liên tục ...', 'Mô tả hành vi của bạn, không phán xét bản thân.'),
      field('brake', 'Phanh an toàn bằng quy tắc', 'Ví dụ: chờ 24 giờ, viết luận điểm và điều kiện sai trước mọi lệnh ...', 'Quy tắc phải thực hiện được khi thị trường biến động.'),
      field('review', 'Cách tự kiểm sau 10 lệnh', 'Ví dụ: phân loại lệnh đúng quy trình/lệch quy trình và so kết quả ...', 'Đánh giá chất lượng quy trình trước lợi nhuận.'),
    ],
    rubric: ['Gọi tên được hành vi cụ thể.', 'Có phanh an toàn trước hành động.', 'Có nhịp xem lại dữ liệu cá nhân.'],
    modelAnswer: 'Kỷ luật không phải ý chí trong một khoảnh khắc. Nó là thiết kế quy tắc trước, ghi lại sau và sửa bằng bằng chứng từ chính hành vi của bạn.',
    link: '/trading',
  },
}
