export const CORPORATE_FINANCE_SOURCES = [
  {
    id: 'mit-15401',
    institution: 'MIT OpenCourseWare',
    title: '15.401 Finance Theory I',
    url: 'https://ocw.mit.edu/courses/15-401-finance-theory-i-fall-2008/',
    relevance: 'Khung nền tảng về định giá, đầu tư vốn, chứng khoán nợ - vốn chủ và đa dạng hóa.',
    lastVerified: '2026-08-17',
  },
  {
    id: 'mit-15402',
    institution: 'MIT OpenCourseWare',
    title: '15.402 Finance Theory II',
    url: 'https://ocw.mit.edu/courses/15-402-finance-theory-ii-spring-2003/',
    relevance: 'Khung thực hành corporate finance: tài trợ, dòng tiền tự do, WACC, APV, định giá, đầu tư vốn và case.',
    lastVerified: '2026-08-17',
  },
  {
    id: 'nyu-damodaran',
    institution: 'NYU Stern',
    title: 'Corporate Finance - Aswath Damodaran',
    url: 'https://pages.stern.nyu.edu/~adamodar/New_Home_Page/corpfin.html',
    relevance: 'Cấu trúc học theo buổi, bài tập, bảng tính và dữ liệu cho các quyết định đầu tư, tài trợ và cổ tức.',
    lastVerified: '2026-08-17',
  },
]

export const CORPORATE_FINANCE_MODULES = [
  {
    id: 'orientation-business-model',
    order: '01',
    label: 'Khởi đầu',
    minutes: '50 phút',
    title: 'Tài chính doanh nghiệp bắt đầu từ mô hình kinh doanh',
    outcome: 'Bạn mô tả được doanh nghiệp kiếm tiền bằng cách nào, đâu là động lực vận hành và vì sao finance cần hiểu hoạt động trước khi mở Excel.',
    objective: 'Nhận diện được mô hình tạo giá trị, nguồn doanh thu, cấu trúc chi phí và các động lực vận hành cốt lõi.',
    prerequisite: 'Không cần kiến thức trước. Chuẩn bị một doanh nghiệp quen thuộc: quán cà phê, cửa hàng online, nhà máy nhỏ hoặc phần mềm thuê bao.',
    question: 'Công ty bán giá trị gì, thu tiền từ ai, và mỗi lần tăng doanh thu thì điều gì thay đổi trong chi phí, tiền mặt và rủi ro?',
    explain: 'Tài chính doanh nghiệp là cách biến câu chuyện vận hành thành quyết định dùng tiền. Người làm FP&A hay corporate finance không chỉ tính công thức; họ phải nối khách hàng, sản phẩm, giá, sản lượng, chi phí, công nợ và vốn đầu tư thành một bức tranh có thể hành động.',
    blocks: [
      {
        title: 'Ba câu hỏi nền móng',
        text: 'Doanh nghiệp tạo doanh thu từ đâu? Chi phí nào tăng theo doanh thu và chi phí nào gần như cố định? Tiền thu về trước hay sau khi phải chi? Trả lời ba câu này giúp bạn chọn đúng chỉ số để theo dõi.',
      },
      {
        title: 'Động lực khác chỉ tiêu',
        text: 'Doanh thu là kết quả. Động lực là thứ có thể can thiệp, chẳng hạn số khách, tỷ lệ chuyển đổi, giá trị đơn hàng, công suất máy hoặc số thuê bao trả phí. Forecast tốt đi từ động lực lên kết quả.',
      },
      {
        title: 'Vai trò của finance',
        text: 'Finance kiểm tra tính kinh tế của lựa chọn: tăng trưởng có tạo tiền không, nguồn lực có đủ không, dự án nào đáng ưu tiên và rủi ro nào cần báo sớm cho quản lý.',
      },
    ],
    formula: {
      label: 'Khung doanh thu cơ bản',
      expression: 'Doanh thu = Số khách hoặc số đơn x Giá bán bình quân',
      explanation: 'Tùy mô hình, thay số khách bằng lượt giao dịch, sản lượng, số thuê bao hoặc số hợp đồng. Sau đó thêm tỷ lệ hoàn trả, chiết khấu và cơ cấu sản phẩm khi cần.',
    },
    workedExample: {
      context: 'Một cửa hàng bán 2.000 đơn trong tháng, giá trị đơn bình quân 350.000 đồng và tỷ lệ hoàn trả 4%.',
      calculation: 'Doanh thu gộp = 2.000 x 350.000 = 700 triệu đồng. Doanh thu sau hoàn trả xấp xỉ 700 x (1 - 4%) = 672 triệu đồng.',
      conclusion: 'Nếu doanh thu giảm, đừng mặc định do giá. Hãy kiểm tra số đơn, giá trị đơn, chiết khấu và hoàn trả trước.',
    },
    pitfall: 'Dùng một chỉ số tổng như doanh thu để giải thích mọi việc. Doanh thu có thể tăng vì giảm giá sâu, nhưng lợi nhuận và tiền mặt lại xấu đi.',
    jobOutput: 'Một trang “business map” có khách hàng, sản phẩm, nguồn doanh thu, ba chi phí lớn, điều khoản thu tiền và ba KPI vận hành.',
    practice: {
      case: 'Chọn một doanh nghiệp gần gũi. Hãy giả định bạn là intern được yêu cầu giải thích trong 5 phút công ty tạo tiền như thế nào.',
      steps: [
        'Viết một câu mô tả khách hàng, sản phẩm và lý do khách trả tiền.',
        'Vẽ chuỗi: đầu vào -> hoạt động -> giao hàng -> hóa đơn -> thu tiền.',
        'Chọn ba động lực doanh thu và ba động lực chi phí có thể đo mỗi tuần hoặc mỗi tháng.',
        'Nêu một rủi ro khiến doanh thu tăng nhưng tiền mặt có thể giảm.',
      ],
      checklist: [
        'Có phân biệt doanh thu, lợi nhuận và tiền mặt.',
        'KPI là nguyên nhân vận hành, không chỉ là số tài chính cuối cùng.',
        'Mỗi giả định đều có đơn vị đo và kỳ theo dõi.',
      ],
    },
    sources: ['mit-15402', 'nyu-damodaran'],
    lastVerified: '2026-08-17',
  },
  {
    id: 'accounting-three-statements',
    order: '02',
    label: 'Báo cáo',
    minutes: '70 phút',
    title: 'Đọc ba báo cáo tài chính như một câu chuyện duy nhất',
    outcome: 'Bạn hiểu P&L, bảng cân đối kế toán và lưu chuyển tiền tệ nói gì, đồng thời lần được một giao dịch đơn giản qua cả ba báo cáo.',
    objective: 'Liên kết được lợi nhuận, tài sản - nguồn vốn và tiền mặt trong các giao dịch kinh doanh cơ bản.',
    prerequisite: 'Hoàn thành mô-đun 01 hoặc biết doanh thu, chi phí và tiền mặt khác nhau.',
    question: 'Một công ty báo lãi nhưng tiền mặt giảm: điều này có thể xảy ra ở những dòng nào?',
    explain: 'Ba báo cáo không cạnh tranh nhau. P&L ghi kết quả trong một kỳ, bảng cân đối là ảnh chụp tài sản và nguồn hình thành tài sản tại một thời điểm, còn báo cáo lưu chuyển tiền tệ cho biết tiền thật vào ra. Người mới đi làm cần nhìn được mối nối thay vì học thuộc định nghĩa rời rạc.',
    blocks: [
      {
        title: 'P&L: hiệu quả trong kỳ',
        text: 'Bắt đầu từ doanh thu, trừ giá vốn và chi phí vận hành để ra lợi nhuận. P&L dùng nguyên tắc dồn tích nên thời điểm ghi nhận không luôn trùng thời điểm thu hoặc chi tiền.',
      },
      {
        title: 'Bảng cân đối: nguồn lực và nghĩa vụ',
        text: 'Tài sản gồm tiền, phải thu, tồn kho, máy móc. Nợ phải trả gồm vay, phải trả nhà cung cấp. Phần còn lại là vốn chủ sở hữu. Bảng này phải cân bằng theo phương trình kế toán.',
      },
      {
        title: 'Lưu chuyển tiền tệ: tiền từ đâu đến',
        text: 'Dòng tiền hoạt động phản ánh kinh doanh và vốn lưu động; dòng tiền đầu tư phản ánh mua bán tài sản dài hạn; dòng tiền tài trợ phản ánh vay, trả nợ, góp vốn hoặc trả cổ tức.',
      },
    ],
    formula: {
      label: 'Phương trình kế toán',
      expression: 'Tài sản = Nợ phải trả + Vốn chủ sở hữu',
      explanation: 'Mọi bút toán hợp lệ đều giữ phương trình cân bằng. Đây là phép kiểm tra logic đầu tiên khi xây model hoặc nhập dữ liệu.',
    },
    workedExample: {
      context: 'Công ty bán chịu hàng trị giá 100 triệu đồng, giá vốn 60 triệu đồng. Khách chưa thanh toán.',
      calculation: 'P&L ghi doanh thu 100 và giá vốn 60, nên lợi nhuận gộp tăng 40. Bảng cân đối tăng phải thu 100 và giảm tồn kho 60; vốn chủ tăng 40 qua lợi nhuận. Dòng tiền hoạt động chưa tăng 100 vì tiền đang nằm ở phải thu.',
      conclusion: 'Lợi nhuận gộp không đồng nghĩa tiền đã về. Khoản phải thu phải được theo dõi cùng doanh thu.',
    },
    pitfall: 'Cộng tiền vay vào doanh thu hoặc xem toàn bộ tiền mua máy là chi phí ngay trên P&L. Cần phân biệt hoạt động kinh doanh, đầu tư và tài trợ.',
    jobOutput: 'Một bảng nối ba báo cáo cho năm giao dịch: bán tiền mặt, bán chịu, mua tồn kho, mua máy và vay ngân hàng.',
    practice: {
      case: 'Bạn nhận một file có P&L lãi 80 triệu đồng nhưng tiền cuối kỳ giảm 50 triệu đồng. Hãy tìm ít nhất hai lời giải thích có thể xảy ra.',
      steps: [
        'Tạo ba cột P&L, bảng cân đối và lưu chuyển tiền tệ.',
        'Ghi tác động dấu cộng hoặc trừ của năm giao dịch nêu trên.',
        'Kiểm tra tổng tài sản có bằng nợ phải trả cộng vốn chủ sau từng giao dịch.',
        'Viết hai câu giải thích chênh lệch giữa lợi nhuận và tiền mặt.',
      ],
      checklist: [
        'Không nhầm doanh thu với tiền thu khách hàng.',
        'Bảng cân đối luôn cân bằng.',
        'Có chỉ ra khoản phải thu, tồn kho hoặc CAPEX khi giải thích dòng tiền.',
      ],
    },
    sources: ['mit-15401', 'mit-15402'],
    lastVerified: '2026-08-17',
  },
  {
    id: 'pnl-unit-economics',
    order: '03',
    label: 'Lợi nhuận',
    minutes: '65 phút',
    title: 'P&L, biên lợi nhuận và unit economics',
    outcome: 'Bạn dựng được P&L đơn giản, tách được chi phí biến đổi và cố định, rồi giải thích liệu mỗi đơn hàng hay mỗi khách mới có tạo giá trị không.',
    objective: 'Phân tích được biên lợi nhuận, phần đóng góp và điểm hòa vốn để đánh giá chất lượng tăng trưởng.',
    prerequisite: 'Biết cấu trúc cơ bản của P&L ở mô-đun 02.',
    question: 'Tăng doanh thu có chắc làm lợi nhuận tăng không, và bao nhiêu doanh thu thì doanh nghiệp hòa vốn?',
    explain: 'P&L là nơi finance nhìn chất lượng tăng trưởng. Một doanh nghiệp có thể có doanh thu lớn nhưng biên gộp thấp, chi phí thu hút khách cao hoặc chi phí cố định quá nặng. Unit economics thu nhỏ vấn đề về một đơn hàng, một khách hoặc một sản phẩm để thấy đòn bẩy thật.',
    blocks: [
      {
        title: 'Giá vốn và biên gộp',
        text: 'Giá vốn là chi phí trực tiếp để tạo hoặc mua hàng bán ra. Biên gộp cho biết sau giá vốn, mỗi đồng doanh thu còn bao nhiêu để trang trải vận hành và tạo lợi nhuận.',
      },
      {
        title: 'Chi phí biến đổi và cố định',
        text: 'Chi phí biến đổi thay đổi cùng sản lượng như bao bì, hoa hồng. Chi phí cố định ngắn hạn ít đổi theo số đơn như lương đội ngũ, thuê mặt bằng. Phân loại đúng giúp tính điểm hòa vốn.',
      },
      {
        title: 'Đóng góp trên mỗi đơn',
        text: 'Contribution margin không phải lợi nhuận cuối cùng. Nó cho biết mỗi đơn đóng góp bao nhiêu để bù chi phí cố định, từ đó giúp quyết định tăng sản lượng, đổi giá hay cắt chi phí.',
      },
    ],
    formula: {
      label: 'Điểm hòa vốn theo sản lượng',
      expression: 'Sản lượng hòa vốn = Chi phí cố định / (Giá bán đơn vị - Chi phí biến đổi đơn vị)',
      explanation: 'Mẫu số là phần đóng góp của một đơn vị. Nếu phần này bằng hoặc nhỏ hơn 0, tăng bán không thể bù chi phí cố định.',
    },
    workedExample: {
      context: 'Một ly đồ uống bán 50.000 đồng, nguyên liệu và bao bì 22.000 đồng; chi phí cố định tháng là 84 triệu đồng.',
      calculation: 'Đóng góp mỗi ly = 50.000 - 22.000 = 28.000 đồng. Điểm hòa vốn = 84.000.000 / 28.000 = 3.000 ly mỗi tháng.',
      conclusion: 'Muốn giảm điểm hòa vốn, doanh nghiệp có thể tăng giá có kiểm soát, hạ chi phí biến đổi hoặc giảm chi phí cố định; mỗi cách có rủi ro riêng.',
    },
    pitfall: 'Gọi EBITDA, EBIT và lợi nhuận ròng là một. Mỗi chỉ tiêu loại trừ các khoản khác nhau, nên luôn ghi rõ đang dùng cấp lợi nhuận nào.',
    jobOutput: 'Một P&L tháng có doanh thu, giá vốn, chi phí vận hành, các biên lợi nhuận và phần nhận xét ba dòng.',
    practice: {
      case: 'Một cửa hàng online muốn khuyến mãi giảm giá 10%. Bạn cần kiểm tra số đơn phải tăng thêm bao nhiêu để giữ nguyên tổng phần đóng góp.',
      steps: [
        'Đặt giá bán, chi phí biến đổi, số đơn và chi phí cố định ban đầu.',
        'Tính contribution margin hiện tại và tổng đóng góp.',
        'Giảm giá 10%, giữ chi phí biến đổi không đổi, rồi tính số đơn cần bán để bù.',
        'Viết kết luận: khuyến mãi hợp lý khi nào và cần theo dõi KPI nào sau khi chạy.',
      ],
      checklist: [
        'Đơn vị tính nhất quán giữa nghìn, triệu và đồng.',
        'Có tách phần đóng góp khỏi lợi nhuận ròng.',
        'Kết luận nêu cả lợi ích doanh thu và rủi ro biên lợi nhuận.',
      ],
    },
    sources: ['mit-15402', 'nyu-damodaran'],
    lastVerified: '2026-08-17',
  },
  {
    id: 'budget-forecast-drivers',
    order: '04',
    label: 'Kế hoạch',
    minutes: '75 phút',
    title: 'Lập budget và rolling forecast từ business drivers',
    outcome: 'Bạn lập được forecast 12 tháng đơn giản dựa trên giả định minh bạch, biết phân biệt Actual, Budget và Forecast, đồng thời cập nhật forecast khi có dữ liệu mới.',
    objective: 'Xây được mô hình dự báo từ giá, lượng, cơ cấu và các giả định vận hành có chủ sở hữu.',
    prerequisite: 'Hoàn thành mô-đun 01 và 03; biết doanh thu được tạo bởi giá, lượng và cơ cấu.',
    question: 'Nếu doanh thu năm nay đang dưới kế hoạch, cuối năm sẽ ra sao và đội nào cần thay đổi hành động ngay trong tháng này?',
    explain: 'Budget là cam kết hoặc mục tiêu đã phê duyệt tại một thời điểm. Forecast là ước tính tốt nhất hiện tại về điều sẽ xảy ra. Việc forecast khác budget không phải lỗi; che giấu chênh lệch mới là lỗi vì doanh nghiệp mất thời gian để điều chỉnh.',
    blocks: [
      {
        title: 'Base case và giả định',
        text: 'Mỗi dòng forecast phải đi về một giả định có chủ sở hữu: lượng khách, giá, tỷ lệ chuyển đổi, năng suất, tỷ lệ hao hụt, lương, tỷ giá hoặc thời điểm tuyển dụng.',
      },
      {
        title: 'Rolling forecast',
        text: 'Sau mỗi tháng đã có Actual, thay tháng đó bằng số thực tế và cập nhật các tháng còn lại. Cách làm này giúp forecast phản ánh tình hình hơn là bảo vệ con số kế hoạch cũ.',
      },
      {
        title: 'Kịch bản',
        text: 'Ít nhất nên có base, upside và downside. Mỗi kịch bản thay vài giả định có ý nghĩa thay vì nhân toàn bộ P&L với một tỷ lệ tùy ý.',
      },
    ],
    formula: {
      label: 'Cầu nối forecast doanh thu',
      expression: 'Doanh thu forecast = Lượng forecast x Giá forecast x (1 - Tỷ lệ giảm trừ)',
      explanation: 'Khi nhiều sản phẩm, tính từng nhóm rồi cộng lại. Đừng dùng một mức tăng trưởng chung nếu cơ cấu sản phẩm thay đổi đáng kể.',
    },
    workedExample: {
      context: 'Budget tháng 7 là 1.000 đơn x 500.000 đồng. Actual nửa đầu tháng cho thấy tốc độ chỉ đạt 850 đơn nhưng giá bình quân cao hơn 3%.',
      calculation: 'Forecast sơ bộ = 850 x 515.000 = 437,75 triệu đồng, so với budget 500 triệu đồng là thấp hơn 62,25 triệu đồng trước khi xét giảm trừ và mix.',
      conclusion: 'Cần kiểm tra liệu thiếu sản lượng do nhu cầu, tồn kho, nhân sự bán hàng hay dữ liệu cập nhật chậm; giải pháp tùy nguyên nhân.',
    },
    pitfall: 'Lấy Actual năm trước nhân với một tỷ lệ tăng trưởng rồi gọi đó là forecast. Cách này che mất công suất, thay đổi giá, mùa vụ và kế hoạch vận hành.',
    jobOutput: 'Một workbook gồm tab Assumptions, Actual, Budget, Forecast và Executive Summary với các biến chính được ghi nguồn.',
    practice: {
      case: 'Dự báo doanh thu và chi phí cho một cửa hàng trong ba tháng tới khi số khách, giá bán và lịch tuyển dụng đều thay đổi.',
      steps: [
        'Liệt kê giả định theo tháng và ghi ai sở hữu từng giả định.',
        'Tạo forecast doanh thu từ lượng, giá và giảm trừ.',
        'Cho giá vốn biến đổi theo doanh thu và thêm chi phí cố định theo lịch.',
        'Tạo downside bằng cách giảm lượng khách 10% và nêu tác động đến lợi nhuận.',
      ],
      checklist: [
        'Không ghi số cứng trong công thức khi số đó là giả định.',
        'Có dấu thời gian cập nhật forecast.',
        'Có thể giải thích ba biến thay đổi lớn nhất so với budget.',
      ],
    },
    sources: ['mit-15402', 'nyu-damodaran'],
    lastVerified: '2026-08-17',
  },
  {
    id: 'working-capital-cash-cycle',
    order: '05',
    label: 'Vốn lưu động',
    minutes: '65 phút',
    title: 'Vốn lưu động: doanh thu tăng mà tiền vẫn cạn',
    outcome: 'Bạn tính được chu kỳ chuyển đổi tiền mặt, giải thích được biến động tồn kho - phải thu - phải trả và đề xuất hành động có cân nhắc quan hệ vận hành.',
    objective: 'Đánh giá được nhu cầu vốn lưu động và các đòn bẩy cải thiện tiền mặt mà không bỏ qua đánh đổi vận hành.',
    prerequisite: 'Hiểu khoản phải thu, tồn kho và phải trả từ mô-đun 02.',
    question: 'Công ty phải bỏ tiền ra trước bao lâu rồi mới thu được tiền từ khách hàng?',
    explain: 'Vốn lưu động là phần vốn phục vụ hoạt động hằng ngày. Khi bán chịu hoặc phải tích hàng trước mùa cao điểm, lợi nhuận có thể tốt nhưng tiền bị kẹt. Đây là lý do finance phải theo dõi cả P&L và bảng cân đối.',
    blocks: [
      {
        title: 'Khoản phải thu',
        text: 'Bán chịu làm doanh thu ghi nhận trước tiền. DSO tăng có thể do khách trả chậm, chính sách tín dụng lỏng hoặc lỗi xuất hóa đơn và đối soát.',
      },
      {
        title: 'Tồn kho',
        text: 'Tồn kho bảo đảm phục vụ khách hàng nhưng dùng tiền. DIO tăng cần tách nguyên nhân: dự trữ chủ động, dự báo sai, hàng chậm bán hay dữ liệu giá vốn không đúng.',
      },
      {
        title: 'Khoản phải trả',
        text: 'DPO dài hơn có thể cải thiện thanh khoản, nhưng kéo quá mức có thể làm mất chiết khấu, gây đứt nguồn cung hoặc làm xấu quan hệ với nhà cung cấp.',
      },
    ],
    formula: {
      label: 'Chu kỳ chuyển đổi tiền mặt',
      expression: 'CCC = DIO + DSO - DPO',
      explanation: 'DIO, DSO và DPO thường dùng số dư bình quân chia cho dòng chi phí hoặc doanh thu phù hợp rồi quy đổi sang ngày. So sánh theo xu hướng của chính công ty và cùng ngành.',
    },
    workedExample: {
      context: 'DIO là 50 ngày, DSO là 40 ngày và DPO là 28 ngày.',
      calculation: 'CCC = 50 + 40 - 28 = 62 ngày.',
      conclusion: 'Công ty tự tài trợ khoảng 62 ngày hoạt động trước khi thu được tiền. Nếu DSO giảm 10 ngày mà doanh thu giữ nguyên, nhu cầu vốn lưu động có thể giảm đáng kể.',
    },
    pitfall: 'Kết luận CCC thấp luôn tốt. Mỗi ngành có mô hình tiền khác nhau; giảm tồn kho quá sâu còn có thể làm mất doanh thu vì hết hàng.',
    jobOutput: 'Một bảng theo tháng gồm tồn kho, phải thu, phải trả, DIO/DSO/DPO, nhận xét nguyên nhân và một chủ sở hữu hành động cho từng biến động lớn.',
    practice: {
      case: 'Doanh thu tăng 20% nhưng tiền từ hoạt động lại giảm. Số liệu cho thấy phải thu tăng 90 triệu, tồn kho tăng 60 triệu, phải trả tăng 25 triệu.',
      steps: [
        'Tính tác động ròng sơ bộ của ba khoản vốn lưu động đến tiền.',
        'Đặt ba giả thuyết nguyên nhân, trong đó ít nhất một giả thuyết cần được xác minh với đội vận hành.',
        'Đề xuất một hành động cho thu hồi công nợ, một cho tồn kho và một cho điều khoản nhà cung cấp.',
        'Nêu rủi ro nếu chỉ ép DPO tăng mà không trao đổi với mua hàng.',
      ],
      checklist: [
        'Đã dùng đúng chiều dấu khi giải thích tiền mặt.',
        'Phân biệt số dư cuối kỳ với mức bình quân khi tính ngày.',
        'Đề xuất không làm tổn hại doanh thu hoặc chuỗi cung ứng mà không nêu đánh đổi.',
      ],
    },
    sources: ['mit-15402', 'nyu-damodaran'],
    lastVerified: '2026-08-17',
  },
  {
    id: 'monthly-close-variance',
    order: '06',
    label: 'FP&A',
    minutes: '70 phút',
    title: 'Monthly close và variance analysis để quản lý ra quyết định',
    outcome: 'Bạn biết một chu kỳ close cơ bản, có thể tách chênh lệch Actual vs Budget thành nguyên nhân và viết memo ngắn có hành động.',
    objective: 'Biến số liệu khóa sổ thành phân tích chênh lệch có mức độ ưu tiên, nguyên nhân và hành động rõ ràng.',
    prerequisite: 'Hoàn thành mô-đun 03 và 04; biết Actual, Budget, Forecast là gì.',
    question: 'Kết quả tháng này lệch kế hoạch ở đâu, tại sao, có kéo dài đến cuối năm không và ai sẽ làm gì tiếp theo?',
    explain: 'Sau khi kế toán khóa sổ, nhiệm vụ của FP&A mới bắt đầu. Bảng số cần được biến thành thông tin ra quyết định: điều gì thay đổi, mức độ quan trọng, nguyên nhân gốc, tác động dự báo và hành động. Báo cáo tốt ngắn nhưng kiểm chứng được.',
    blocks: [
      {
        title: 'Kỷ luật close',
        text: 'Cần có lịch nhận dữ liệu, kiểm tra cut-off, đối soát với kế toán, đóng phiên bản và ghi rõ thay đổi. Nếu không kiểm soát phiên bản, cùng một chỉ tiêu có thể có nhiều “sự thật”.',
      },
      {
        title: 'Cầu nối variance',
        text: 'Tách chênh lệch thành giá, lượng, mix, tỷ giá, thời điểm ghi nhận, chi phí một lần hoặc năng suất. Điều này tốt hơn câu “doanh thu giảm 5%” vì chỉ ra nơi cần hành động.',
      },
      {
        title: 'Materiality',
        text: 'Không phải mọi chênh lệch đều đáng báo cáo. Xếp ưu tiên theo giá trị tuyệt đối, tỷ lệ, mức lặp lại và tác động đến mục tiêu năm.',
      },
    ],
    formula: {
      label: 'Chênh lệch và tỷ lệ chênh lệch',
      expression: 'Variance = Actual - Budget; Variance % = (Actual - Budget) / Budget',
      explanation: 'Quy ước màu tốt/xấu phụ thuộc dòng chỉ tiêu. Doanh thu cao hơn budget thường tốt, còn chi phí cao hơn budget cần xem có tạo thêm giá trị không.',
    },
    workedExample: {
      context: 'Marketing Actual là 180 triệu, Budget là 130 triệu. Chiến dịch phát sinh thêm 1.000 đơn với phần đóng góp 70.000 đồng mỗi đơn.',
      calculation: 'Chi phí vượt budget 50 triệu, nhưng đóng góp tăng thêm là 70 triệu. Tác động sơ bộ sau marketing là dương 20 triệu, trước khi xét hiệu ứng dài hạn và chi phí liên quan.',
      conclusion: 'Không nên gọi mọi chi phí vượt kế hoạch là xấu. Cần nối chi phí với kết quả kinh doanh và tính bền vững của kết quả.',
    },
    pitfall: 'Đưa ra lời giải thích chung chung như “thị trường khó khăn” mà không có dữ liệu, mức độ tác động và người chịu trách nhiệm xác nhận.',
    jobOutput: 'Một memo một trang: headline, ba variance quan trọng, forecast cuối năm, rủi ro, hành động, chủ sở hữu và hạn hoàn thành.',
    practice: {
      case: 'P&L tháng có doanh thu dưới budget 8%, biên gộp cao hơn 2 điểm phần trăm và chi phí lương cao hơn 12% vì tuyển sớm.',
      steps: [
        'Tính variance giá trị và phần trăm cho ba chỉ tiêu.',
        'Nêu giả thuyết nguyên nhân cho doanh thu, biên và lương; đánh dấu giả thuyết cần chứng cứ.',
        'Viết headline không quá 25 từ cho quản lý.',
        'Đưa ba hành động, mỗi hành động có chủ sở hữu và thời hạn.',
      ],
      checklist: [
        'Không trộn Actual vs Budget với Actual vs tháng trước.',
        'Có quy ước đơn vị và dấu tốt/xấu rõ ràng.',
        'Mỗi hành động trả lời được “ai làm gì khi nào”.',
      ],
    },
    sources: ['mit-15402', 'nyu-damodaran'],
    lastVerified: '2026-08-17',
  },
  {
    id: 'cash-budget-liquidity',
    order: '07',
    label: 'Thanh khoản',
    minutes: '75 phút',
    title: 'Cash budget và kế hoạch thanh khoản 13 tuần',
    outcome: 'Bạn dựng được cash forecast theo tuần, hiểu khoảng trống thanh khoản và biết phân biệt lợi nhuận với khả năng trả tiền đúng hạn.',
    objective: 'Dự báo được thời điểm thu chi và nhận diện sớm rủi ro thiếu tiền trong ngắn hạn.',
    prerequisite: 'Hoàn thành mô-đun 02 và 05.',
    question: 'Công ty có đủ tiền trong từng tuần để trả lương, nhà cung cấp, thuế, lãi vay và đầu tư bắt buộc không?',
    explain: 'P&L thường theo tháng, còn khủng hoảng tiền mặt có thể xảy ra trong một tuần. Cash budget giúp finance nhìn thời điểm thu chi, không chỉ tổng số cả năm. Với doanh nghiệp biến động mạnh, forecast 13 tuần là công cụ thực tế để điều hành thanh khoản.',
    blocks: [
      {
        title: 'Dự báo thu tiền',
        text: 'Bắt đầu từ lịch hóa đơn, điều khoản thanh toán, tỷ lệ thu đúng hạn và khoản nợ quá hạn. Doanh thu dự báo chỉ là đầu vào; lịch thu tiền mới đi vào cash forecast.',
      },
      {
        title: 'Dự báo chi tiền',
        text: 'Phân loại khoản phải chi theo thời điểm: lương, thuế, mua hàng, thuê, nợ, CAPEX và chi bất thường. Nhiều chi phí đã ghi nhận trước nhưng sẽ chi tiền sau.',
      },
      {
        title: 'Đệm thanh khoản',
        text: 'Thiết lập mức tiền tối thiểu phù hợp rủi ro. Khi forecast xuống dưới ngưỡng, cần chuẩn bị hành động như đẩy thu nợ, hoãn chi không thiết yếu hoặc trao đổi nguồn tài trợ sớm.',
      },
    ],
    formula: {
      label: 'Số dư tiền cuối kỳ',
      expression: 'Tiền cuối tuần = Tiền đầu tuần + Tiền thu - Tiền chi',
      explanation: 'Số dư cuối tuần trở thành số dư đầu tuần kế tiếp. Luôn ghi riêng hạn mức tín dụng và các khoản tiền bị hạn chế sử dụng.',
    },
    workedExample: {
      context: 'Tiền đầu tuần là 300 triệu; dự kiến thu 180 triệu; chi lương 200 triệu, trả nhà cung cấp 160 triệu và trả lãi 20 triệu.',
      calculation: 'Tiền cuối tuần = 300 + 180 - 200 - 160 - 20 = 100 triệu đồng.',
      conclusion: 'Nếu mức tiền tối thiểu là 150 triệu, finance cần xử lý thiếu hụt 50 triệu trước tuần đó, không chờ đến khi tài khoản thiếu tiền.',
    },
    pitfall: 'Lấy lợi nhuận forecast làm tiền thu. Các điều khoản thanh toán, VAT/thuế, trả nợ gốc, CAPEX và thay đổi vốn lưu động có thể làm tiền rất khác lợi nhuận.',
    jobOutput: 'Một forecast tiền 13 tuần có lịch thu, lịch chi, số dư tối thiểu, hạn mức và bảng hành động cho các tuần âm hoặc sát ngưỡng.',
    practice: {
      case: 'Bạn có 4 tuần dữ liệu thu tiền khách hàng, trả nhà cung cấp, lương và khoản thuế cố định. Tuần 3 có CAPEX bắt buộc 120 triệu.',
      steps: [
        'Lập bảng theo cột tuần 1 đến tuần 4, bắt đầu bằng tiền đầu kỳ.',
        'Tách thu tiền từ khách cũ và doanh thu mới nếu thời hạn thanh toán khác nhau.',
        'Đánh dấu tuần có tiền cuối kỳ dưới ngưỡng 150 triệu.',
        'Đề xuất ít nhất hai đòn bẩy và nêu đánh đổi của từng đòn bẩy.',
      ],
      checklist: [
        'Số dư đầu kỳ tuần sau khớp số dư cuối kỳ tuần trước.',
        'Không bỏ sót thuế, trả nợ gốc hoặc CAPEX nếu tình huống có nêu.',
        'Hành động thanh khoản có thời điểm và người cần trao đổi.',
      ],
    },
    sources: ['mit-15402', 'nyu-damodaran'],
    lastVerified: '2026-08-17',
  },
  {
    id: 'capex-npv-irr-sensitivity',
    order: '08',
    label: 'Đầu tư vốn',
    minutes: '90 phút',
    title: 'CAPEX, dòng tiền tăng thêm, NPV, IRR và sensitivity',
    outcome: 'Bạn đánh giá được một dự án bằng dòng tiền tăng thêm sau thuế, hiểu NPV là chỉ tiêu quyết định chính và dùng sensitivity để trình bày sự không chắc chắn.',
    objective: 'Lập và phản biện được business case đầu tư dựa trên giá trị hiện tại của dòng tiền tăng thêm.',
    prerequisite: 'Hoàn thành mô-đun 03, 05 và 07; hiểu dòng tiền khác lợi nhuận.',
    question: 'Có nên chi tiền hôm nay để mở điểm bán, mua máy, xây hệ thống hay ra sản phẩm mới?',
    explain: 'Quyết định đầu tư vốn phải dựa vào dòng tiền tăng thêm so với phương án không đầu tư. NPV đưa các dòng tiền khác thời điểm về cùng một mốc bằng tỷ lệ chiết khấu phù hợp rủi ro. IRR và thời gian hoàn vốn hữu ích để giao tiếp, nhưng không thay thế câu hỏi dự án tạo bao nhiêu giá trị tuyệt đối.',
    blocks: [
      {
        title: 'Dòng tiền tăng thêm',
        text: 'Chỉ đưa vào doanh thu, chi phí, thuế, vốn lưu động và CAPEX thay đổi vì dự án. Chi phí đã phát sinh và không thể thu hồi là chi phí chìm, không nên quyết định thay cho tương lai.',
      },
      {
        title: 'Giá trị thời gian của tiền',
        text: 'Một đồng hôm nay có thể được đầu tư, đồng thời dòng tiền tương lai có rủi ro. Tỷ lệ chiết khấu phản ánh mức sinh lời tối thiểu hoặc chi phí cơ hội tương ứng.',
      },
      {
        title: 'Sensitivity và kịch bản',
        text: 'Đừng chỉ đưa một NPV. Hãy thử thay sản lượng, giá, biên, CAPEX, thời gian triển khai và tỷ lệ chiết khấu để thấy biến nào có thể đảo kết luận.',
      },
    ],
    formula: {
      label: 'Giá trị hiện tại ròng',
      expression: 'NPV = Tổng[FCF_t / (1 + r)^t] - Vốn đầu tư ban đầu',
      explanation: 'FCF_t là dòng tiền tự do tăng thêm ở kỳ t, r là tỷ lệ chiết khấu. Khi dòng tiền đầu kỳ không phải một lần hoặc có giá trị thanh lý, đặt chúng đúng thời điểm.',
    },
    workedExample: {
      context: 'Dự án cần 1.000 triệu đồng hôm nay, tạo dòng tiền tăng thêm 450 triệu đồng mỗi năm trong 3 năm; tỷ lệ chiết khấu 12%.',
      calculation: 'Giá trị hiện tại lần lượt xấp xỉ 401,8; 358,7; 320,3 triệu đồng. Tổng 1.080,8 triệu đồng, nên NPV xấp xỉ 80,8 triệu đồng.',
      conclusion: 'Theo giả định này dự án tạo giá trị. Tuy nhiên cần thử giảm dòng tiền hoặc tăng tỷ lệ chiết khấu trước khi khuyến nghị.',
    },
    pitfall: 'Đưa cả khoản vay vào dòng tiền dự án rồi lại chiết khấu bằng WACC. Hãy tách quyết định đầu tư khỏi cấu trúc tài trợ để tránh đếm hai lần chi phí vốn.',
    jobOutput: 'Một business case có tab Assumptions, FCF, NPV, sensitivity, rủi ro và memo khuyến nghị một trang.',
    practice: {
      case: 'Công ty cân nhắc mua máy đóng gói. Máy giảm chi phí lao động nhưng cần bảo trì, tăng tồn kho phụ tùng và chỉ chạy sau 3 tháng lắp đặt.',
      steps: [
        'Liệt kê dòng tiền tăng thêm theo năm: CAPEX, tiết kiệm chi phí, bảo trì, thuế, vốn lưu động và giá trị thanh lý.',
        'Tính NPV bằng một tỷ lệ chiết khấu giả định và ghi rõ lý do dùng tỷ lệ đó.',
        'Tạo bảng sensitivity cho sản lượng giảm 15% và CAPEX tăng 10%.',
        'Viết khuyến nghị có điều kiện: chấp thuận, hoãn hoặc cần thêm dữ liệu nào.',
      ],
      checklist: [
        'Không dùng doanh thu toàn công ty thay cho dòng tiền tăng thêm.',
        'Có xét thời điểm dòng tiền, không cộng thẳng các năm.',
        'Khuyến nghị nêu rủi ro quan trọng nhất và ngưỡng đảo chiều.',
      ],
    },
    sources: ['mit-15401', 'mit-15402', 'nyu-damodaran'],
    lastVerified: '2026-08-17',
  },
  {
    id: 'wacc-capital-structure',
    order: '09',
    label: 'Nguồn vốn',
    minutes: '80 phút',
    title: 'WACC, cấu trúc vốn và lựa chọn nguồn tài trợ',
    outcome: 'Bạn hiểu doanh nghiệp không chỉ chọn dự án mà còn phải chọn nguồn vốn, biết ý nghĩa trực giác của WACC, đòn bẩy tài chính và các đánh đổi giữa nợ và vốn chủ.',
    objective: 'So sánh được các nguồn tài trợ theo chi phí, lịch tiền, rủi ro và khả năng chịu đựng của doanh nghiệp.',
    prerequisite: 'Hoàn thành mô-đun 08; hiểu tỷ lệ chiết khấu là yêu cầu sinh lời có điều chỉnh rủi ro.',
    question: 'Nên dùng tiền mặt, vay nợ, vốn chủ, thuê tài sản hay kết hợp nhiều nguồn để tài trợ một kế hoạch?',
    explain: 'Nợ thường rẻ hơn vốn chủ nhưng tạo nghĩa vụ trả lãi và gốc cố định. Vốn chủ linh hoạt hơn nhưng pha loãng quyền sở hữu và nhà đầu tư vẫn đòi hỏi lợi suất. Cấu trúc vốn phù hợp phụ thuộc tính ổn định của dòng tiền, tài sản thế chấp, chu kỳ ngành, hạn mức tín dụng và khả năng chịu rủi ro.',
    blocks: [
      {
        title: 'Chi phí nợ sau thuế',
        text: 'Lãi vay là chi phí hợp đồng và trong nhiều bối cảnh có tác động thuế, nhưng nợ không miễn phí: doanh nghiệp phải đáp ứng lịch trả nợ, điều khoản vay và rủi ro tái cấp vốn.',
      },
      {
        title: 'Chi phí vốn chủ',
        text: 'Vốn chủ không có hóa đơn lãi hàng tháng, song chủ sở hữu kỳ vọng lợi suất tương xứng rủi ro. Dùng vốn chủ cho mọi dự án có thể làm phân bổ vốn kém kỷ luật.',
      },
      {
        title: 'WACC là khung, không phải con số thần kỳ',
        text: 'WACC có thể là điểm xuất phát cho dự án có rủi ro tương tự hoạt động cốt lõi. Dự án rủi ro khác biệt cần kiểm tra tỷ lệ chiết khấu và phương pháp điều chỉnh phù hợp hơn.',
      },
    ],
    formula: {
      label: 'Chi phí vốn bình quân gia quyền',
      expression: 'WACC = wD x rD x (1 - T) + wE x rE',
      explanation: 'wD và wE là tỷ trọng nợ, vốn chủ; rD và rE là chi phí từng nguồn; T là thuế suất giả định. Các đầu vào phải nhất quán về thị trường, tiền tệ và thời điểm.',
    },
    workedExample: {
      context: 'Một công ty có 40% nợ với chi phí nợ 9%, 60% vốn chủ với chi phí vốn chủ 16%, thuế suất 20%.',
      calculation: 'WACC = 40% x 9% x (1 - 20%) + 60% x 16% = 12,48%.',
      conclusion: 'WACC là mức tham chiếu để đánh giá dự án tương tự rủi ro của công ty, không phải lý do duy nhất để quyết định vay thêm.',
    },
    pitfall: 'Tăng nợ vì thấy lãi suất thấp mà bỏ qua lịch trả gốc, covenant, biến động lãi suất và khả năng dòng tiền xấu đi. Thanh khoản có thể quan trọng hơn chi phí danh nghĩa.',
    jobOutput: 'Một trang so sánh 3 phương án tài trợ theo chi phí, lịch tiền, điều kiện, rủi ro và khuyến nghị.',
    practice: {
      case: 'Công ty cần 2 tỷ đồng cho dự án 4 năm. Có thể dùng tiền mặt, vay ngân hàng lãi 10%, hoặc gọi vốn chủ. Dòng tiền dự án biến động theo mùa.',
      steps: [
        'Liệt kê điều doanh nghiệp cần biết trước khi chọn nguồn vốn: tiền hiện có, lịch trả nợ, tài sản đảm bảo, hạn mức và covenant.',
        'Tính một WACC minh họa với tỷ trọng nợ/vốn chủ tự chọn và ghi rõ đây là giả định học tập.',
        'Lập bảng lợi ích - rủi ro của ba phương án.',
        'Khuyến nghị phương án hoặc kết hợp phương án, kèm điều kiện cần được phê duyệt.',
      ],
      checklist: [
        'Không gọi lãi vay là chi phí duy nhất của nợ.',
        'Có xét dòng tiền trả nợ theo mùa vụ.',
        'Không dùng WACC cứng nhắc cho mọi loại dự án.',
      ],
    },
    sources: ['mit-15401', 'mit-15402', 'nyu-damodaran'],
    lastVerified: '2026-08-17',
  },
  {
    id: 'valuation-decision-memo',
    order: '10',
    label: 'Định giá',
    minutes: '95 phút',
    title: 'Định giá doanh nghiệp và viết decision memo',
    outcome: 'Bạn hiểu định giá là một tập hợp giả định có kiểm chứng, dựng được DCF tối giản và truyền đạt được khoảng giá trị cùng các yếu tố nhạy cảm.',
    objective: 'Xây được định giá DCF cơ bản và chuyển kết quả thành khuyến nghị có điều kiện thay vì một con số đơn lẻ.',
    prerequisite: 'Hoàn thành mô-đun 04, 08 và 09.',
    question: 'Một doanh nghiệp hoặc dự án đáng giá bao nhiêu, và giả định nào khiến kết luận đó thay đổi mạnh nhất?',
    explain: 'Định giá không cho một “giá đúng” duy nhất. Nó buộc người phân tích nói rõ dự báo dòng tiền, tốc độ tăng trưởng, biên lợi nhuận, tái đầu tư và rủi ro. Trong corporate finance, định giá giúp so sánh phương án mua, bán, đầu tư hoặc hợp tác; trong FP&A, tư duy định giá giúp ưu tiên nguồn lực dài hạn.',
    blocks: [
      {
        title: 'Enterprise value và equity value',
        text: 'Enterprise value nhìn giá trị hoạt động trước nguồn tài trợ; equity value là phần còn lại cho chủ sở hữu sau khi xét nợ ròng và các điều chỉnh liên quan. Không được so sánh nhầm chỉ tiêu hoạt động với chỉ tiêu vốn chủ.',
      },
      {
        title: 'DCF tối giản',
        text: 'Dự báo free cash flow trong giai đoạn hữu hạn, chiết khấu về hiện tại, sau đó ước tính giá trị tiếp diễn với giả định thận trọng. Giá trị tiếp diễn thường nhạy cảm nên phải trình bày rõ.',
      },
      {
        title: 'Tính hợp lý chéo',
        text: 'So sánh với bội số thị trường hoặc giao dịch tương đồng để phát hiện giả định bất thường. Bội số hỗ trợ kiểm tra, không thay thế hiểu biết về dòng tiền và rủi ro riêng.',
      },
    ],
    formula: {
      label: 'Giá trị tiếp diễn theo tăng trưởng ổn định',
      expression: 'Terminal value = FCF_(n+1) / (WACC - g)',
      explanation: 'Cần có WACC lớn hơn g và g phải phù hợp với trạng thái tăng trưởng dài hạn. Đây là giả định nhạy cảm, không nên dùng mức tăng trưởng cao vĩnh viễn.',
    },
    workedExample: {
      context: 'FCF năm tới dự kiến 120 triệu đồng, WACC 12%, tăng trưởng dài hạn 4%.',
      calculation: 'Terminal value tại cuối năm hiện tại = 120 / (12% - 4%) = 1.500 triệu đồng, sau đó vẫn cần chiết khấu về thời điểm định giá nếu nó nằm ở cuối một giai đoạn forecast.',
      conclusion: 'Chỉ cần g hoặc WACC thay đổi nhỏ, giá trị có thể đổi mạnh. Vì vậy decision memo phải nêu khoảng giá trị và sensitivity.',
    },
    pitfall: 'Đưa ra một con số định giá với hai chữ số thập phân nhưng không nêu giả định, kỳ dự báo, nợ ròng hoặc độ nhạy. Độ chính xác trình bày không tạo ra độ chính xác kinh tế.',
    jobOutput: 'Một decision memo hai trang có kết luận trước, khoảng giá trị, bảng giả định, sensitivity 2 chiều và khuyến nghị hành động.',
    practice: {
      case: 'Một công ty cân nhắc mua đối thủ nhỏ. Bạn có forecast FCF 5 năm, nợ ròng mục tiêu và hai nhóm công ty so sánh.',
      steps: [
        'Xây DCF tối giản với năm forecast rõ ràng và terminal value thận trọng.',
        'Chuyển enterprise value sang equity value bằng nợ ròng giả định.',
        'Tạo bảng sensitivity WACC và tăng trưởng dài hạn.',
        'Viết memo: giá đề nghị tối đa, lý do, dữ liệu còn thiếu và điều kiện trước khi ký.',
      ],
      checklist: [
        'Không trộn enterprise value với equity value.',
        'Có ghi rõ đơn vị tiền, ngày định giá và giả định tăng trưởng.',
        'Khuyến nghị thể hiện khoảng giá trị, không chỉ một điểm.',
      ],
    },
    sources: ['mit-15401', 'mit-15402', 'nyu-damodaran'],
    lastVerified: '2026-08-17',
  },
  {
    id: 'controls-model-review',
    order: '11',
    label: 'Kỹ năng làm việc',
    minutes: '70 phút',
    title: 'Kiểm soát số liệu, review model và giao tiếp với người ra quyết định',
    outcome: 'Bạn tạo được file tài chính dễ review, biết các kiểm tra logic cơ bản, quản lý phiên bản và trình bày kết luận trước bảng tính.',
    objective: 'Thiết kế được workbook có khả năng truy vết, kiểm tra và bàn giao cho người khác review.',
    prerequisite: 'Đã làm ít nhất một workbook ở mô-đun 04, 06 hoặc 08.',
    question: 'Làm sao để người khác có thể tin, kiểm tra và dùng lại file của bạn sau một tuần không ngồi cạnh bạn?',
    explain: 'Công việc finance tốt không chỉ đúng khi người tạo file mở nó. File phải có cấu trúc rõ, đầu vào phân biệt đầu ra, công thức nhất quán, kiểm tra lỗi và dấu vết nguồn dữ liệu. Kỹ năng này tạo niềm tin cho intern và junior nhanh hơn một dashboard đẹp.',
    blocks: [
      {
        title: 'Thiết kế workbook',
        text: 'Tách Inputs/Assumptions, dữ liệu nguồn, tính toán và Outputs. Dùng nhãn, đơn vị, kỳ thời gian và quy ước màu nhất quán. Tránh viết số cứng vào công thức khi số đó là một giả định.',
      },
      {
        title: 'Kiểm tra logic',
        text: 'Tạo các dòng check: bảng cân đối có cân, tổng chi tiết có khớp tổng hợp, tỷ lệ có bất thường, thời gian có bị lệch, dòng tiền có bắt đầu và kết thúc đúng hay không.',
      },
      {
        title: 'Kể chuyện bằng số',
        text: 'Một quản lý thường cần headline, bằng chứng, rủi ro và đề xuất. Đặt kết luận lên trước, sau đó mới là bảng hỗ trợ. Ghi rõ đâu là Actual, đâu là Forecast và độ tin cậy của dữ liệu.',
      },
    ],
    formula: {
      label: 'Kiểm tra cân đối',
      expression: 'Balance check = Tài sản - Nợ phải trả - Vốn chủ sở hữu = 0',
      explanation: 'Ngoài phép kiểm tra này, model nên có check nguồn - sử dụng tiền, check tổng chi tiết và check tỷ lệ hợp lý theo thời gian.',
    },
    workedExample: {
      context: 'Một file forecast có tổng doanh thu trên trang Summary là 1.250 triệu nhưng tổng theo sản phẩm là 1.230 triệu.',
      calculation: 'Check chênh lệch = 1.250 - 1.230 = 20 triệu đồng, không được bỏ qua dù tỷ lệ nhỏ.',
      conclusion: 'Trước khi gửi, cần lần lại phạm vi dữ liệu, liên kết công thức và kỳ thời gian. Số đẹp nhưng không đối chiếu được sẽ làm mất niềm tin.',
    },
    pitfall: 'Chỉ kiểm tra công thức không báo lỗi Excel. Sai phạm vi SUM, trộn đơn vị nghìn với triệu, liên kết nhầm tab hoặc dùng dữ liệu cũ vẫn có thể cho ra số “hợp lý”.',
    jobOutput: 'Một workbook có tab README, Assumptions, Data, Calculations, Output và ít nhất năm dòng kiểm tra; kèm memo 5-8 câu cho quản lý.',
    practice: {
      case: 'Bạn nhận một file forecast của người khác không có mô tả, số liệu từ ba nguồn và một chart gửi cho sếp vào chiều nay.',
      steps: [
        'Lập danh sách nguồn, ngày dữ liệu và người xác nhận từng nguồn.',
        'Tạo kiểm tra tổng, kiểm tra đơn vị, kiểm tra kỳ và kiểm tra bảng cân đối nếu có.',
        'Tô rõ phần input thủ công, công thức và output; thêm tab README ngắn.',
        'Viết email hoặc memo nêu ba kết luận, hai giới hạn dữ liệu và một quyết định cần quản lý chốt.',
      ],
      checklist: [
        'Có thể tìm nguồn của mọi input quan trọng.',
        'Không để công thức chứa con số khó giải thích.',
        'Người review có thể thấy ngay các check pass/fail.',
      ],
    },
    sources: ['mit-15402', 'nyu-damodaran'],
    lastVerified: '2026-08-17',
  },
  {
    id: 'capstone-career-portfolio',
    order: '12',
    label: 'Đi làm',
    minutes: '120 phút',
    title: 'Capstone: portfolio và phỏng vấn cho vị trí intern hoặc junior finance',
    outcome: 'Bạn hoàn thiện một portfolio ba sản phẩm, trình bày được quy trình phân tích và trả lời case phỏng vấn bằng giả định, số liệu, rủi ro và hành động.',
    objective: 'Tổng hợp các kỹ năng thành bằng chứng ứng tuyển rõ ràng, trung thực và phù hợp với công việc finance đầu vào.',
    prerequisite: 'Hoàn thành hoặc đang làm các mô-đun 04, 06, 08 và 11.',
    question: 'Nhà tuyển dụng cần thấy bằng chứng nào cho thấy bạn có thể biến số liệu thô thành kết luận đáng tin cậy?',
    explain: 'Người mới không cần một model quá lớn. Portfolio tốt chứng minh ba năng lực: hiểu vấn đề kinh doanh, xây số liệu sạch có kiểm tra và giao tiếp được kết luận. Hãy dùng dữ liệu mô phỏng hoặc công khai, không đưa dữ liệu nhạy cảm của nơi thực tập lên mạng.',
    blocks: [
      {
        title: 'Ba sản phẩm đủ mạnh',
        text: 'Một forecast P&L theo drivers, một variance analysis một trang và một business case NPV/sensitivity. Ba sản phẩm này phản ánh phần lớn công việc nền tảng của FP&A và corporate finance.',
      },
      {
        title: 'Cách nói về bài làm',
        text: 'Dùng cấu trúc: bối cảnh, câu hỏi, nguồn dữ liệu, giả định, phương pháp, kết luận, rủi ro và bước tiếp theo. Đừng chỉ khoe biểu đồ hoặc công thức.',
      },
      {
        title: 'Tính chuyên nghiệp',
        text: 'Ẩn dữ liệu nhạy cảm, ghi nguồn, nêu giới hạn và phân biệt rõ dữ liệu thật với số liệu mô phỏng. Khi không biết, hãy nói dữ liệu nào cần xin và cách bạn sẽ kiểm chứng.',
      },
    ],
    formula: {
      label: 'Khung trả lời case',
      expression: 'Kết luận -> Bằng chứng -> Rủi ro/giả định -> Hành động tiếp theo',
      explanation: 'Khung này không phải công thức toán; nó giúp câu trả lời có thứ tự, tránh nhảy thẳng vào bảng số trước khi làm rõ điều quản lý cần quyết định.',
    },
    workedExample: {
      context: 'Câu hỏi phỏng vấn: “Doanh thu dưới budget 6%, em sẽ làm gì?”',
      calculation: 'Câu trả lời có thể bắt đầu: xác nhận phạm vi và chất lượng dữ liệu; tách chênh lệch thành lượng, giá, mix, thời điểm; ước tính tác động forecast năm; sau đó đề xuất hành động với Sales, Operations và Marketing.',
      conclusion: 'Điểm mạnh không phải đoán một nguyên nhân, mà là cho thấy cách kiểm tra, ưu tiên và hành động dựa trên số liệu.',
    },
    pitfall: 'Đưa file có công thức hỏng, nguồn không rõ hoặc số liệu công ty thật chưa được phép chia sẻ. Uy tín và bảo mật quan trọng như kỹ năng tính toán.',
    jobOutput: 'Một thư mục portfolio gồm README, 3 workbook/PDF, một memo cho mỗi case và một trang CV mô tả đúng đóng góp, công cụ và kết quả học tập.',
    practice: {
      case: 'Đóng vai ứng viên FP&A intern. Bạn có 7 phút để giới thiệu một case forecast và nhận 3 câu hỏi phản biện từ người phỏng vấn.',
      steps: [
        'Chọn case có dữ liệu mô phỏng hoặc công khai, ghi rõ nguồn và mục tiêu.',
        'Chuẩn bị 5 slide hoặc 1 memo gồm kết luận, drivers, forecast, rủi ro và đề xuất.',
        'Tự phản biện ba giả định: nếu sản lượng thấp hơn, giá thay đổi hoặc chi phí tăng thì kết luận ra sao.',
        'Rà soát file theo checklist mô-đun 11 trước khi chia sẻ.',
      ],
      checklist: [
        'Mỗi case có mục tiêu, dữ liệu, giả định và kết luận rõ.',
        'Không chứa dữ liệu mật hoặc nhận mình làm điều chưa làm.',
        'Có thể trình bày quyết định trong 60 giây trước khi mở chi tiết.',
      ],
    },
    sources: ['mit-15401', 'mit-15402', 'nyu-damodaran'],
    lastVerified: '2026-08-17',
  },
]

export const CORPORATE_FINANCE_LABS = [
  {
    id: 'pnl-lab',
    title: 'Lab P&L và điểm hòa vốn',
    moduleIds: ['pnl-unit-economics'],
    purpose: 'Thay đổi doanh thu, giá vốn và chi phí để quan sát đường đi từ doanh thu đến lợi nhuận.',
  },
  {
    id: 'variance-lab',
    title: 'Lab Actual vs Budget',
    moduleIds: ['budget-forecast-drivers', 'monthly-close-variance'],
    purpose: 'Tách chênh lệch doanh thu và chi phí thành nguyên nhân, rồi viết memo hành động.',
  },
  {
    id: 'working-capital-lab',
    title: 'Lab chu kỳ tiền mặt',
    moduleIds: ['working-capital-cash-cycle'],
    purpose: 'Thử thay đổi DIO, DSO, DPO để thấy tiền bị giam ở đâu.',
  },
  {
    id: 'cash-budget-lab',
    title: 'Lab kế hoạch tiền 13 tuần',
    moduleIds: ['cash-budget-liquidity'],
    purpose: 'Xây dòng thu chi theo tuần và phát hiện khoảng trống thanh khoản trước khi nó xảy ra.',
  },
  {
    id: 'npv-lab',
    title: 'Lab NPV và sensitivity',
    moduleIds: ['capex-npv-irr-sensitivity', 'wacc-capital-structure'],
    purpose: 'Đánh giá dự án từ dòng tiền tăng thêm, tỷ lệ chiết khấu và các kịch bản xấu hơn.',
  },
]
