// ═══ REGISTRY GIẢI THÍCH TẬP TRUNG — nguồn DUY NHẤT cho mọi con số trên web ═══
// Dùng bởi <ExplainableValue>. Nếu metricKey không có ở đây → hiện lỗi dev thấy được (không fallback im lặng).
// Ghi chú: mọi "ngưỡng" (ROE 15%, nợ/vốn 100%...) chỉ là gợi ý giáo dục, KHÔNG phải luật cho mọi ngành.

export const METRICS = {
  indexPoints: { labelVi: 'Điểm chỉ số thị trường', en: 'Index Points', cat: 'Thị trường',
    def: '"Giá" của một GIỎ cổ phiếu tiêu biểu — không phải giá 1 cổ phiếu nào cả, mà là điểm số tổng hợp cả rổ.',
    why: 'Là nhiệt kế của cả thị trường: chỉ số giảm = đa số cổ phiếu đang giảm, dù cp riêng của bạn có thể ngược chiều.',
    formula: 'Tính theo giá của rổ cp thành phần (mỗi chỉ số có công thức riêng, có trọng số theo vốn hóa)', parts: [],
    example: 'VN-Index 1.729 điểm — con số này so với chính nó hôm qua (−2,07%), không mua bán được như giá cp.',
    up: 'Thị trường chung đang色调 xanh', down: 'Thị trường chung đỏ', flat: 'Đi ngang',
    pitfalls: 'Chỉ số là BỐI CẢNH cho cp riêng — cp tốt vẫn giảm khi cả thị trường bán tháo, và ngược lại.',
    unit: 'điểm', terms: ['Chỉ số thị trường (Index)'], lesson: 'thi-truong-va-bang-gia', task: 'morning-brief' },
  healthScore: { labelVi: 'Điểm nhóm Health Check', en: 'Health Check Group Score', cat: 'Học tập',
    def: 'Điểm 0–10 của 1 nhóm sức khỏe (sinh lời/tăng trưởng/đòn bẩy/dòng tiền/định giá) theo quy tắc ngưỡng giáo dục.',
    why: 'Tách sức khỏe doanh nghiệp thành 5 khía cạnh để không gộp mọi thứ thành một chữ "tốt/xấu".',
    formula: 'Quy tắc bậc thang trên tỷ số của nhóm (VD dòng tiền: OCF/LN ≥90% → 10đ, ≥70% → 7đ...)', parts: [],
    example: 'ROE 23,5% → nhóm "sinh lời" ~8-9/10.',
    up: 'Nhóm đó mạnh theo mốc tham khảo', down: 'Cần kiểm tra thêm', flat: '',
    pitfalls: 'Điểm quy tắc đơn giản trên số liệu demo/manual — CHỈ để học cách đọc, không phải kết luận mua/bán; từng điểm đều kèm bằng chứng ngay bên cạnh.',
    unit: 'điểm /10', terms: [], lesson: 'chi-so-dinh-gia', task: null },
  // ── GIÁ THỊ TRƯỜNG ──────────────────────────────────────────
  price: { labelVi: 'Giá cổ phiếu', en: 'Price', cat: 'Thị trường',
    def: 'Số tiền bạn phải trả để mua 1 cổ phiếu tại giao dịch gần nhất.',
    why: 'Giá là "phiếu bầu" của thị trường về giá trị doanh nghiệp tại từng khoảnh khắc — do cung cầu quyết định, không phải do công ty tự đặt.',
    formula: 'Giá khớp lệnh mua–bán gần nhất trên sàn', parts: [],
    example: 'Ai đó sẵn sàng trả 68.300₫ cho 1 cp FPT → giá FPT lúc đó là 68.300₫.',
    up: 'Nhu cầu mua đang mạnh hơn bán', down: 'Áp lực bán đang mạnh hơn', flat: 'Cung cầu cân bằng',
    pitfalls: 'Giá thay đổi từng phút theo cảm xúc — giá rẻ hơn hôm qua chưa chắc "hời", phải so với giá trị doanh nghiệp.',
    unit: '₫ hoặc $ cho 1 cổ phiếu', terms: ['Cổ phiếu (Stock)'], lesson: 'co-phieu-la-gi', task: null },
  change: { labelVi: 'Thay đổi giá', en: 'Price Change', cat: 'Thị trường',
    def: 'Giá hiện tại trừ giá đóng cửa HÔM TRƯỚC — tính bằng tiền.',
    why: 'Cho biết trong 1 phiên thị trường đánh giá công ty này tốt hơn hay xấu hơn so với hôm qua bao nhiêu.',
    formula: 'Giá hiện tại − Giá đóng cửa hôm trước', parts: ['Giá hiện tại: giá khớp gần nhất', 'Đóng cửa hôm trước: mốc so sánh chuẩn'],
    example: 'Hôm qua đóng 70.800₫, giờ 68.300₫ → thay đổi = −2.500₫.',
    up: 'Thị trường đang thưởng', down: 'Thị trường đang phạt (hoặc chốt lời)', flat: 'Đi ngang',
    pitfalls: 'Chỉ là 1 phiên — không nói gì về xu hướng dài hạn; luôn xem % chứ không chỉ số tuyệt đối.',
    unit: '₫ hoặc $', terms: ['Giá đóng cửa (Close)'], lesson: 'thi-truong-va-bang-gia', task: 'morning-brief' },
  changePercent: { labelVi: '% thay đổi', en: 'Percent Change', cat: 'Thị trường',
    def: 'Thay đổi giá tính theo % so với đóng cửa hôm trước — để so sánh công bằng giữa các mã giá to, giá nhỏ.',
    why: '−3,5% trên cp 10.000₫ và cp 1 triệu ₫ cùng "đau" như nhau; số tuyệt đối thì không.',
    formula: '(Giá hiện tại − Đóng cửa hôm trước) ÷ Đóng cửa hôm trước × 100', parts: [],
    example: '(68.300 − 70.800) ÷ 70.800 = −3,53%.',
    up: '', down: '', flat: '',
    pitfalls: 'VN có biên độ trần/sàn ~±7%/ngày — chạm trần chưa chắc là "tốt fundament", có thể chỉ là dòng tiền nóng.',
    unit: '%', terms: ['Biên độ trần/sàn'], lesson: 'thi-truong-va-bang-gia', task: 'morning-brief' },
  volume: { labelVi: 'Khối lượng', en: 'Volume', cat: 'Thị trường',
    def: 'Số cổ phiếu đổi chủ trong phiên — "xăng" của mọi biến động giá.',
    why: 'Giá tăng kèm khối lượng lớn = nhiều tiền THẬT đồng thuận; giá tăng mà khối lượng lẹt đẹt = dễ là sóng giả.',
    formula: 'Tổng cp được giao dịch trong phiên', parts: [],
    example: '9,7 triệu cp FPT đổi chủ hôm nay — so với bình quân 20 phiên để biết "bất thường không".',
    up: 'Sôi động/dòng tiền vào', down: 'Vắng vẻ/khó bán khi cần', flat: '',
    pitfalls: 'Khối lượng lớn ở ĐÁY khác ở ĐỈNH — phải đọc kèm vị trí giá.',
    unit: 'cổ phiếu', terms: ['Khối lượng (Volume)'], lesson: 'khoi-luong-xu-huong', task: null },
  marketCap: { labelVi: 'Vốn hóa thị trường', en: 'Market Cap', cat: 'Thị trường',
    def: 'Tổng giá trị thị trường đang gán cho TOÀN BỘ công ty = giá × số cp đang lưu hành.',
    why: 'Đây là cách so "to nhỏ" công bằng giữa các công ty — giá 1 cp không nói lên quy mô.',
    formula: 'Giá cổ phiếu × Số cổ phiếu đang lưu hành', parts: [],
    example: 'Giá 68.300₫ × 1,46 tỷ cp = ~100 nghìn tỷ ₫.',
    up: 'Thị trường định giá cả công ty cao hơn', down: 'Thấp hơn', flat: '',
    pitfalls: 'Công ty có thể tăng vốn hóa bằng phát hành thêm cp (loãng) chứ không phải nhờ kinh doanh — VỐN HÓA ≠ GIÁ TRỊ THẬT.',
    unit: '₫ hoặc $', terms: ['Vốn hóa thị trường (Market Cap)'], lesson: 'thi-truong-va-bang-gia', task: null },
  beta: { labelVi: 'Beta (độ nhạy thị trường)', en: 'Beta', cat: 'Thị trường',
    def: 'Đo cổ phiếu này dao động mạnh hay nhẹ hơn thị trường chung.',
    why: 'Giúp biết trước "cảm giác ngồi trên" cp này: beta 1,5 = thị trường ±1% thì nó thường ±1,5%.',
    formula: 'Tương quan biến động cp với chỉ số (thống kê)', parts: [],
    example: 'Beta 1,2: VN-Index −2% → cp này trung bình −2,4%.',
    up: '', down: '', flat: '',
    pitfalls: 'Beta tính từ QUÁ KHỨ — tương lai có thể khác; beta thấp không đồng nghĩa an toàn.',
    unit: 'lần', terms: ['Beta'], lesson: 'quan-tri-rui-ro', task: null },

  // ── KẾT QUẢ KINH DOANH (Income Statement) ───────────────────
  revenue: { labelVi: 'Doanh thu', en: 'Revenue', cat: 'BCTC · KQKD',
    def: 'Tổng tiền doanh nghiệp ghi nhận từ bán sản phẩm/dịch vụ trong kỳ — quy mô của việc kinh doanh.',
    why: 'Là điểm khởi đầu của mọi câu chuyện lợi nhuận: không có doanh thu thì không có gì để trừ chi phí.',
    formula: 'Số lượng bán ra × giá bán (cộng lại doanh thu dịch vụ)', parts: [],
    example: 'Bán 1.000 sản phẩm × 100.000₫ = 100 triệu doanh thu — TRƯỚC khi trừ bất kỳ chi phí nào.',
    up: 'Đang mở rộng quy mô hoặc tăng giá', down: 'Co lại — tìm lý do (cạnh tranh? nhu cầu?)', flat: 'Đứng yên cũng cần giải thích',
    pitfalls: 'Doanh thu ≠ tiền đã thu: có thể bán chịu (chưa thu tiền) — LUÔN đọc cạnh OCF.',
    unit: 'tỷ ₫ / tỷ $', terms: ['Doanh thu (Revenue)'], lesson: 'bao-cao-tai-chinh-2-ket-qua', task: 'health-check' },
  revenueGrowth: { labelVi: 'Tăng trưởng doanh thu', en: 'Revenue Growth', cat: 'BCTC · KQKD',
    def: 'Doanh thu năm nay hơn năm trước bao nhiêu phần trăm.',
    why: 'Đà tăng là "nguồn sống" của cổ phiếu tăng trưởng dài hạn — lợi nhuận rất khó tăng mãi khi doanh thu đứng yên.',
    formula: '(Doanh thu năm nay − năm trước) ÷ năm trước × 100', parts: [],
    example: '52,6 → 62,8 = +19,4%.',
    up: 'Mở rộng', down: 'Co lại', flat: 'Bình ổn',
    pitfalls: '1 năm tăng vọt có thể là năm cơ sở thấp / hợp đồng một lần — hãy xem 3-5 năm.',
    unit: '%', terms: ['Tăng trưởng doanh thu (%)'], lesson: 'bao-cao-tai-chinh-2-ket-qua', task: null },
  grossProfit: { labelVi: 'Lợi nhuận gộp', en: 'Gross Profit', cat: 'BCTC · KQKD',
    def: 'Tiền lời THÔ sau khi mới trừ GIÁ VỐN hàng bán — chưa trừ lương, quảng cáo, quản lý.',
    why: 'Cho thấy "quyền lực định giá" sản phẩm: hàng hiệu ăn gian giá vốn vẫn bán được giá cao.',
    formula: 'Doanh thu − Giá vốn hàng bán', parts: ['Giá vốn: tiền làm ra sản phẩm (nguyên liệu, công nhân...)'],
    example: '62,8 − 50,9 = 11,9.',
    up: 'Bán đắt hơn hoặc sản xuất rẻ hơn', down: 'Cạnh tranh ép giá / chi phí đầu vào tăng', flat: '',
    pitfalls: 'Ngành dịch vụ gần như không có "giá vốn" rõ ràng — so cùng ngành mới có nghĩa.',
    unit: 'tỷ ₫ / tỷ $', terms: ['Lợi nhuận gộp (Gross Profit)'], lesson: 'bao-cao-tai-chinh-2-ket-qua', task: null },
  grossMargin: { labelVi: 'Biên lợi nhuận gộp', en: 'Gross Margin', cat: 'BCTC · KQKD',
    def: 'Mỗi 100 đồng doanh thu, sau khi trả giá vốn, còn lại mấy đồng.',
    why: 'Biên gộp cao & ổn định = "con hào kinh tế" (thương hiệu/công nghệ bảo vệ); biên mỏng = dễ bị bào mòn.',
    formula: 'LN gộp ÷ Doanh thu × 100', parts: [],
    example: '11,9 ÷ 62,8 = 18,9%.',
    up: 'Định giá mạnh hơn', down: 'Cạnh tranh gay / chi phí đầu vào tăng', flat: '',
    pitfalls: 'Mỗi ngành một dải — bán lẻ 20% là rất tốt, phần mềm 20% là yếu.',
    unit: '%', terms: ['Biên lợi nhuận (Profit Margin)'], lesson: 'bao-cao-tai-chinh-2-ket-qua', task: null },
  operatingIncome: { labelVi: 'Lợi nhuận hoạt động', en: 'Operating Income', cat: 'BCTC · KQKD',
    def: 'Lời từ NGHỀ chính của doanh nghiệp — đã trừ chi phí vận hành, chưa trừ lãi vay và thuế.',
    why: 'Đây là "sức khỏe cốt lõi": loại bỏ tiếng ồn của thu nhập ngoài nghề (bán đất, đổi tỷ giá...).',
    formula: 'LN gộp − Chi phí bán hàng − Chi phí quản lý', parts: [],
    example: '11,9 − 4,3 = 7,6.',
    up: 'Vận hành hiệu quả hơn', down: 'Chi phí quản lý/bán hàng phình to', flat: '',
    pitfalls: 'Công ty có thể "gói" chi phí lạ vào đây — đọc chú thích BCTC khi thấy đột biến.',
    unit: 'tỷ ₫ / tỷ $', terms: [], lesson: 'bao-cao-tai-chinh-2-ket-qua', task: null },
  operatingMargin: { labelVi: 'Biên hoạt động', en: 'Operating Margin', cat: 'BCTC · KQKD',
    def: 'Mỗi 100 đồng doanh thu, nghề chính giữ lại mấy đồng trước lãi vay & thuế.',
    why: 'Đo hiệu quả vận hành thuần — không bị "làm đẹp" bởi đòn bẩy tài chính.',
    formula: 'LN hoạt động ÷ Doanh thu × 100', parts: [],
    example: '7,6 ÷ 62,8 = 12,1%.',
    up: 'Tốt', down: 'Cần xem chi phí', flat: '',
    pitfalls: 'So cùng ngành; ngành chu kỳ biên lên xuống theo giá hàng hóa.',
    unit: '%', terms: [], lesson: 'bao-cao-tai-chinh-2-ket-qua', task: null },
  netIncome: { labelVi: 'Lợi nhuận ròng', en: 'Net Income', cat: 'BCTC · KQKD',
    def: 'Phần CÙNG CỰC còn lại sau MỌI chi phí: giá vốn, vận hành, lãi vay, thuế — "thu nhập" của cổ đông theo sổ sách.',
    why: 'Là tử số của EPS → P/E — con số mà thị trường treo giá lên.',
    formula: 'LN hoạt động − Lãi vay − Thuế (+ thu nhập khác)', parts: [],
    example: 'Doanh thu 100, mọi chi phí 88 → LN ròng 12 (chưa chắc 12 đã thành tiền mặt!).',
    up: 'Kiếm nhiều hơn', down: 'Chi phí/thuế tăng hoặc doanh thu giảm', flat: '',
    pitfalls: 'Lợi nhuận là QUAN ĐIỂM kế toán — có thể đẹp mà két sắt rỗng; kiểm tra bằng OCF.',
    unit: 'tỷ ₫ / tỷ $', terms: ['EPS'], lesson: 'bao-cao-tai-chinh-2-ket-qua', task: 'health-check' },
  netMargin: { labelVi: 'Biên lợi nhuận ròng', en: 'Net Margin', cat: 'BCTC · KQKD',
    def: 'Mỗi 100 đồng bán ra, cuối cùng về tay cổ đông mấy đồng.',
    why: 'Gộp cả 3 chuyện: định giá, vận hành, tài chính — tóm tắt "chất lượng" một con số.',
    formula: 'LN ròng ÷ Doanh thu × 100', parts: [],
    example: 'Doanh thu 120, LN 12 → biên 10%.',
    up: 'Mỗi đồng doanh thu tạo nhiều lợi nhuận hơn — nhưng kiểm tra khoản bất thường', down: 'Bị bào mòn', flat: '',
    pitfalls: 'Một quý bán đất làm biên nhảy — loại khoản một lần trước khi kết luận.',
    unit: '%', terms: ['Biên lợi nhuận (Profit Margin)'], lesson: 'bao-cao-tai-chinh-2-ket-qua', task: null },
  eps: { labelVi: 'EPS — Lợi nhuận trên mỗi cổ phiếu', en: 'Earnings Per Share', cat: 'Định giá',
    def: 'Lợi nhuận ròng chia đều cho từng cổ phiếu — "lương" 1 cp kiếm được trong năm.',
    why: 'Là cây cầu giữa doanh nghiệp và giá cổ phiếu: từ EPS tính ra P/E.',
    formula: 'LN ròng ÷ Số cổ phiếu đang lưu hành', parts: [],
    example: '7.300 tỷ ₫ ÷ 1,46 tỷ cp = ~5.000₫/cp.',
    up: 'Mỗi cp đang kiếm nhiều hơn', down: 'Ít hơn (hoặc cp nhiều lên mà lãi không tăng)', flat: '',
    pitfalls: 'Phát hành thêm cp làm EPS LOÃNG — theo dõi số cp tăng liên tục không; EPS âm thì P/E mất nghĩa.',
    unit: '₫ hoặc $ / cp', terms: ['EPS'], lesson: 'bao-cao-tai-chinh-2-ket-qua', task: 'valuation' },
  pe: { labelVi: 'P/E — Giá trên lợi nhuận', en: 'Price-to-Earnings (trailing)', cat: 'Định giá',
    def: 'Bạn đang trả mấy đồng cho mỗi 1 đồng lợi nhuận MỖI NĂM của công ty (12 tháng qua).',
    why: 'Thước đo "đắt/rẻ" phổ biến nhất — nhưng chỉ có nghĩa khi so cùng ngành, so chính nó, so tăng trưởng.',
    formula: 'Giá cổ phiếu ÷ EPS', parts: [],
    example: 'Giá 68.300₫ ÷ EPS 5.000₫ = P/E 13,7 lần.',
    up: 'Thị trường kỳ vọng tăng trưởng lớn (hoặc đang lố)', down: 'Kỳ vọng thấp / đang rẻ — hoặc DN đang hỏng', flat: '',
    pitfalls: 'Bẫy giá rẻ: P/E thấp vì tương lai xấu; EPS âm thì KHÔNG hiển thị P/E như số bình thường. P/E ngành ngân hàng ~10 là thường, công nghệ ~30 cũng thường.',
    unit: 'lần', terms: ['P/E'], lesson: 'chi-so-dinh-gia', task: 'valuation' },
  forwardPE: { labelVi: 'P/E dự phóng', en: 'Forward P/E', cat: 'Định giá',
    def: 'Giá ÷ EPS dự KIẾN của năm tới — nhìn về trước thay vì sau lưng.',
    why: 'Giá cổ phiếu phản ánh TƯƠNG LAI: forward < trailing = thị trường expects lợi nhuận tăng.',
    formula: 'Giá ÷ EPS dự phóng năm tới', parts: [],
    example: 'P/E thường 20 nhưng EPS dự kiến +25% → forward 16.',
    up: '', down: '', flat: '',
    pitfalls: 'Dự phóng là ƯỚC LƯỢNG của phân tích viên — có thể sai; xem kèm tỷ lệ đạt dự báo trước đây.',
    unit: 'lần', terms: ['P/E'], lesson: 'chi-so-dinh-gia', task: null },
  pb: { labelVi: 'P/B — Giá trên giá trị sổ sách', en: 'Price-to-Book', cat: 'Định giá',
    def: 'Giá thị trường đang trả mấy lần GIÁ TRỊ SỔ SÁCH của tài sản ròng (vốn chủ).',
    why: 'Hữu ích cho ngành "nặng tài sản": ngân hàng, bảo hiểm, sản xuất, BĐS.',
    formula: 'Giá ÷ (Vốn chủ sở hữu ÷ Số cp)', parts: [],
    example: 'Vốn chủ 31 nghìn tỷ ÷ 1,46 tỷ cp ≈ 21.200₫/cp sổ sách; giá 68.300₫ → P/B ≈ 3,2.',
    up: 'Thị trường trả hơn giá trị tài sản (thương hiệu/mói kinh doanh)', down: 'Gần giá trị thanh lý', flat: '',
    pitfalls: 'P/B < 1 có thể rẻ — hoặc tài sản trên sổ đã mục ruỗng; công nghệ nhẹ tài sản P/B rất cao vẫn hợp lý.',
    unit: 'lần', terms: ['P/B'], lesson: 'chi-so-dinh-gia', task: null },
  roe: { labelVi: 'ROE — Sinh lời trên vốn chủ', en: 'Return on Equity', cat: 'Chất lượng',
    def: 'Với mỗi 100 đồng vốn THẬT của chủ sở hữu, doanh nghiệp tạo ra mấy đồng lợi nhuận trong kỳ.',
    why: 'Đo hiệu quả "biến vốn thành lãi" — chỉ số chất lượng được xem nhiều nhất.',
    formula: 'LN ròng ÷ Vốn chủ sở hữu (bình quân) × 100', parts: ['Bình quân: (đầu kỳ + cuối kỳ) ÷ 2 để công bằng hơn'],
    example: 'LN 12, vốn chủ bình quân 60 → ROE 20%.',
    up: 'Dùng vốn hiệu quả — HOẶC do nợ cao đẩy lên (xem kèm Nợ/Vốn — DuPont)', down: 'Vốn sinh lời kém', flat: '',
    pitfalls: 'Không kết luận từ 1 năm/1 chỉ số; ROE cao + nợ nhẹ mới thật chất lượng.',
    unit: '%', terms: ['ROE'], lesson: 'chi-so-dinh-gia', task: 'dupont' },
  roa: { labelVi: 'ROA — Sinh lời trên tài sản', en: 'Return on Assets', cat: 'Chất lượng',
    def: 'Mỗi 100 đồng TỔNG tài sản (kể cả tiền đi vay) sinh ra mấy đồng lợi nhuận.',
    why: 'Không bị đòn bẩy làm đẹp: ROA thấp + ROE cao = đang "gánh nợ ra vẻ".',
    formula: 'LN ròng ÷ Tổng tài sản × 100', parts: [],
    example: '7,3 ÷ 58 = 12,6%.',
    up: 'Máy kiếm tiền thật sự hiệu quả', down: 'Tài sản đang nằm phí', flat: '',
    pitfalls: 'Ngành nhẹ tài sản (phần mềm) ROA tự nhiên cao hơn nhà máy nặng máy móc.',
    unit: '%', terms: ['ROA'], lesson: 'chi-so-dinh-gia', task: 'dupont' },
  debtToEquity: { labelVi: 'Nợ / Vốn chủ', en: 'Debt-to-Equity', cat: 'Rủi ro tài chính',
    def: 'Bao nhiêu đồng nợ trên mỗi 1 đồng vốn thật của chủ sở hữu.',
    why: 'Nợ là "tăng tốc 2 chiều": thời tốt lợi nhuận nhân lên, thời xấu đẩy doanh nghiệp vào vực.',
    formula: 'Tổng nợ phải trả ÷ Vốn chủ sở hữu × 100', parts: [],
    example: 'Nợ 40, vốn 60 → 66,7%.',
    up: 'Đòn bẩy mạnh thêm — lợi nhuận VÀ rủi ro cùng tăng', down: 'Gánh nợ nhẹ đi', flat: '',
    pitfalls: 'Nợ không tự động xấu — phải xem dùng nợ làm gì, dòng tiền trả nổi không; NGÂN HÀNG nợ cao là bản chất ngành.',
    unit: '%', terms: ['Nợ phải trả (Liabilities)', 'Vốn chủ sở hữu (Equity)'], lesson: 'bao-cao-tai-chinh-1-can-doi', task: 'health-check' },
  currentRatio: { labelVi: 'Hệ số thanh toán hiện hành', en: 'Current Ratio', cat: 'Rủi ro tài chính',
    def: 'Tài sản sẽ về tiền trong 12 tháng đủ trả nợ đến hạn trong 12 tháng mấy lần.',
    why: 'Đo "hơi thở" ngắn hạn — công ty lãi trên giấy vẫn chết nếu thiếu tiền trả lương.',
    formula: 'Tài sản ngắn hạn ÷ Nợ ngắn hạn', parts: [],
    example: 'Tài sản NH 50 ÷ nợ NH 25 = 2,0 lần.',
    up: 'Thanh khoản thoải mái', down: 'Dưới 1 = thiếu tài sản trả nợ đến hạn — hỏi sâu dòng tiền', flat: '',
    pitfalls: 'Quá cao cũng không tốt — tiền/hàng nằm chết không sinh lời.',
    unit: 'lần', terms: ['Hệ số thanh toán hiện hành (Current Ratio)'], lesson: 'bao-cao-tai-chinh-1-can-doi', task: null },

  // ── BẢNG CÂN ĐỐI ────────────────────────────────────────────
  totalAssets: { labelVi: 'Tổng tài sản', en: 'Total Assets', cat: 'BCTC · Cân đối',
    def: 'Toàn bộ những gì doanh nghiệp đang SỞ HỮU: tiền, kho, phải thu, nhà xưởng, thương hiệu đã mua...',
    why: 'Là "cỗ máy" sản xuất ra doanh thu — nhưng tài sản to chưa chắc tốt nếu không sinh lời (xem ROA).',
    formula: 'Tài sản ngắn hạn + Tài sản dài hạn', parts: [],
    example: 'Tiền 5 + kho 3 + nhà xưởng 50 = 58.',
    up: 'Đang mở rộng quy mô máy móc', down: 'Thanh lý/co lại', flat: '',
    pitfalls: 'Tài sản ghi theo GIÁ SỔ SÁCH có thể lạc hậu (đất 20 năm trước); goodwill "ảo" hơn nữa.',
    unit: 'tỷ ₫ / tỷ $', terms: ['Tài sản (Assets)'], lesson: 'bao-cao-tai-chinh-1-can-doi', task: null },
  totalLiabilities: { labelVi: 'Tổng nợ phải trả', en: 'Total Liabilities', cat: 'BCTC · Cân đối',
    def: 'Toàn bộ những gì doanh nghiệp đang NỢ: nhà cung cấp, lương, thuế, vay ngân hàng, trái phiếu...',
    why: 'Cùng tài sản, nợ càng nhiều thì phần THẬT của cổ đông càng ít — và nghĩa vụ trả càng nặng.',
    formula: 'Nợ ngắn hạn + Nợ dài hạn', parts: [],
    example: 'Nợ nhà cung cấp 10 + vay ngân hàng 17 = 27.',
    up: 'Đang vay/chiếm dụng nhiều hơn', down: 'Trả bớt nợ', flat: '',
    pitfalls: 'Nợ nhà cung cấp (không lãi) khác vay ngân hàng (có lãi) — chất lượng nợ quan trọng bằng số lượng.',
    unit: 'tỷ ₫ / tỷ $', terms: ['Nợ phải trả (Liabilities)'], lesson: 'bao-cao-tai-chinh-1-can-doi', task: null },
  equity: { labelVi: 'Vốn chủ sở hữu', en: 'Equity', cat: 'BCTC · Cân đối',
    def: 'Phần THẬT thuộc về cổ đông = toàn bộ tài sản − toàn bộ nợ. Nếu thanh lý hết, trả nợ xong, cổ đông nhận chừng này.',
    why: 'Là "đệm an toàn" hấp thụ thua lỗ — vốn chủ dày thì công ty chịu được bão.',
    formula: 'Tổng tài sản − Tổng nợ phải trả', parts: [],
    example: '58 − 27 = 31.',
    up: 'Tích lũy lợi nhuận giữ lại / góp thêm', down: 'Lỗ ròng làm bào mòn', flat: '',
    pitfalls: 'Vốn chủ tăng do phát hành cp (loãng) khác với tăng do lợi nhuận giữ lại (tốt) — đọc 2 dòng này riêng.',
    unit: 'tỷ ₫ / tỷ $', terms: ['Vốn chủ sở hữu (Equity)'], lesson: 'bao-cao-tai-chinh-1-can-doi', task: 'health-check' },
  receivables: { labelVi: 'Khoản phải thu', en: 'Receivables', cat: 'BCTC · Cân đối',
    def: 'Tiền khách NỢ doanh nghiệp — hàng đã giao, hóa đơn đã ghi doanh thu, nhưng chưa thu tiền.',
    why: 'Phải thu phình nhanh hơn doanh thu = "bán chịu mua doanh thu" — nguyên nhân số 1 của OCF kém.',
    formula: 'Tổng các khoản khách nợ tại thời điểm chụp', parts: [],
    example: 'Phải thu 13,5 tăng 23% trong khi doanh thu chỉ +19% → đang nới tín dụng cho khách.',
    up: 'Cần xem có thu hồi nổi không', down: 'Thu tiền gọn hơn', flat: '',
    pitfalls: 'Phải thu cũ难 thu phải lập dự phòng — lúc xóa sổ lợi nhuận tụt một cú.',
    unit: 'tỷ ₫ / tỷ $', terms: [], lesson: 'bao-cao-tai-chinh-3-luu-chuyen-tien', task: 'red-flags' },
  inventory: { labelVi: 'Tồn kho', en: 'Inventory', cat: 'BCTC · Cân đối',
    def: 'Hàng hóa/nguyên liệu đang nằm chờ bán.',
    why: 'Tiền bị "đóng băng" trong kho — tồn kho tăng nhanh hơn doanh thu = hàng bán chậm.',
    formula: 'Giá trị kho tại thời điểm chụp', parts: [],
    example: 'Kho +32%/năm trong khi doanh thu +19% → dư thừa 13 điểm % — dấu hiệu cầu yếu.',
    up: 'Có thể chuẩn bị đơn lớn — hoặc bán chậm', down: 'Bán nhanh/chuẩn kho', flat: '',
    pitfalls: 'Kho dễ bị lỗi thời (điện tử, thời trang) → giảm giá trị mạnh một lần.',
    unit: 'tỷ ₫ / tỷ $', terms: [], lesson: 'bao-cao-tai-chinh-1-can-doi', task: 'red-flags' },
  goodwill: { labelVi: 'Goodwill (lợi thế thương mại)', en: 'Goodwill', cat: 'BCTC · Cân đối',
    def: 'Phần trả THƯA khi mua công ty khác so với giá trị tài sản ròng của họ — giá của "thương hiệu, khách hàng, đội ngũ".',
    why: 'Goodwill khổng lồ = đã mua đắt — một ngày phải "xóa sổ" làm lợi nhuận tụt không báo trước.',
    formula: 'Giá mua − Giá trị tài sản ròng được mua', parts: [],
    example: 'Mua công ty tài sản đáng 10 nhưng trả 25 → goodwill 15 (chiếm to trong vốn chủ là đèn vàng).',
    up: '', down: '', flat: '',
    pitfalls: 'Không phải tài sản bán được; Goodwill/VCSH > 30% là dấu hiệu cần kiểm tra M&A',
    unit: 'tỷ ₫ / tỷ $', terms: ['Goodwill'], lesson: 'bao-cao-tai-chinh-1-can-doi', task: 'red-flags' },
  shares: { labelVi: 'Số cổ phiếu lưu hành', en: 'Shares Outstanding', cat: 'BCTC · Cân đối',
    def: 'Tổng số cổ phiếu đang tồn tại trên thị trường.',
    why: 'Tử số của EPS và là chỉ báo LOÃNG: cp nhiều lên mà lãi không tăng = phần mỗi cổ đông bị pha loãng.',
    formula: 'Đếm trực tiếp (công ty công bố)', parts: [],
    example: 'Năm sau phát hành thêm 5% số cp: LN giữ nguyên → EPS tự tụt 5%.',
    up: 'Phát hành thêm — hỏi vì sao (vốn cho tăng trưởng hay vá lỗ?)', down: 'Mua lại cp (tốt cho EPS)', flat: '',
    pitfalls: 'Còn quyền chọn/cp chuyển đổi chưa tính — xem EPS pha loãng kỹ hơn.',
    unit: 'tỷ cp', terms: [], lesson: 'bao-cao-tai-chinh-2-ket-qua', task: null },

  // ── DÒNG TIỀN ───────────────────────────────────────────────
  ocf: { labelVi: 'OCF — Dòng tiền từ kinh doanh', en: 'Operating Cash Flow', cat: 'BCTC · Dòng tiền',
    def: 'Tiền THẬT chảy vào két sắt từ buôn bán chính trong kỳ — thu của khách, trừ trả lương/nhà cung cấp.',
    why: 'Lợi nhuận có thể "trang điểm"; tiền trong két thì khó làm đẹp — OCF là phép kiểm tra sự thật.',
    formula: 'Tiền thu từ khách − tiền trả cho hoạt động (không trừ đầu tư dài hạn)', parts: [],
    example: 'Lãi 12 nhưng khách chưa trả → OCF có thể chỉ 3: "lợi nhuận trên giấy".',
    up: 'Kinh doanh tự nuôi mình khỏe', down: 'Tiền chưa về / tồn kho chất', flat: '',
    pitfalls: 'OCF < LN kéo dài nhiều kỳ = bẫy số 1 của người mới; ngược lại OCF > LN dư sức là tốt.',
    unit: 'tỷ ₫ / tỷ $', terms: ['OCF (Operating Cash Flow)'], lesson: 'bao-cao-tai-chinh-3-luu-chuyen-tien', task: 'cashflow-quality' },
  capex: { labelVi: 'CAPEX — Chi phí đầu tư', en: 'Capital Expenditure', cat: 'BCTC · Dòng tiền',
    def: 'Tiền chi mua/sửa tài sản dài hạn: nhà xưởng, máy móc, công nghệ.',
    why: 'Chi phí "nuôi tương lai" — CAPEX lớn ở công ty tăng trưởng là đầu tư, ở công ty già là dấu hỏi.',
    formula: 'Tổng tiền đầu tư tài sản dài hạn trong kỳ', parts: [],
    example: 'OCF 7,9 − CAPEX 3,8 = FCF 4,1 (quy ước trên web: CAPEX nhập số DƯƠNG rồi trừ).',
    up: 'Đang mở rộng', down: 'Thắt lưng', flat: '',
    pitfalls: 'Chú ý quy ước dấu: nếu nguồn ghi CAPEX âm (−3,8) thì FCF = OCF + CAPEX — đừng trừ 2 lần!',
    unit: 'tỷ ₫ / tỷ $', terms: ['CAPEX'], lesson: 'bao-cao-tai-chinh-3-luu-chuyen-tien', task: null },
  fcf: { labelVi: 'FCF — Dòng tiền tự do', en: 'Free Cash Flow', cat: 'BCTC · Dòng tiền',
    def: 'Tiền còn lại SAU khi nuôi xong cơ sở vật chất — phần thật sự "tự do" để trả nợ, mua lại cp, chia cổ tức.',
    why: 'Được gọi là "oxy của cổ đông" — lợi nhuận có thể ảo, FCF âm nhiều năm thì khó ảo.',
    formula: 'FCF = OCF − CAPEX (CAPEX dương)', parts: [],
    example: 'OCF 15 − CAPEX 5 = FCF 10.',
    up: 'Nhiều oxy hơn', down: 'Đang nuốt tiền của cổ đông (đầu tư nặng hoặc kinh doanh yếu)', flat: '',
    pitfalls: 'Am liên tục ở công ty TRƯỞNG THÀNH là cảnh báo; ở công ty trẻ đang xây có thể chấp nhận.',
    unit: 'tỷ ₫ / tỷ $', terms: ['FCF (Free Cash Flow)'], lesson: 'bao-cao-tai-chinh-3-luu-chuyen-tien', task: 'cashflow-quality' },
  ocfToNi: { labelVi: 'OCF / Lợi nhuận ròng', en: 'OCF-to-Net-Income', cat: 'Chất lượng dòng tiền',
    def: 'Bao nhiêu % lợi nhuận trên giấy đã THÀNH TIỀN thật — bộ lọc chất lượng số 1 của analyst.',
    why: 'Một chỉ số thay cho cả câu hỏi "sếp trả lương bằng tiền hay bằng giấy?".',
    formula: 'OCF ÷ LN ròng × 100', parts: [],
    example: '7,9 ÷ 7,3 = 108% — lợi nhuận chuyển tiền THẬA cả 8%.',
    up: '≥100% rất thật', down: '<50% kéo dài = phải hỏi sâu (Bài 11)', flat: '80-100% ổn',
    pitfalls: 'Một năm xấu do thu tiền trễ quý chưa kết luận — xem ít nhất 2-3 năm.',
    unit: '%', terms: ['OCF (Operating Cash Flow)'], lesson: 'bao-cao-tai-chinh-3-luu-chuyen-tien', task: 'cashflow-quality' },
  dividends: { labelVi: 'Cổ tức', en: 'Dividends', cat: 'Thu nhập cổ đông',
    def: 'Phần lợi nhuận công ty chia TẶNG cho cổ đông, thường bằng tiền mặt theo mỗi cp.',
    why: 'Là một trong 2 cách kiếm tiền từ cp (cách còn lại: giá tăng) — nguồn thu nhập "passive" cho dài hạn.',
    formula: 'Quyết định của HĐQT theo từng năm (không cố định)', parts: [],
    example: 'Cổ tức 2.000₫/cp trên giá 68.300₫ → yield ≈ 2,9%/năm.',
    up: 'Công ty dư tiền và hào phóng', down: 'Giữ tiền tái đầu tư (hoặc lỗ!)', flat: '',
    pitfalls: 'Cổ tức cao bất thường có thể là "đánh bóng" trước khi xấu đi; cổ tức phải bền mới đáng tiền.',
    unit: '₫ / $ trên cp', terms: ['Cổ tức (Dividend)'], lesson: 'co-phieu-la-gi', task: 'dividend-portfolio' },
  dividendYield: { labelVi: 'Tỷ suất cổ tức', en: 'Dividend Yield', cat: 'Thu nhập cổ đông',
    def: 'Cổ tức 1 năm chia cho GIÁ hiện tại — "lãi suốt" nếu bạn mua ở giá này và giữ nguyên.',
    why: 'So sánh cổ tức với gửi tiết kiệm/trái phiếu — nhưng phải kèm đánh giá BỀN của cổ tức.',
    formula: 'Cổ tức mỗi cp ÷ Giá cp × 100', parts: [],
    example: '2.000₫ ÷ 68.300₫ = 2,9%.',
    up: 'Hấp dẫn hơn (hoặc giá đang rơi)', down: 'Ít hấp dẫn', flat: '',
    pitfalls: 'Yield 9% với payout 140% = cái bẫy (chia hơn cả kiếm — không bền). Yield phải đọc kèm payout.',
    unit: '%', terms: ['Cổ tức (Dividend)'], lesson: 'co-phieu-la-gi', task: 'dividend-portfolio' },

  // ── BIỂU ĐỒ NẾN ─────────────────────────────────────────────
  open: { labelVi: 'Giá mở cửa', en: 'Open', cat: 'Biểu đồ',
    def: 'Giá khớp đầu tiên của phiên — điểm xuất phát của thân nến.', why: 'Cho biết tâm thế mở phiên: mở cao = háo hức mua.',
    formula: 'Lệnh khớp đầu phiên', parts: [], example: 'Mở 67.500₫, đóng 68.300₫ → nến xanh.', up: '', down: '', flat: '',
    pitfalls: 'Phiên VN có khớp lệnh định kỳ ATO — mở cửa có thể nhảy xa hôm trước (gap).', unit: '₫ / $', terms: ['Giá mở cửa (Open)'], lesson: 'doc-hieu-bieu-do-nen', task: null },
  high: { labelVi: 'Giá cao nhất', en: 'High', cat: 'Biểu đồ',
    def: 'Đỉnh giá phiên chạm được — mép TRÊN của ria nến.', why: 'Vùng kháng cự tự nhiên: nơi phe bán từng áp đảo.',
    formula: 'Max giá trong phiên', parts: [], example: 'Chạm 69.600 rồi đóng 68.300 → ria trên 1.300₫.', up: '', down: '', flat: '',
    pitfalls: 'Chạm đỉnh ≠ giữ đỉnh — xem nơi ĐÓNG mới là kết luận phiên.', unit: '₫ / $', terms: ['Kháng cự (Resistance)'], lesson: 'doc-hieu-bieu-do-nen', task: null },
  low: { labelVi: 'Giá thấp nhất', en: 'Low', cat: 'Biểu đồ',
    def: 'Đáy giá phiên — mép DƯỚI ria nến.', why: 'Vùng hỗ trợ tự nhiên: nơi phe mua từng vào gom.',
    formula: 'Min giá trong phiên', parts: [], example: 'Đáy 68.000 kéo lên đóng 68.300 → phe mua bảo vệ vùng này.', up: '', down: '', flat: '',
    pitfalls: 'Ria dưới DÀI sau đợt giảm = tín hiệu "ai đó hút hàng ở đáy" — không phải đảm bảo đáy.', unit: '₫ / $', terms: ['Hỗ trợ (Support)'], lesson: 'doc-hieu-bieu-do-nen', task: null },
  close: { labelVi: 'Giá đóng cửa', en: 'Close', cat: 'Biểu đồ',
    def: 'Giá khớp CUỐI phiên — con số quan trọng nhất: mọi chỉ báo (MA, RSI...) đều tính từ close.',
    why: 'Là "phiếu bầu cuối cùng" của phiên — quyết định màu nến và là mốc so cho ngày mai.',
    formula: 'Lệnh khớp cuối phiên (ATC ở VN)', parts: [], example: 'Đóng 68.300 > mở 67.500 → nến xanh.', up: 'Phe mua thắng phiên', down: 'Phe bán thắng', flat: '',
    pitfalls: 'Đóng phiên VN có thể nhảy tại ATC — đừng bất ngờ.', unit: '₫ / $', terms: ['Giá đóng cửa (Close)'], lesson: 'doc-hieu-bieu-do-nen', task: null },

  // ── CHỈ BÁO KỸ THUẬT ────────────────────────────────────────
  rsi14: { labelVi: 'RSI (14 phiên) — Chỉ số sức mạnh tương đối', en: 'Relative Strength Index', cat: 'Kỹ thuật',
    def: 'Tổng kết sức mạnh các phiên tăng so với phiên giảm trong 14 phiên gần nhất thành điểm 0–100.',
    why: 'Đo ĐỘNG LƯỢNG (mua có khỏe không) — không đo hướng dài hạn.',
    formula: '100 − 100 ÷ (1 + RS), với RS = trung bình tăng ÷ trung bình giảm (14 phiên)', parts: [],
    example: 'RSI 46,5 = cân bằng, hơi lệch phe bán.',
    up: '>70 = QUÁ MUA (mua đã kéo dài, cẩn trọng điều chỉnh — không phải lệnh bán!)', down: '<30 = QUÁ BÁN', flat: '30–70 trung tính',
    pitfalls: 'Bẫy số 1: trong xu hướng tăng mạnh RSI "mắc kẹt" trên 70 nhiều tuần — bán ở 70 là bỏ lỡ sóng.',
    unit: 'điểm', terms: ['RSI'], lesson: 'rsi-dong-luong', task: 'entry-point' },
  macd: { labelVi: 'MACD — Hội tụ/phân kỳ trung bình động', en: 'MACD (12,26,9)', cat: 'Kỹ thuật',
    def: 'Khoảng cách giữa 2 đường trung bình mũ (EMA12 − EMA26) — dương khi sóng ngắn mạnh hơn sóng dài.',
    why: 'Bắt BƯỚC NGOẶT động lượng giữa các đợt sóng trung hạn.',
    formula: 'MACD = EMA(12) − EMA(26); Signal = EMA(9) của MACD', parts: ['EMA: trung bình cho trọng số lớn hơn cho phiên gần'],
    example: 'MACD +303: sóng ngắn đang trên sóng dài khá rõ.',
    up: 'Cắt lên Signal/vạch 0: động lượng tăng khởi động', down: 'Cắt xuống: mất tốc', flat: '',
    pitfalls: 'Rất NHIỄU trong thị trường đi ngang (quấn quanh vạch 0); trễ theo bản chất.',
    unit: '₫ / $ (khác scale giá)', terms: ['MACD'], lesson: 'macd-hoi-tu-phan-ky', task: 'entry-point' },
  macdHistogram: { labelVi: 'MACD Histogram', en: 'MACD Histogram', cat: 'Kỹ thuật',
    def: 'Cột = MACD − Signal: "đồng hồ tốc độ" của động lượng.',
    why: 'Cột cao lên = đang mạnh thêm; cụt xuống = đang mất tốc TRƯỚC khi giá đảo.',
    formula: 'MACD − Signal line', parts: [], example: 'Histogram +304 nhưng các cột đang ngắn dần → sóng tăng mất tốc.',
    up: 'Cột xanh dài dần = tăng tốc', down: 'Cột đỏ dài dần = giảm tốc', flat: '',
    pitfalls: 'Đọc XU HƯỚNG chiều cao cột (mạnh lên/yếu đi), không chỉ âm/dương.',
    unit: '₫ / $', terms: ['Histogram'], lesson: 'macd-hoi-tu-phan-ky', task: null },
  bollingerBands: { labelVi: 'Bollinger Bands — Dải biến động', en: 'Bollinger Bands (20,2)', cat: 'Kỹ thuật',
    def: 'Dải trên/dưới = MA20 ± 2 độ lệch chuẩn của giá — "vòng đai hô hấp" của biến động.',
    why: 'Giá chỉ thoát ra ngoài dải ~5% số phiên → chạm dải là SỰ KIỆN hiếm đáng chú ý; dải co hẹp (squeeze) thường trước bùng nổ.',
    formula: 'Trên = SMA20 + 2×độ lệch chuẩn; Dưới = SMA20 − 2×độ lệch chuẩn', parts: [],
    example: 'Giá chạm dải dưới trong thị trường đi ngang → thường bật về giữa.',
    up: 'Chạm dải trên = sóng mua rất mạnh (cẩn trọng hạ nhiệt)', down: 'Chạm dải dưới = áp lực bán kéo dài', flat: '',
    pitfalls: 'Chạm dải KHÔNG tự động là lệnh mua/bán — trong xu hướng giá "trượt dọc" dải nhiều phiên.',
    unit: '₫ / $', terms: ['Bollinger Bands'], lesson: 'bollinger-bands', task: null },

  // ── VÍ GIẢ LẬP & HỌC TẬP ────────────────────────────────────
  portfolioValue: { labelVi: 'Tổng tài sản ví', en: 'Portfolio Value', cat: 'Ví giả lập',
    def: 'Tiền mặt cộng giá trị thị trường của mọi cp bạn đang giữ.',
    why: 'Con số theo dõi duy nhất của người quản lý danh mục — lãi/lỗ tính từ đây so với vốn ban đầu.',
    formula: 'Tiền mặt + Σ(giá hiện tại × số cp mỗi mã)', parts: [],
    example: 'Tiền 80.000$ + cp đáng 21.500$ = 101.500$.', up: 'Tài sản tăng', down: 'Giảm', flat: '',
    pitfalls: 'Dao động theo thị trường từng ngày — quan trọng là XU HƯỚNG dài hạn và kỷ luật lệnh.',
    unit: '$ / ₫', terms: [], lesson: 'quan-tri-rui-ro', task: 'portfolio' },
  cash: { labelVi: 'Tiền mặt trong ví', en: 'Cash', cat: 'Ví giả lập',
    def: 'Số tiền ẢO chưa dùng để mua cp — sẵn sàng cho cơ hội tiếp theo.',
    why: 'Tiền mặt cũng là một VỊ THẾ: giữ 10-20% giúp mua khi thị trường "sale" mà không phải bán thứ gì.',
    formula: 'Vốn ban đầu − đã mua + đã bán (kể lỗ/lãi)', parts: [],
    example: 'Bắt đầu 100.000$, mua hết 21.500$ → còn 78.500$ tiền mặt.', up: '', down: '', flat: '',
    pitfalls: 'All-in (0 tiền mặt) = không còn đạn khi cơ hội thật đến.',
    unit: '$ / ₫', terms: [], lesson: 'quan-tri-rui-ro', task: 'portfolio' },
  investedValue: { labelVi: 'Giá trị đang đầu tư', en: 'Invested Value', cat: 'Ví giả lập',
    def: 'Tổng tiền đang nằm trong cổ phiếu (theo giá thị trường hiện tại).',
    why: 'Cho biết mức độ "phơi nhiễm rủi ro" — bao nhiêu tài sản đang chịu biến động thị trường.',
    formula: 'Σ(giá hiện tại × số cp)', parts: [], example: '3 mã tổng 21.500$ = 21,5% tài sản đang chịu rủi ro.',
    up: '', down: '', flat: '', pitfalls: 'Tăng đột biến do giá nhảy chứ không phải bạn mua thêm — đọc kèm lịch sử lệnh.',
    unit: '$ / ₫', terms: [], lesson: 'quan-tri-rui-ro', task: 'portfolio' },
  pnl: { labelVi: 'Lãi/Lỗ (PnL)', en: 'Profit & Loss', cat: 'Ví giả lập',
    def: 'Chênh lệch giữa tổng tài sản hiện tại và vốn ban đầu — "thành tích" của bạn.',
    why: 'Thước đo khách quan nhất của kỹ năng — kèm điều kiện: phải đạt bằng KỶ LUẬT chứ không may rủi.',
    formula: 'Tổng tài sản − Vốn khởi đầu', parts: [],
    example: '101.500 − 100.000 = +1.500$ (+1,5%).', up: '', down: '', flat: '',
    pitfalls: 'PnL dương nhờ 1 lệnh may mắn all-in chưa nói lên gì — xem NHẬT KÝ và tỷ lệ lệnh đúng quy trình.',
    unit: '$ / ₫', terms: [], lesson: 'tam-ly-dau-tu', task: null },
  quantity: { labelVi: 'Số lượng cổ phiếu', en: 'Share Quantity', cat: 'Ví giả lập',
    def: 'Số cổ phiếu bạn đang định mua, bán hoặc đang nắm giữ trong một vị thế giả lập.',
    why: 'Số lượng quyết định quy mô rủi ro: cùng một cổ phiếu, mua 100 cổ phiếu sẽ chịu lãi/lỗ gấp 10 lần mua 10 cổ phiếu.',
    formula: 'Giá trị lệnh ÷ Giá một cổ phiếu, sau đó làm tròn theo quy định giao dịch của thị trường.', parts: [],
    example: 'Có 1.000 USD và giá 1 cổ phiếu là 100 USD thì tối đa mua được 10 cổ phiếu, trước khi tính phí.',
    up: 'Tăng số lượng = tăng mức phơi nhiễm với biến động giá', down: 'Giảm số lượng = giảm rủi ro cho một ý tưởng', flat: '',
    pitfalls: 'Không chọn số lượng chỉ vì "có đủ tiền". Trước hết hãy xác định nếu nhận định sai, bạn chấp nhận mất bao nhiêu tiền ảo để học.',
    unit: 'cổ phiếu', terms: ['Vị thế (Position)'], lesson: 'quan-tri-rui-ro', task: 'portfolio' },
  averageCost: { labelVi: 'Giá mua trung bình', en: 'Average Cost', cat: 'Ví giả lập',
    def: 'Giá vốn bình quân cho mỗi cổ phiếu trong vị thế của bạn, sau nhiều lần mua ở các mức giá khác nhau.',
    why: 'Đây là mốc để biết vị thế đang lãi hay lỗ trên giấy; nó khác với giá hiện tại của thị trường.',
    formula: 'Tổng tiền đã mua ÷ Tổng số cổ phiếu đang giữ', parts: [],
    example: 'Mua 10 cổ phiếu giá 100 và 10 cổ phiếu giá 80: giá mua trung bình = (1.000 + 800) ÷ 20 = 90.',
    up: 'Mua thêm ở giá cao hơn làm giá vốn bình quân tăng', down: 'Mua thêm ở giá thấp hơn làm giá vốn bình quân giảm', flat: '',
    pitfalls: 'Bình quân giá xuống không tự làm doanh nghiệp tốt hơn. Chỉ nên thêm vị thế khi luận điểm tài chính vẫn đúng, không phải để xóa cảm giác lỗ.',
    unit: '$ / ₫ cho một cổ phiếu', terms: ['Giá vốn (Cost Basis)'], lesson: 'quan-tri-rui-ro', task: 'portfolio' },
  marketValue: { labelVi: 'Giá trị thị trường của vị thế', en: 'Market Value', cat: 'Ví giả lập',
    def: 'Số tiền vị thế của bạn đáng giá nếu quy đổi theo giá thị trường hiện tại.',
    why: 'Cho biết số tiền thực sự đang biến động cùng cổ phiếu, để bạn kiểm soát mức tập trung của danh mục.',
    formula: 'Giá hiện tại × Số cổ phiếu đang giữ', parts: [],
    example: 'Giữ 20 cổ phiếu, giá hiện tại 105 USD: giá trị thị trường = 20 × 105 = 2.100 USD.',
    up: 'Tăng khi giá cổ phiếu tăng hoặc khi bạn mua thêm', down: 'Giảm khi giá giảm hoặc khi bạn bán bớt', flat: '',
    pitfalls: 'Giá trị thị trường không phải tiền mặt cho đến khi bạn bán. Giá được hiển thị có thể là dữ liệu trễ, nên không dùng để giả định khớp lệnh chính xác từng giây.',
    unit: '$ / ₫', terms: ['Vị thế (Position)'], lesson: 'quan-tri-rui-ro', task: 'portfolio' },
  orderValue: { labelVi: 'Giá trị lệnh ước tính', en: 'Estimated Order Value', cat: 'Ví giả lập',
    def: 'Số tiền dự kiến dùng cho một lệnh mua hoặc thu về từ một lệnh bán, tính theo báo giá đang hiển thị.',
    why: 'Giúp kiểm tra lệnh có vượt số tiền mặt của ví và có quá lớn so với kế hoạch quản trị rủi ro hay không.',
    formula: 'Báo giá hiện tại × Số lượng cổ phiếu', parts: [],
    example: '10 cổ phiếu × 68.300 ₫ = 683.000 ₫ giá trị lệnh ước tính.',
    up: 'Tăng khi giá hoặc số lượng tăng', down: 'Giảm khi giá hoặc số lượng giảm', flat: '',
    pitfalls: 'Đây là ước tính học tập. Báo giá có thể trễ và chưa phản ánh phí, chênh lệch mua-bán hay quy tắc lô giao dịch.',
    unit: '$ / ₫', terms: ['Khối lượng (Volume)'], lesson: 'quan-tri-rui-ro', task: 'portfolio' },
  technicalScore: { labelVi: 'Điểm tín hiệu kỹ thuật', en: 'Technical Signal Score', cat: 'Kỹ thuật',
    def: 'Điểm tổng hợp do web quy ước từ một số chỉ báo kỹ thuật như RSI, MA, MACD và khối lượng.',
    why: 'Nó giúp người học thấy các chỉ báo có thể đồng thuận hay mâu thuẫn, nhưng không thay thế việc đọc doanh thu, lợi nhuận, dòng tiền và rủi ro.',
    formula: 'Tổng hợp quy tắc giáo dục của các chỉ báo, không phải mô hình dự báo lợi nhuận.', parts: [],
    example: 'RSI trung tính, MA tích cực và MACD yếu có thể cho một điểm gần 0: các tín hiệu chưa thống nhất.',
    up: 'Nhiều chỉ báo kỹ thuật đang nghiêng tích cực hơn', down: 'Nhiều chỉ báo kỹ thuật đang nghiêng tiêu cực hơn', flat: 'Tín hiệu đang lẫn lộn hoặc trung tính',
    pitfalls: 'Điểm này không phải khuyến nghị mua/bán và không đo chất lượng doanh nghiệp. Luôn đọc BCTC trước, rồi mới dùng nó làm bối cảnh phụ.',
    unit: 'điểm quy ước', terms: ['RSI', 'MACD'], lesson: 'rsi-dong-luong', task: null },
  xp: { labelVi: 'XP — Điểm kinh nghiệm', en: 'Experience Points', cat: 'Học tập',
    def: 'Điểm tích lũy khi hoàn thành task (đạt ≥60% điểm, làm càng tốt XP càng cao).',
    why: 'Thang đo tiến bộ nghề nghiệp của bạn trong "phòng phân tích": Intern → Junior → Analyst → Senior.',
    formula: 'XP = XP task × (điểm đạt được ÷ điểm tối đa)', parts: [],
    example: 'Task 60 XP làm được 50/60 điểm → nhận 50 XP.', up: '', down: '', flat: '',
    pitfalls: 'Nộp lại lấy điểm cao hơn được — nhưng mục tiêu là HIỂU, không phải grinding XP.',
    unit: 'điểm', terms: [], lesson: null, task: null },
  taskScore: { labelVi: 'Điểm task', en: 'Task Score', cat: 'Học tập',
    def: 'Số mục đúng ÷ tổng mục của phiếu hoàn thành nhiệm vụ (chấm bằng dữ liệu live/case).',
    why: 'Không phải điểm "thi" — là phản hồi chính xác chỗ nào còn hổng để học lại.',
    formula: 'Σ điểm các mục đúng ÷ tổng điểm × 100', parts: [],
    example: '50/60 = 83% → ĐẠT (cần ≥60%).', up: '', down: '', flat: '',
    pitfalls: 'Đạt rồi vẫn nên đọc phản hồi mentor — mục sai chính là chỗ kiến thức thật nằm.',
    unit: 'điểm / %', terms: [], lesson: null, task: null },

  // ── NGUỒN DỮ LIỆU ───────────────────────────────────────────
  freshness: { labelVi: 'Trạng thái dữ liệu', en: 'Data Freshness', cat: 'Nguồn dữ liệu',
    def: 'Mức "tươi" của số liệu: live (vài giây-phút) · delayed (trễ ~15 phút) · eod (cuối ngày) · demo (mô phỏng để học) · manual (bạn tự nhập) · stale (đã cũ).',
    why: 'Biết tin cậy bao nhiêu trước khi kết luận: giá chọn điểm vào có thể trễ vài phút, còn BCTC chỉ mới theo QUÝ.',
    formula: 'Gán bởi hệ thống theo nguồn cung cấp', parts: [],
    example: '"Trễ ~15 phút" (Yahoo VN) — đủ để học phân tích, không đủ để tranh giây lập lệnh.',
    up: '', down: '', flat: '',
    pitfalls: 'Giá cập nhật theo PHÚT còn BCTC theo QUÝ/NĂM — hai loại dữ liệu khác nhau, đừng lẫn. Demo/manual không bao giờ dùng làm kết luận thị trường thật.',
    unit: '', terms: ['EOD (End of Day)'], lesson: 'thi-truong-va-bang-gia', task: null },
  median: { labelVi: 'Median (trung vị)', en: 'Median', cat: 'So sánh',
    def: 'Giá trị ĐỨNG GIỮA sau khi sắp xếp nhóm từ nhỏ đến lớn.',
    why: 'Chuẩn so sánh "bình thường của bọn nó" bền hơn trung bình (không bị 1 giá trị cực đoan kéo lệch).',
    formula: 'Sắp xếp → lấy số giữa (số chẵn thì trung bình 2 số giữa)', parts: [],
    example: 'Ba công ty ROE [15% · 23,5% · 41,5%] → median = 23,5% (số đứng giữa) — không bị mã 41,5% kéo lệch như cách lấy trung bình cộng.',
    up: '', down: '', flat: '',
    pitfalls: 'Median KHÔNG phải điểm chuẩn đúng/sai — chỉ là mốc "trung bình của nhóm đang so".',
    unit: '% / lần / tỷ', terms: [], lesson: 'chi-so-dinh-gia', task: 'peer-compare' },
}

// ── MA20/50/200 sinh ra từ 1 khuôn (giống hệt nhau, khác độ dài) ──
for (const [p, note, cls] of [
  [20, '≈1 tháng giao dịch — nhịp THỞ NGẮN HẠN: giá trên MA20 & MA20 dốc lên = sóng ngắn đẹp; điều chỉnh chạm MA20 bật lên là điểm mua phổ biến', 'ngắn hạn'],
  [50, '≈1 quý — HUYẾT MẠCH TRUNG HẠN: các quỹ trung hạn theo dõi; vùng MA50 là nơi "mua dip" lần 2 được quan tâm', 'trung hạn'],
  [200, '≈1 năm — RANH GIỚI TĂNG/GIẢM DÀI HẠN: giá TRÊN MA200 = "lãnh thổ tăng"; DƯỚI = "lãnh thổ giảm" — nhiều nhà đầu tư chỉ mua khi điều kiện này đúng', 'dài hạn'],
]) {
  METRICS['ma' + p] = {
    labelVi: `MA${p} — Đường trung bình động ${p} phiên`, en: `Moving Average (${p})`, cat: 'Kỹ thuật',
    def: `Trung bình giá đóng cửa của ${p} phiên gần nhất, vẽ liền thành đường — làm mượt nhiễu để lộ xu hướng ${cls}.`,
    why: note,
    formula: `MA${p} = (tổng giá đóng cửa ${p} phiên) ÷ ${p}`, parts: ['Chỉ dùng giá ĐÓNG CỬA', 'Cần đủ dữ liệu lịch sử mới tính được — thiếu là "—"'],
    example: `Giá 68.300 > MA20 67.740 → sóng ngắn đang trên trung bình gần.`,
    up: `Đường dốc lên + giá đứng trên = xu hướng ${cls} tăng`, down: `Giá thủng & đường gập xuống = xu hướng ${cls} suy yếu`, flat: 'Đường đi ngang = thị trường lúng túng, giảm bớt hành động',
    pitfalls: 'MA TRỄ theo bản chất (mô tả quá khứ); trong thị trường đi ngang MA giao cắt loạn xạ — dùng làm BỘ LỌC bối cảnh, không phải cò súng.',
    unit: '₫ / $', terms: ['MA (Đường trung bình)', p === 50 ? 'Golden Cross' : p === 200 ? 'Death Cross' : 'EMA'], lesson: 'duong-trung-binh-ma', task: p === 200 ? null : 'entry-point',
  }
}

export const METRIC_KEYS = Object.keys(METRICS)
